### PR TITLE
Fix PIXI.Graphics.drawTorus() behavior with existing geometry

### PR DESCRIPTION
**Pull request by irongaze**
##### Description of change
Fix for drawTorus() bug #6885

##### Pre-Merge Checklist

- [X] Documentation is changed or added
- [ ] Lint process passed (`npm run lint`)
- [ ] Tests passed (`npm run test`)

### CODE REVIEW

**Review by ivanpopelyshev — APPROVED** [review]
I didnt know we even have a `drawTorus`

**Review by bigtimebuddy — APPROVED** [review]
Thanks @irongaze

**Review by bigtimebuddy — CHANGES_REQUESTED** [review]
Oops, spoke too soon. Better, but I'm seeing this weird artifact:
https://jsfiddle.net/bigtimebuddy/0m891ry4/

**Review by bigtimebuddy — APPROVED** [review]
Fixed example

**Comment by irongaze** [comment]
> Oops, spoke too soon. Better, but I'm seeing this weird artifact:
> https://jsfiddle.net/bigtimebuddy/0m891ry4/

Yeah, wasn't sure what the expected outcome should be with a moveTo followed by a draw call.  My naive understanding would be that the torus segment should still be drawn properly, i.e. that the call to drawTorus() should implicitly end any prior drawing geometry.  Was planning on digging in more tonight to figure it out.  moveTo() + drawRect() works fine, for example.  

It seems like there needs to be a more clear delineation between "draw a full shape" and "draw a path segment" in the Graphics API, where full shape calls implicitly close/complete any prior actions.  But perhaps I'm not understanding the API well enough.

**Comment by bigtimebuddy** [comment]
No, you're right @irongaze. The thing that makes drawTorus different is that the other shapes like drawStar, drawRegularPolygon go thru the `drawShape` API which doesn't have the issue. 

Adding a `finishPoly()` call _before_ adding the arcs fixes the problem. Updated and this is what I would expect to happen:
https://jsfiddle.net/bigtimebuddy/0m891ry4/

**Pull request merged**
