### PR TITLE
A fix to maintain the text gradient when modifying the drop shadow distance.

### PR DESCRIPTION
**Pull request by surtr-isaz**
For example, see: https://pixijs.io/examples/#/text/text.js

In the example above, when modifying the dropShadowDistance, try 100, one will observe the gradient distorting across the 3 lines of text.

Animating it will result in a clearer demonstration. For example, add the following:
```
app.ticker.add((delta) => {
  richText.style.dropShadowDistance += 1;
});
```

This is due to the drop shadow's offset increasing the dimensions of the canvas used to render the text and which the gradient's calculations rely on.

The fix corrects the dimensions by removing this offset thus maintaining the desired gradient.

##### Pre-Merge Checklist

- [x] Tests and/or benchmarks are included
- [x] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by themoonrat** [comment]
Wouldn't this now cause text to get cut off with larger drop shadow distances?

**Comment by surtr-isaz** [comment]
> Wouldn't this now cause text to get cut off with larger drop shadow distances?

Nope, I've tested it with very large values and and it renders correctly.

However, I did not test it with negative values. I just tested negative values the Text example and the current behaviour is that the canvas is cropped. Unfortunately, this doesn't fix that, but at least your gradients remain consistent ...

**Comment by surtr-isaz** [comment]
Perhaps the distance should be absolute ...

**Comment by themoonrat** [comment]
I see, was thinking of a different area of Text code. Thanks for the fix!

**Comment by surtr-isaz** [comment]
My pleasure, gentlemen.

**Pull request merged**
