### PR TITLE
Moves SVG_SIZE and getSvgSize, and docs resources

### PR DESCRIPTION
**Pull request by bigtimebuddy**
_I’m working on a series of incremental changes which remove, reorganize and realign the current utils (aka the “junk drawer” of PixiJS)._

This change combines all the SVG-related stuff together in SVGResource.

### Changed

* Moves `PIXI.utils.SVG_SIZE` to `PIXI.SVGResource.SVG_SIZE`
* Moves `PIXI.utils.getSvgSize` to `PIXI.SVGResource.getSize`
* Documents and exports all resource classes so they show up

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Thought should `getSize` be non-static and private? Is this really a useful API?

**Comment by ivanpopelyshev** [comment]
But please dont fiddle with Resources unless you do something like that (utils optimization), I'm working on them right now.

**Comment by bigtimebuddy** [comment]
This is the only thing I have on my list of changes that touches Resources.

**Comment by ivanpopelyshev** [comment]
Ok, I like it :)

**Comment by ivanpopelyshev** [comment]
I know that SVG is pain and we'll change it many times in nearest future.

**Pull request merged**
