### PR TITLE
Fix AnimatedSprite's current texture index does not match current frame index

### PR DESCRIPTION
**Pull request by JetLua**
##### Description of change

**Note: The page should display 3, which may need to be refreshed many times due to the low probability of bugs.**

demo: https://www.pixiplayground.com/#/edit/oSNBXIXePT__SL3KYhOoI
fixed: https://www.pixiplayground.com/#/edit/7Fjo_WQTq6iloKAAOJ2UN

Because `currentFrame` is computed dynamically, there is always a problem with 
```js
const previousFrame = this.currentFrame;
this._currentTime = frameNumber;
if (previousFrame !== this.currentFrame) {
  ...
}
...
```

**So I added a new property to save the texture index from the last updateTexture.**

##### Pre-Merge Checklist

- [x] Tests and/or benchmarks are included
- [ ] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by themoonrat** [comment]
lgtm - but is there a unit test that can cover why this fix works, and the current code doesn't? https://github.com/pixijs/pixi.js/pull/6274 may have introduced this issue whilst fixing another, but it did also include lots of nice unit tests to narrow down expected behaviour

**Comment by bigtimebuddy** [comment]
I agree with @themoonrat. Can you make a test please @JetLua?

**Comment by JetLua** [comment]
@bigtimebuddy @ivanpopelyshev @themoonrat Updated PR and description.

**Comment by ivanpopelyshev** [comment]
I like the test!

**Comment by JetLua** [comment]
> I like the test!
> 
> Wait, I saw 2 and 1 somehow, in fixed version. Do you have pixijs build somewhere that we can reference from that playground? Also, even if you specify settings in playground - modify code, and press "save" or it wont be really saved. Its buggy.

Yes, the custom url did not take effect.

https://static.lufei.so/tmp/pixi.js

**Comment by bigtimebuddy** [comment]
Checks out https://jsfiddle.net/bigtimebuddy/qwo32ph9/5/

**Pull request merged**
