### PR TITLE
Assignment by value for position/scale/skew/pivot

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
http://www.html5gamedevs.com/topic/23380-position-in-latest-dev-build/

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Please help me to solve it:

I want to destroy or set transform to null in displayObject.destroy();

1. Either we use "transform && transform.position" in getters
2. Either we modify the tests somehow

First way probably loses some performance.
Second way, any call of "displayObject.position" will throw an error after destroy().

I do not know what to do with it.

**Comment by GoodBoyDigital** [comment]
Yo! If you can tweak the test so it passes - I can merge this one in 👍

**Comment by ivanpopelyshev** [comment]
@GoodBoyDigital done.

**Comment by GoodBoyDigital** [comment]
thanks man! 👍

**Pull request merged**
