### PR TITLE
Fixed nested stenicl masks not rendering correctly

### PR DESCRIPTION
**Pull request by ceco-fmedia**
Test case: https://jsfiddle.net/x1zq0xbd/

### CODE REVIEW

**Comment by GoodBoyDigital** [comment]
Thanks for this PR @ceco-fmedia! I will review shortly 👍

**Comment by themoonrat** [comment]
Not my area of expertise, but my only comment is the maths clearly works, but it's not explained. Looking at it from my point of view, in the code at certain points you have 

Math.pow(2, currentMasks + 1) - 1
currentMasks + 1
currentMasks + 1, (2 * sFuncMask) + 1) 

For me, perhaps even just a couple of well named variables that help explain what's being done with a couple of the bits of maths might help others coming to modify the code later

**Comment by ivanpopelyshev** [comment]
Please use "<<" instead of pow, we are working with binary operations here.

**Comment by englercj** [comment]
+1 for more comments, explaining what is happening makes it easier for others to fix it in the future.

**Pull request merged**
