### PR TITLE
Don't call  getter , use  `texture.orig.*` directly.

### PR DESCRIPTION
**Pull request by finscn**
Don't call  getter of `texture.width`/`texture.height`.

 in other places in PIXI , when need texture's size , PIXI use texture.orig.width/height . Why only this place use texture.width/height ?

I've said : " Do similar things in similar way" .
So , whatever use texture.width/height or texture.orig.width/height , The key point is "please use one style".

~~Why don't use `texture.width/height`  :  
see https://github.com/pixijs/pixi.js/issues/3782 . So I think if there is need  `orig.size` , we should use `orig.size` directly.~~

~~The  4 sizes :~~
~~* orig.size~~
~~* frame.size~~
~~* trim.size~~
~~* texture.size~~

~~are different things.~~

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
texture size is the same as orig size

**Comment by finscn** [comment]
@ivanpopelyshev  , in other places in PIXI , when need texture's size , PIXI use `texture.orig.width/height` . Why only this place use `texture.width/height` ?

I've said : " Do similar things in similar way" .
So , whatever use `texture.width/height`  or `texture.orig.width/height` , The key point is "please use one style".

**Comment by finscn** [comment]
@ivanpopelyshev  , please re-think about this issue , thanks.

**Comment by finscn** [comment]
@ivanpopelyshev , I hope the code in the same style.  like  `sprite._texture`

**Comment by ivanpopelyshev** [comment]
You can close this one, i'll do those changes in dev-texture

**Comment by bigtimebuddy** [comment]
@finscn could you update with the latest from dev?

**Comment by finscn** [comment]
@bigtimebuddy  , done.

**Comment by bigtimebuddy** [comment]
@finscn Thanks for all your pull-requests concerning code formatting, consistency and minor optimization issues. We would _love_ to see a larger more substantial pull-request with a bunch of these things together rather than many minor pull-requests.

**Pull request merged**
