### PR TITLE
Convert mixin-get-child-by-name to TS

### PR DESCRIPTION
**Pull request by SerG-Y**
#### Description of change
Converted mixin-get-child-by-name to TS

##### Pre-Merge Checklist
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
thank you @Serg-Y! Might you be interested in doing the other mixins?

**Comment by SerG-Y** [comment]
> thank you @SerG-Y! Might you be interested in doing the other mixins?

@bigtimebuddy yes, and also interested in converting other modules

**Comment by luchidalgo** [comment]
Hi 👋 this PR introduce an error in ts project : this.getChildByName is not a function

**Comment by bigtimebuddy** [comment]
@luchidalgo can you please file an issue with an example that reproduces that?

**Comment by luchidalgo** [comment]
Sorry it was a pixi-viewport lib error that broke pixi build :/

**Comment by bigtimebuddy** [comment]
Okay, you should file an issue there probably? https://github.com/davidfig/pixi-viewport

**Pull request merged**
