### PR TITLE
Fix IE11 canvas renderer setTransform problem

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
Fix for #6587

@afarber

please confirm that pixijs.download/fix-canvas-settransform/pixi-legacy.js works for you.

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Do you think we should do another 5.2.x patch fix for this?

**Comment by afarber** [comment]
> 
> 
> Fix for #6587
> 
> @afarber
> 
> please confirm that pixijs.download/fix-canvas-settransform/pixi-legacy.js works for you.

I have tested on ie11, but then another issue pops up: #6589

**Comment by afarber** [comment]
> please confirm that pixijs.download/fix-canvas-settransform/pixi-legacy.js works for you.

I will test today evening.

I have tried a quick test today morning, but IE11 was acting strangely for me with "security error"

2020-04-26 09_40_45-Window

**Comment by ivanpopelyshev** [comment]
Need more details. Pleae debug it, when exactly that line appears.

Btw, "context does not support premultipliedAlpha:false" hm i think we need to modify our test context settings - not related to the issue.

**Comment by afarber** [comment]
I have tried ie11 multiple times (also InPrivate browsing) with

```
<SCRIPT TYPE="text/javascript" SRC="//cdn.jsdelivr.net/npm/pixi.js@5.2.2/dist/pixi.min.js"></SCRIPT>
<SCRIPT TYPE="text/javascript" SRC="//cdn.jsdelivr.net/npm/pixi.js-legacy@5.2.2/dist/pixi-legacy.min.js"></SCRIPT>
```

but could not reproduce the setTransform problem. 

Then I have tried the new files with:

```
<SCRIPT TYPE="text/javascript" SRC="//cdn.jsdelivr.net/npm/pixi.js@5.2.2/dist/pixi.min.js"></SCRIPT>
<SCRIPT TYPE="text/javascript" SRC="//pixijs.download/fix-canvas-settransform/pixi-legacy.js"></SCRIPT>
```

And did not have any problem as well.

**Comment by afarber** [comment]
Today I have tested 5.2.2 and 5.2.3 with Opera on macOS and Windows 10 - and cannot reproduce the setTransform problem:

image

Then I have tried another test of 5.2.2 and 5.2.3 with ie11 on a different Win10 computer - and cannot reproduce the setTransform problem:

image

**Comment by bigtimebuddy** [comment]
@afarber are you saying this isn’t a reproducible bug anymore?

**Comment by afarber** [comment]
> @afarber are you saying this isn’t a reproducible bug anymore?

Yes, the setTransform issue I had in ie11 after upgrading 5.2.1 to 5.2.2, I cannot reproduce it for you anymore.

However I have 1 user, mailing me about some problem with Opera browser, after I have updated 5.2.1 -> 5.2.2. Then I rolled back to 5.2.1, she reported "oh it works", then today updated to 5.2.3, she mails "the issue is back, cannot play". I tried to get browser version and console output from her, but she says, "my husband is not there, he handles the computer".

I think there is smth changed with pixi-legacy 5.2.1 -> 5.2.2, but you guys are the experts :-)

**Comment by afarber** [comment]
Maybe it is just my situation, but 5.2.4 makes IE11 eat all CPU after some time:

image

Its CPU usage goes to 99% or 100%. Happens for me every time or at least often.

**Pull request merged**
