### PR TITLE
fix Canvas Mesh Render bugs 

### PR DESCRIPTION
**Pull request by qingyangmoke**
1.  fix line gap bug when you set mesh canvasPadding>0 and sprite set scale=-1 
2.  add mesh defaults config object, so you can set change the default canvasPadding value ,specially you use dragonbones with gap line problems you can set `PIXI.mesh.Mesh.defaults.canvasPadding=1`
to fixed gap line problems  

like issue #4046 and #3891

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Seems like a valid fix, but we need fiddle for it anyway.

Can you please move defaults to settings? https://github.com/pixijs/pixi.js/blob/dev/src/core/settings.js

@bigtimebuddy @GoodBoyDigital Regardless of deprecation of canvas renderer, this fix is important for both v4 and v5

**Comment by qingyangmoke** [comment]
@ivanpopelyshev done ! move defaults to settings, ` PIXI.settings.MESH_CANVAS_PADDING = 1;`,please review it, i fix the bug because my team member use dragonbones have this gap line problems yesterday ,i fixed it today, and we  test in my project already, Performing well, please test again ,thx, hope help someone who real need it

**Comment by qingyangmoke** [comment]
when i  init 
 `new PIXI.CanvasRenderer({ 
      resolution: 2, // 
    });`
 and set `PIXI.settings.MESH_CANVAS_PADDING = 2; `
i find perform different，so i check the code, find it is wrong, then i change the `const canvasPadding = mesh.canvasPadding * this.renderer.resolution;` to `const canvasPadding = mesh.canvasPadding / this.renderer.resolution;`    
then test  again
set `PIXI.settings.MESH_CANVAS_PADDING = 2` whether resolution=2 or resolution=1
it perform same  @ivanpopelyshev

**Comment by bigtimebuddy** [comment]
Thanks @qingyangmoke!

**Pull request merged**
