### PR TITLE
Adds Patreon support link

### PR DESCRIPTION
**Pull request by bigtimebuddy**
## Overview

This PR adds a link to Patreon in the console on postinstall when installing **pixi.js**. Many projects are doing this now, and it's a great idea!

screen shot 2018-04-29 at 3 50 38 pm

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Who puts patreon in the console?

**Comment by bigtimebuddy** [comment]
This is becoming super common. Open collective projects have started doing this. More places to remind people about our Patreon the better, including Readme, site and console on install.

**Comment by ivanpopelyshev** [comment]
I mean browser console. Right now people dont use `skipHello` much, but if we post patreon link there, it will leak to their apps.

**Comment by ivanpopelyshev** [comment]
It'll be better if we just post patreon link on top of pixijs website. Right now patreon widget in our landing is not working at all.

**Comment by ivanpopelyshev** [comment]
Also, look here: https://github.com/pixijs/pixi.js , ctrl+F patreon.

**Comment by bigtimebuddy** [comment]
This PR is not for the browser console, it’s in the Terminal when installing.

**Pull request merged**
