### PR TITLE
Make createIndicesForQuads public, add uint32

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
Subj. Follow-up for #5738 . Lets discuss the API.

### CODE REVIEW

**Comment by englercj** [comment]
Rather than a `32-bit` param, what if it just took the buffer and offset as parameters?

```
function createIndicesForQuads(size, outBuffer, offset)
{
    // the total number of indices in our array, there are 6 points per quad.
    const totalIndices = size * 6;

    if ((outBuffer.length - offset) < totalIndices)
        return false;

    // fill `outBuffer`

    return true;
}
```

Another option would be to pass the object to be created as a parameter:

```
function createIndicesForQuads(size, ArrayType)
{
    // the total number of indices in our array, there are 6 points per quad.
    const totalIndices = size * 6;
    const buffer = new ArrayType(totalIndices);

    // fill `buffer`

    return buffer;
}
```

**Comment by ivanpopelyshev** [comment]
> Another option would be to pass the object to be created as a parameter:

Will make our typings harder. There's only Uint16 or Uint32 , we dont need anything else.

offset is kinda good idea, but maybe it needs new function? `fillIndicesForQuads(arr, size, offset1, offset2);`

**Comment by ivanpopelyshev** [comment]
Oh, right, I forgot to say that this thing is mostly for plugins.

**Comment by bigtimebuddy** [comment]
This would be my suggestion.  This is backward compatible, and supports providing Uint32Array. I think it's better than using a boolean.

If `offset` is useful down the road, we can add it, but I don't think we need to pile-on this simple change.

```js
function createIndicesForQuads(size, outBuffer = null)
{
    // the total number of indices in our array, there are 6 points per quad.
    const totalIndices = size * 6;

    outBuffer = outBuffer || new Uint16Array(totalIndices);

    if (outBuffer.length !== totalIndices)
        throw new Error(`Out buffer length is incorrect, got ${outBuffer.length} and expected ${totalIndices}`);

    // fill `outBuffer`
}
```

**Comment by hochuen0** [comment]
Found these in my files, anyone can help me understand it's function?
  FSCK0134.REC
<https://drive.google.com/file/d/0B2J8gZH-_miSQXRSSE8tOXhYMWxqNk1tSDVpb3prRUxtLUFv/view?usp=drivesdk>

  FSCK0127.REC
<https://drive.google.com/file/d/0B2J8gZH-_miSMmptajdsNXJTdzB5VmJfdmxXQVlrS19ZQndr/view?usp=drivesdk>

  FSCK0129.REC
<https://drive.google.com/file/d/0B2J8gZH-_miSLUZEcDB6d0lUNjdURFNvXzlJcTd3T0Jsa0hz/view?usp=drivesdk>
Another suspicious file.

2019-06-05 20:41:01,221 INFO  [ChangeOverTAG ]-[127] VersionUtilssPairedVersion == null, not init

**Comment by ivanpopelyshev** [comment]
@bigtimebuddy OK, done, rebased. We can make a better function with both kind of offsets later.

**Pull request merged**
