### PR TITLE
Allows the user to decide where drop shadows are applied to text

### PR DESCRIPTION
**Pull request by themoonrat**
##### Description of change
Since porting over games from v4 to v5, an issue was noticed where drop shadows were looking different to how they did in v4 (due to my PR https://github.com/pixijs/pixi.js/pull/5375) Namely, for v4, drop shadows occurred only on the 'fill', but for v5 they occur on both the fill and the stroke.

I went around the houses on how to solve this, and I've finalised on letting the user decide what they want. With a new text style property, they can decide whether they want the drop shadow to only occur on the 'fill' (default behaviour, which matches v4), or if they want it to only occur on the stroke (new for v5), or they want it to occur on both (accidental buggy behaviour which v5 does now).

Sorry about introducing the bug in the first place :/

##### Pre-Merge Checklist
- [x] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by themoonrat** [comment]
To compare how things look across the versions, here are some uploads of the text style tool so you can have a play

http://www.moonrat.co.uk/html5/pixi-drop-shadow/v4/
http://www.moonrat.co.uk/html5/pixi-drop-shadow/v5/
http://www.moonrat.co.uk/html5/pixi-drop-shadow/v5-new-settings/

**Comment by themoonrat** [comment]
With both fill and stroke

v4: Does both because of a bug: http://www.moonrat.co.uk/html5/pixi-drop-shadow/v4/#%7B%22style%22%3A%7B%22dropShadow%22%3Atrue%2C%22dropShadowAlpha%22%3A0.4%2C%22dropShadowAngle%22%3A1.5%2C%22dropShadowBlur%22%3A5%2C%22dropShadowColor%22%3A%22%2380ff00%22%2C%22dropShadowDistance%22%3A43%2C%22fill%22%3A%22red%22%2C%22fontSize%22%3A80%2C%22fontWeight%22%3A%22bold%22%2C%22letterSpacing%22%3A1%2C%22lineJoin%22%3A%22round%22%2C%22miterLimit%22%3A5%2C%22padding%22%3A10%2C%22stroke%22%3A%22yellow%22%2C%22strokeThickness%22%3A8%2C%22wordWrapWidth%22%3A0%7D%2C%22background%22%3A%22%23aaaaaa%22%7D

v5: Does both, but because it uses native canvas drop shadows, actually uses the blur property unlike v4 http://www.moonrat.co.uk/html5/pixi-drop-shadow/v5/#%7B%22style%22%3A%7B%22dropShadow%22%3Atrue%2C%22dropShadowAlpha%22%3A0.4%2C%22dropShadowAngle%22%3A1.5%2C%22dropShadowBlur%22%3A5%2C%22dropShadowColor%22%3A%22%2380ff00%22%2C%22dropShadowDistance%22%3A43%2C%22fill%22%3A%22red%22%2C%22fontSize%22%3A80%2C%22fontWeight%22%3A%22bold%22%2C%22letterSpacing%22%3A1%2C%22lineJoin%22%3A%22round%22%2C%22miterLimit%22%3A5%2C%22padding%22%3A10%2C%22stroke%22%3A%22yellow%22%2C%22strokeThickness%22%3A8%2C%22wordWrapWidth%22%3A0%7D%2C%22background%22%3A%22%23aaaaaa%22%7D

v5 fixed: can choose what you want http://www.moonrat.co.uk/html5/pixi-drop-shadow/v5-new-setting/#%7B%22style%22%3A%7B%22dropShadow%22%3Atrue%2C%22dropShadowAlpha%22%3A0.4%2C%22dropShadowAngle%22%3A1.5%2C%22dropShadowBlur%22%3A5%2C%22dropShadowColor%22%3A%22%2380ff00%22%2C%22dropShadowDistance%22%3A43%2C%22fill%22%3A%22red%22%2C%22fontSize%22%3A80%2C%22fontWeight%22%3A%22bold%22%2C%22letterSpacing%22%3A1%2C%22lineJoin%22%3A%22round%22%2C%22miterLimit%22%3A5%2C%22padding%22%3A10%2C%22stroke%22%3A%22yellow%22%2C%22strokeThickness%22%3A8%2C%22wordWrapWidth%22%3A0%7D%2C%22background%22%3A%22%23aaaaaa%22%7D


With just a fill

v4: works, but still doesn't do the blurring properly http://www.moonrat.co.uk/html5/pixi-drop-shadow/v4/#%7B%22style%22%3A%7B%22dropShadow%22%3Atrue%2C%22dropShadowAlpha%22%3A0.4%2C%22dropShadowAngle%22%3A1.5%2C%22dropShadowBlur%22%3A5%2C%22dropShadowColor%22%3A%22%2380ff00%22%2C%22dropShadowDistance%22%3A43%2C%22fill%22%3A%22red%22%2C%22fontSize%22%3A80%2C%22fontWeight%22%3A%22bold%22%2C%22letterSpacing%22%3A1%2C%22lineJoin%22%3A%22round%22%2C%22miterLimit%22%3A5%2C%22padding%22%3A10%2C%22stroke%22%3A%22%22%2C%22strokeThickness%22%3A8%2C%22wordWrapWidth%22%3A0%7D%2C%22background%22%3A%22%23aaaaaa%22%7D

v5 works perfect http://www.moonrat.co.uk/html5/pixi-drop-shadow/v5/#%7B%22style%22%3A%7B%22dropShadow%22%3Atrue%2C%22dropShadowAlpha%22%3A0.4%2C%22dropShadowAngle%22%3A1.5%2C%22dropShadowBlur%22%3A5%2C%22dropShadowColor%22%3A%22%2380ff00%22%2C%22dropShadowDistance%22%3A43%2C%22fill%22%3A%22red%22%2C%22fontSize%22%3A80%2C%22fontWeight%22%3A%22bold%22%2C%22letterSpacing%22%3A1%2C%22lineJoin%22%3A%22round%22%2C%22miterLimit%22%3A5%2C%22padding%22%3A10%2C%22stroke%22%3A%22%22%2C%22strokeThickness%22%3A8%2C%22wordWrapWidth%22%3A0%7D%2C%22background%22%3A%22%23aaaaaa%22%7D

v5 fixed still works, but if you change the drop shadow type to stroke, then correctly no drop shadow appears... because there is no stroke http://www.moonrat.co.uk/html5/pixi-drop-shadow/v5-new-setting/#%7B%22style%22%3A%7B%22dropShadow%22%3Atrue%2C%22dropShadowAlpha%22%3A0.4%2C%22dropShadowAngle%22%3A1.5%2C%22dropShadowBlur%22%3A5%2C%22dropShadowColor%22%3A%22%2380ff00%22%2C%22dropShadowDistance%22%3A43%2C%22fill%22%3A%22red%22%2C%22fontSize%22%3A80%2C%22fontWeight%22%3A%22bold%22%2C%22letterSpacing%22%3A1%2C%22lineJoin%22%3A%22round%22%2C%22miterLimit%22%3A5%2C%22padding%22%3A10%2C%22stroke%22%3A%22%22%2C%22strokeThickness%22%3A8%2C%22wordWrapWidth%22%3A0%7D%2C%22background%22%3A%22%23aaaaaa%22%7D


With just a stroke

v4 doesn't show a drop shadow http://www.moonrat.co.uk/html5/pixi-drop-shadow/v4/#%7B%22style%22%3A%7B%22dropShadow%22%3Atrue%2C%22dropShadowAlpha%22%3A0.4%2C%22dropShadowAngle%22%3A1.5%2C%22dropShadowBlur%22%3A5%2C%22dropShadowColor%22%3A%22%2380ff00%22%2C%22dropShadowDistance%22%3A43%2C%22fill%22%3A%22%22%2C%22fontSize%22%3A80%2C%22fontWeight%22%3A%22bold%22%2C%22letterSpacing%22%3A1%2C%22lineJoin%22%3A%22round%22%2C%22miterLimit%22%3A5%2C%22padding%22%3A10%2C%22stroke%22%3A%22yellow%22%2C%22strokeThickness%22%3A8%2C%22wordWrapWidth%22%3A0%7D%2C%22background%22%3A%22%23aaaaaa%22%7D

v5 shows a drop shadow, even tho v4 didn't http://www.moonrat.co.uk/html5/pixi-drop-shadow/v5/#%7B%22style%22%3A%7B%22dropShadow%22%3Atrue%2C%22dropShadowAlpha%22%3A0.4%2C%22dropShadowAngle%22%3A1.5%2C%22dropShadowBlur%22%3A5%2C%22dropShadowColor%22%3A%22%2380ff00%22%2C%22dropShadowDistance%22%3A43%2C%22fill%22%3A%22%22%2C%22fontSize%22%3A80%2C%22fontWeight%22%3A%22bold%22%2C%22letterSpacing%22%3A1%2C%22lineJoin%22%3A%22round%22%2C%22miterLimit%22%3A5%2C%22padding%22%3A10%2C%22stroke%22%3A%22yellow%22%2C%22strokeThickness%22%3A8%2C%22wordWrapWidth%22%3A0%7D%2C%22background%22%3A%22%23aaaaaa%22%7D

v5 fixed does if set the location to 'stroke', but doesn't if you set it to 'fill' http://www.moonrat.co.uk/html5/pixi-drop-shadow/v5-new-setting/#%7B%22style%22%3A%7B%22dropShadow%22%3Atrue%2C%22dropShadowAlpha%22%3A0.4%2C%22dropShadowAngle%22%3A1.5%2C%22dropShadowBlur%22%3A5%2C%22dropShadowColor%22%3A%22%2380ff00%22%2C%22dropShadowDistance%22%3A43%2C%22dropShadowLocation%22%3A1%2C%22fill%22%3A%22%22%2C%22fontSize%22%3A80%2C%22fontWeight%22%3A%22bold%22%2C%22letterSpacing%22%3A1%2C%22lineJoin%22%3A%22round%22%2C%22miterLimit%22%3A5%2C%22padding%22%3A10%2C%22stroke%22%3A%22yellow%22%2C%22strokeThickness%22%3A8%2C%22wordWrapWidth%22%3A0%7D%2C%22background%22%3A%22%23aaaaaa%22%7D

**Comment by themoonrat** [comment]
Open to making 'both' the default of course. v4 does it but that's not the intent of the code. And the overlapping drop shadows means alpha doubles up so shadows look a lot darker than the settings imply

**Comment by bigtimebuddy** [comment]
The "both" option [gets weird with alpha](http://www.moonrat.co.uk/html5/pixi-drop-shadow/v5-new-setting/#%7B%22style%22%3A%7B%22dropShadow%22%3Atrue%2C%22dropShadowAlpha%22%3A0.2%2C%22dropShadowAngle%22%3A1.5%2C%22dropShadowDistance%22%3A43%2C%22dropShadowLocation%22%3A2%2C%22fill%22%3A%22white%22%2C%22fontSize%22%3A80%2C%22fontWeight%22%3A%22bold%22%2C%22letterSpacing%22%3A1%2C%22lineJoin%22%3A%22round%22%2C%22miterLimit%22%3A5%2C%22padding%22%3A10%2C%22stroke%22%3A%22%230046ff%22%2C%22strokeThickness%22%3A8%2C%22wordWrapWidth%22%3A0%7D%2C%22background%22%3A%22%23aaaaaa%22%7D) because it doubles up the transparency where the fill and stroke shadows overlap.

My developer expectation is that the drop shadow is always both, and the opacity of the stroke + fill is applied evenly (is that even possible?). The user decides if they want a stroke or fill by enabling those Text features. 

There are two visual cases with the PR that I'm not convinced it's worth supporting:

* You have a stroke and fill on Text, but ONLY stroke shadow
* You have a stroke and fill on Text, but ONLY fill shadow

_Maybe_ there's a case that if you need a fill shadow + Text with stroke might be because you want a rollover text effect or something without that changing the shadow. But that case seems small to me. Would like to hear your thoughts about these cases.

**Comment by themoonrat** [comment]
So first assumption I made was wrong, v4 does attempt in code to have a drop shadow contain both the fill and the stroke. But it only tries to do a drop shadow at all if a fill exists. So for v4
Fill & Stroke: drop shadow on both
Fill: drop shadow on fill
Stroke: no drop shadow

Which is odd.

The problem is, the way the Canvas API works, the stroke and the fill always overlap, so using the API to just draw both, either it's via 2 separate draw calls (like v4) or via the native canvas api (like v5).... there is always that overlap.

The situation that started this rabbit hole was for situations like: http://www.moonrat.co.uk/html5/pixi-drop-shadow/v5-new-setting/#%7B%22style%22%3A%7B%22dropShadow%22%3Atrue%2C%22dropShadowAlpha%22%3A0.4%2C%22dropShadowAngle%22%3A1.5%2C%22dropShadowBlur%22%3A1%2C%22dropShadowColor%22%3A%22%2380ff00%22%2C%22dropShadowDistance%22%3A43%2C%22dropShadowLocation%22%3A2%2C%22fill%22%3A%22red%22%2C%22fontSize%22%3A80%2C%22fontWeight%22%3A%22bold%22%2C%22letterSpacing%22%3A1%2C%22lineJoin%22%3A%22round%22%2C%22miterLimit%22%3A5%2C%22padding%22%3A10%2C%22stroke%22%3A%22yellow%22%2C%22strokeThickness%22%3A8%2C%22wordWrapWidth%22%3A0%7D%2C%22background%22%3A%22%23aaaaaa%22%7D

This is the new version, set to 'both'. Look at the 2 L's; notice how the drop shadow appears _over the top_ of the stroke? This was what we wanted to avoid. So by separating out the drop shadow setting, you can just have a drop shadow on the stroke, but blur it a lot to fill it in.

http://www.moonrat.co.uk/html5/pixi-drop-shadow/v5-new-setting/#%7B%22style%22%3A%7B%22dropShadow%22%3Atrue%2C%22dropShadowAlpha%22%3A0.7%2C%22dropShadowAngle%22%3A1.5%2C%22dropShadowBlur%22%3A13%2C%22dropShadowColor%22%3A%22%2380ff00%22%2C%22dropShadowDistance%22%3A43%2C%22dropShadowLocation%22%3A1%2C%22fill%22%3A%22red%22%2C%22fontSize%22%3A80%2C%22fontWeight%22%3A%22bold%22%2C%22letterSpacing%22%3A1%2C%22lineJoin%22%3A%22round%22%2C%22miterLimit%22%3A5%2C%22padding%22%3A10%2C%22stroke%22%3A%22yellow%22%2C%22strokeThickness%22%3A8%2C%22wordWrapWidth%22%3A0%7D%2C%22background%22%3A%22%23aaaaaa%22%7D

It's not perfect, but it's better than drop shadows appearing over the top of the stroke.

Now, why does that occur? Because, for some reason, since the very first version of PIXI, the order has been "draw the stroke, then draw the fill". This isn't the way I'd draw text in real life, I'd draw the fill, and then the stroke. And if Pixi did that, my artists wouldn't have noticed anything ;) But if we made that change, then text on everyones Pixi creations would look a _lot_ different. As the stroke and fill overlap, you'd notice strokes effectively look thicker, as they're taking piority over the fill. I'd say that is the correct way, but I don't think we could ever make that change.

v4 doesn't have this issue because it has 2 separate draw calls drawing the shadow underneath manually. But then because of that the 'blur' part of drop shadows really doesn't work well.

So yeah, this PR is to solve an issue caused by something else that cannot be changed!

**Comment by themoonrat** [comment]
Closing in favour of https://github.com/pixijs/pixi.js/pull/5947

**Pull request closed without merging**
