### PR TITLE
Fix for issue #2759

### PR DESCRIPTION
**Pull request by Ayoul**
Fixes align with bitmap fonts when using on maxWidth to make break lines

### CODE REVIEW

**Comment by GoodBoyDigital** [comment]
thanks so much for this @Ayoul would you mind posting a fiddle of this in action so we can verify the fix? Cheers!

**Comment by Ayoul** [comment]
Will do ASAP.

**Comment by GoodBoyDigital** [comment]
thanks @Ayoul 👍

**Comment by GoodBoyDigital** [comment]
poke!

**Comment by Ayoul** [comment]
Sorry, it took so long.

Here you go: http://jsfiddle.net/A_LH/kr8yvdwk/

Tell me if you need anything else!

**Comment by GoodBoyDigital** [comment]
Perfect! Fix verified :D

**Comment by GoodBoyDigital** [comment]
👍

**Pull request merged**
