### PR TITLE
Fix: unsubscribe from old Sprite texture

### PR DESCRIPTION
**Pull request by maximgavrilov**
##### Description of change

Unsubscribe from old texture in Sprite once the new one set.

##### Pre-Merge Checklist

- [X] Tests and/or benchmarks are included
- [X] Lint process passed (`npm run lint`)
- [X] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Its only for the case when texture is not valid. I didnt want to add this thing because I didnt meet the case when it actually led to memory leaks. Whats your case?

**Comment by maximgavrilov** [comment]
No cases yet. Just obvious leak on some execution paths.

**Comment by ivanpopelyshev** [comment]
It also exists in `SimplePlane`. With this PR we introduce a new invariant: sprite can be subscribed only on one not valid texture update.

I leave it to other members of the team, because I dont know whether we should ask all future contributors to maintain it.

**Comment by maximgavrilov** [comment]
If the intend is to provide subscriptions to multiple textures, then `Sprite::_texture` should be an array, not a single var. Because with such intend potential leak will be at the `Sprite::destroy` line: `this._texture.off('update', this._onTextureUpdate, this); ` where no multiple textures are supposed.

**Pull request merged**
