### PR TITLE
[next] Graphics LineStyle refactor

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
I don't like to spawn many objects without prototype.

What if we reduce the number a bit?

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Are you sure that your method `toJSON` has to go?

**Comment by bigtimebuddy** [comment]
The toJSON method isn’t needed. Clone is better for the reasons you point out in maintaining the prototype. Makes it easier to debug, mixin, profile

**Comment by englercj** [comment]
`Rectangle` uses `copyTo` and `copyFrom`. I think `copyTo` was the correct API choice.

**Comment by ivanpopelyshev** [comment]
Oh, then we need to refactor MAtrix too :) ok, moving it back.

**Comment by bigtimebuddy** [comment]
@ivanpopelyshev, could you please remove changes to package-lock.json

**Pull request merged**
