### PR TITLE
Fix lineStyle+fillStyle drawCalls count

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
lineStyle never goes into one drawCall with fillStyle if batching is turned off. That means PixiJS just spams drawCalls for graphics! Bug exists even in 5.0.1

image

Demo has extra feature: it shows wireframe for fills!

Bug, 2 drawcalls: https://www.pixiplayground.com/#/edit/oXRqFpfuva9wwP6B_0V1d

Fixed, 1 drawcall: https://www.pixiplayground.com/#/edit/AjVLQ2NLsXQXM9KrUWCcp

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
This doesn’t make sense to me. Native is a line specific property. It doesn’t make sense to throw it on Fill. Are you sure you’re fixing the right thing here?

**Comment by ivanpopelyshev** [comment]
Oh, right, I didnt explain it, sorry :)

One big problem: https://github.com/pixijs/pixi.js/blob/dev/packages/graphics/src/GraphicsGeometry.js#L653
Not big, but adds extra batch: https://github.com/pixijs/pixi.js/blob/dev/packages/graphics/src/GraphicsGeometry.js#L484

**Comment by bigtimebuddy** [comment]
So fix that case. If native is undefined use false. Don’t change the API to something illogical.

**Comment by ivanpopelyshev** [comment]
OK then, do you want me to change those to `!=` and comment "do not touch that" ?

**Comment by bigtimebuddy** [comment]
Just don't change LineStyle or FillStyle. It's not fixing the problem, it just creating API confusion.

For fills, can you just do `!!style.native`

**Comment by ivanpopelyshev** [comment]
ok, done

**Pull request merged**
