### PR TITLE
Documentation Update: Point.ts

### PR DESCRIPTION
**Pull request by jrod-disco**
##### Description of change
First pass at contributing to the documentation update effort. Please let me know if there is anything I should change or could do better.

* `fix` - update documentation according to: #7159

##### Pre-Merge Checklist
- [x] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by jrod-disco** [comment]
Please note that type inference was not working as expected on `set` which is why I added types/defaults explicitly in the doc.

**Review by bigtimebuddy — APPROVED** [review]
Yes!!! Thank you for helping with this!

**Review by SukantPal — APPROVED** [review]
👏

**Comment by jrod-disco** [comment]
I may have blown away the constructor doc. Will check and push again if needed.
Just noticed as I was working on ObservablePoint.

**Comment by jrod-disco** [comment]
Sorry about that. Pretty sure we want to keep the constructor bit in there yeah? Even if it isn't pure inference.

Should be good now.

image

**Review by SukantPal — APPROVED** [review]

**Pull request merged**
