### PR TITLE
Improved documentation of the destroy method

### PR DESCRIPTION
**Pull request by themoonrat**
Documents the .texture and .baseTexture parameters for the destroy method settings object. They may not be used for the class itself, but could get propagated down to children.
Fixes https://github.com/pixijs/pixi.js/issues/3407

### CODE REVIEW

**Comment by themoonrat** [comment]
@staff0rd how about

     * @param {boolean} [options.texture=false] - Only used for child Sprites if options.children is set to true
     *  Should it destroy the texture of the child sprite
     * @param {boolean} [options.baseTexture=false] - Only used for child Sprites if options.children is set to true
     *  Should it destroy the base texture of the child sprite

**Comment by bigtimebuddy** [comment]
@staff0rd look good?

**Comment by staff0rd** [comment]
all good

**Comment by GoodBoyDigital** [comment]
👍

**Comment by englercj** [comment]
Might be best to move these into a typedef for DestroyOptions or something, then use that everywhere. Instead of maintaining separate lists on each method impl.

**Pull request merged**
