### PR TITLE
Fix for stroke spikes

### PR DESCRIPTION
**Pull request by SebastianNette**
As seen here:
http://jsfiddle.net/ktcy1rd5/

Or here:
http://mokgames.com/playground/pixi/textspike.png

### CODE REVIEW

**Comment by JanAmbrozic** [comment]
This was reverted in next commit (https://github.com/GoodBoyDigital/pixi.js/commit/1a8a041f50564de8be1f09132fd62d18c249da1a). Was that done by mistake or was there a reason behind it? I'm again/still seeing text spikes :(. 

Thanks for answering!

**Comment by englercj** [comment]
@GoodBoyDigital Was this on purpose?

**Comment by GoodBoyDigital** [comment]
I can't quite remember :/  - I definitely think this should be an option passed the the text. possibly in the style params?

**Comment by englercj** [comment]
@GoodBoyDigital That sounds good, I'll open an issue as a reminder for me this weekend.

**Pull request merged**
