### PR TITLE
Fix #2006 by applying texture resolution to crop size

### LINKED ISSUE #2006: Canvas Renderer + Retina (resolution - 2) + Tint not working
http://jsfiddle.net/adireddy/uf1zggL2/

When I tried to apply tint on a retina asset, the image is being cropped.

It works on non-retina asset.

### PR DESCRIPTION
**Pull request by alebianco**
From the tests that i could do, both on desktop, emulators and devices, this seems to fix the issue without side effects ...

### CODE REVIEW

**Comment by stbaer** [comment]
Hi @alebianco - thank you for looking into this. 

I just tested the pr and it doesn't fix it yet for me. Looks like image positions are off, for example if the anchor is set to 0.5.

**Comment by alebianco** [comment]
looks like i've been to optimistic in reducing the number of multiplications.
i've made explicit multiplications where needed now. not sure if that's preferable to cloning the texture crop or not...

**Comment by stbaer** [comment]
:+1: noice

**Comment by stbaer** [comment]
Looks good for normal images. But the combination CanvasRenderer + Retina + Sprite-sheet doesn't work, neighboring images are overlapping (this might be a different issue though).

**Comment by alebianco** [comment]
any chance you have an example of that?

**Comment by stbaer** [comment]
Am travelling atm, but will try to make a fiddle this weekend or early next week.

**Comment by alebianco** [comment]
I managed to test it, is this what you saw? https://jsfiddle.net/alebianco/vkjeumkb/
it does happen regardless of resolution and i'd say it's a separate issue, even if it's always caused by tinting

**Comment by stbaer** [comment]
Not sure if it's the same problem, but I'd also say it's a separate issue. Will take a closer look soon.

**Comment by alebianco** [comment]
Applying a tint to a spritesheet animation will still display incorrectly, but _static_ images taken from spritesheets should be ok now

**Comment by stbaer** [comment]
Yes, +1 for merging / reviewing this pr.

**Pull request merged**
