### PR TITLE
SpriteRenderer pseudo-leak

### LINKED ISSUE #4090: SpriteRenderer#sprites retains destroyed sprites
Steps

- Take heap snapshot
- add some bunny
- take heap snapshot
- destroy bunnies container
- collect garbage
- take an heap snapshot
- filter by "Objects allocated between Snapshot 1 and Snapshot 2"

Try also to look at  ```app.renderer.plugins.sprite.sprites``` before and after destroy them all

screen shot 2017-06-07 at 16 27 56

[test.zip](https://github.com/pixijs/pixi.js/files/1058342/test.zip)

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
Fixes #4090, same as #4899 

Credit goes to @YahorPadlucki

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
@ivanpopelyshev did you actually test this? There's an example here: https://github.com/pixijs/pixi.js/issues/4090#issuecomment-307018737

**Comment by YahorPadlucki** [comment]
@bigtimebuddy I've tested it with .length=0 ) Will arrange a link to example shortly

**Comment by bigtimebuddy** [comment]
@YahorPadlucki the build is here for this PR: https://pixijs.download/dev-sprite-leak/pixi.js

**Comment by YahorPadlucki** [comment]
link markup doesn't work(

**Comment by GoodBoyDigital** [comment]
sweet 👍

**Pull request merged**
