### PR TITLE
Fix for the SVGResource#valid issue (#5816)

### PR DESCRIPTION
**Pull request by mofnire**
##### Description of change

This PR is for fixing the issue #5816. As described at the issue, a canvas created by `document.createElement('canvas')` may have non-zero width and height. Thus, the method `SVGResource#valid` may return true even when loading is in process. This PR changes the `SVGResource` to set the width / height of a created canvas to zero.

##### Pre-Merge Checklist
- [x] Tests and/or benchmarks are included
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by mofnire** [comment]
> Good idea, but I need to think about better implementation. I'm not comfortable with settings canvas size to 0.

If DOM operations are not preferable, this might be better?
```javascript
options = options || {};

super(document.createElement('canvas'));
this._width = 0;
this._height = 0;
```

Or should I introduce a new property `_hasLoaded`...?

**Comment by bigtimebuddy** [comment]
I like that suggestion better: setting internal width and height to zero, instead of setting canvas.

**Comment by mofnire** [comment]
> I like that suggestion better: setting internal width and height to zero, instead of setting canvas.

I changed the way of solving the issue.

**Comment by bigtimebuddy** [comment]
@ivanpopleyshev, you good with this?

**Comment by ivanpopelyshev** [comment]
Yes, I think so. But I'll check this PR anyway, cant just approve it, its my area of expertise.

**Comment by bigtimebuddy** [comment]
MVP @mofnire! It’s easy to approve PRs with very clear tests, like this. Keep up the good work.

**Comment by mofnire** [comment]
> MVP @mofnire! It’s easy to approve PRs with very clear tests, like this. Keep up the good work.

Thank you ! I will !

**Pull request merged**
