### PR TITLE
chore: add Node.js 10

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Thanks for the PR could you please elaborate why this is useful.

**Comment by DanielRuf** [comment]
Node.js 10 is the current stable branch, 8 the LTS branch. I sometimes see projects failing on Node.js 10 due to code or dependency issues.

Both, stable and LTS, should be tested against, to always ensure that it works there.

**Comment by bigtimebuddy** [comment]
Thanks for this @DanielRuf. Couple of notes about this:

Breakages that happen because of Node.js would most likely occur because of external dependencies breaking. PixiJS is mostly designed for browser and build packaging systems like Webpack and it's not a traditional module run in Node.js directly. I think it's more valid and useful to test against those browser/webpack environments than making sure the build system works on Node 10. 

Also, will only consider this change for v5 (**next** branch), currently we are locking down v4 (**dev**) for major and critical bug fixes only.

**Comment by DanielRuf** [comment]
> Thanks for this @DanielRuf. Couple of notes about this:
> 
> Breakages that happen because of Node.js would most likely occur because of external dependencies breaking. PixiJS is designed for browser and build packaging systems like Webpack and it's not a traditional module run in Node.js directly or utilizing Node.js APIs. I think it's more valid and useful to test against those browser/webpack environments than making sure the build system works on Node 10.
> 
> Also, will only consider this change for v5 (next branch), currently we are locking down v4 (dev) for major and critical bug fixes only.

Ok but keep in mind that CI is mainly just for dev (contributors) and many (including me and my team) use Node.js 10 by default.

**Comment by DanielRuf** [comment]
> Also, will only consider this change for v5 (next branch), currently we are locking down v4 (dev) for major and critical bug fixes only.

Why not just change the branch then instead of closing the PR?

**Comment by bigtimebuddy** [comment]
Because dev and next are not an easy merge right now.

**Comment by bigtimebuddy** [comment]
Also, Travis deploys artifacts (build and docs) to our CDN. Not sure how that works with multiple versions of Node.js, do you?

**Comment by DanielRuf** [comment]
> Because dev and next are not an easy merge right now.

I already switched the branch of the PR ;-)

> Also, Travis deploys artifacts (build and docs) to our CDN. Not sure how that works with multiple versions of Node.js, do you?

You can use `only` and branch and jobs / build matrix feature to do this only with one version / job.

**Comment by DanielRuf** [comment]
See https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix

**Comment by DanielRuf** [comment]
> DanielRuf changed the base branch from dev  to next  2 hours ago

;-)

And the change can be cleanly applied. But we have to use the build matrix feature then (push another commit to this branch / PR).

**Comment by bigtimebuddy** [comment]
We probably only want to deploy using builds and docs generated with Node.js 8. Could you figure out how to add that to the Travis file?

**Comment by DanielRuf** [comment]
Rebased it now.

**Comment by bigtimebuddy** [comment]
Could you add support on Travis only deploying using Node.js 8?

**Comment by DanielRuf** [comment]
Will do so this week.

**Comment by bigtimebuddy** [comment]
Hey @DanielRuf, any update on this?

**Comment by DanielRuf** [comment]
Hi @bigtimebuddy, sorry for the late answer. I was at enterJS and was a bit busy in the last days. I'll try to prioritize it for this weekend.

**Comment by bigtimebuddy** [comment]
I'm going to close to inactivity. If you have time to rework, feel free to re-open.

**Comment by DanielRuf** [comment]
> I'm going to close to inactivity. If you have time to rework, feel free to re-open.

Simple contributors can not reopen closed PRs. Just you can.

**Comment by DanielRuf** [comment]
> If you have time to rework, feel free to re-open.

I would like to if I could, see my previous PR.
I general closing PRs because of inactivity is not so nice as private life and others things often get inbetween and other things, please keep this in your mind ;-)

**Comment by DanielRuf** [comment]
> Just you can.

Or a maintainer with the needed rights.

**Comment by bigtimebuddy** [comment]
Sorry. We often close because of unresponsive-ness. Sometimes people just drop off leaving PRs in limbo. Closing keeps from piling up cruft.

This PR is incomplete and needs to address the deployment issue with Travis. If you don’t have time, no problem. Just holler if you want to make changes and we can reopen.

**Comment by DanielRuf** [comment]
> If you don’t have time, no problem. Just holler if you want to make changes and we can reopen.

> I would like to if I could

**Pull request closed without merging**
