### PR TITLE
Feature/runner improvement

### PR DESCRIPTION
**Pull request by GoodBoyDigital**
##### Description of change
Removing items from a runner when its in the middle of running should no longer break, or have weird side effects

An alternative to PR #5970!

##### Pre-Merge Checklist

- [x] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

Once this builds will test the provided example...

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Unit tests?

**Comment by ivanpopelyshev** [comment]
you need to do `if (index !== -1)` anyway.

**Comment by GoodBoyDigital** [comment]
@bigtimebuddy , unit tests are an excellent idea.. Will add them today.
@ivanpopelyshev , adding should have no effect as it get pushed onto the top and does not alter the structure of the array? Not a fan of coping each time, what to keep this as fast as possible.

**Comment by ivanpopelyshev** [comment]
Its not each time, its when it was modified inside a cycle if there is more than one element.

**Comment by GoodBoyDigital** [comment]
unit test added 👍

**Comment by bigtimebuddy** [comment]
Closing in favor of #5975, confirmed with @GoodBoyDigital

**Pull request closed without merging**
