### PR TITLE
Fix polygon bounds

### LINKED ISSUE #3168: Graphics.lineTo padding bounds in some cases
https://codepen.io/staff0rd/pen/rrRdpj?editors=0010

image

Each of the above is a Graphics.drawCircle inside a container, with a sprite placed behind it equal to the bounds of the Container.  When including a line that touches any bound of the circle, the bounds are increased transparently.  I would expect all, except the last, to have the same bounds as the first and sixth(!) image.  For the last image, I would expect the width to be the width of the circle plus half the width of the line.

### PR DESCRIPTION
**Pull request by staff0rd**
Fixes #3168 

Before;
https://codepen.io/staff0rd/pen/rrRdpj?editors=0010
image

After;
https://codepen.io/staff0rd/pen/ZpPxvK?editors=0010
image

### CODE REVIEW

**Comment by staff0rd** [comment]
@ivanpopelyshev switched that theta calc out for arctan2, can you advise on what to do with the trig functions?  My math is pretty poor.

**Comment by GoodBoyDigital** [comment]
This looks great, @ivanpopelyshev are you able to advise on the changes you requested? This advanced math stuff is definitely something you are best at!

**Comment by ivanpopelyshev** [comment]
@GoodBoyDigital explain me how to change the other man's PR and I will remove trigonometric stuff

**Comment by staff0rd** [comment]
Closed in favour of #3234

**Pull request closed without merging**
