### PR TITLE
Fix spikes from wide strokes (#6924)

### LINKED ISSUE #6924: Spikes from strokes when a segment contains a neighboring point
When a path is drawn using `moveTo` and `lineTo` in `PIXI.Graphics`, and the path width is large enough that a segment contains a neighboring point, anomalous spikes can appear.

For instance: If you try to draw the path defined by the black circles and black segments, with a suitably large stroke width, you'll get the triangles & stroke shown here:

Note that a large spike emerges, facing in the opposite direction of the angle in the path. Here's a GIF:

bug

A live version of this demo is available [here](https://jsfiddle.net/Lzy2bohq/2/).

### In the wild

This problem occurs naturally if you shrink a path while keeping its stroke width fixed – for instance, in mapping applications. The spikes in the map below come from this problem:

Screen Shot 2020-10-06 at 5 49 11 PM

### Fix

I have a stop-gap fix implemented, which I will submit as a PR ASAP.

Thanks! ✌️

### PR DESCRIPTION
**Pull request by joshuahhh**
##### Description of change

This fixes #6924, the spikes-behind-wide-joins problem.

**Before:** (miter, bevel, round)
before

**After:** (miter, bevel, round)
after

It's not perfect. In particular, some regions are drawn twice, so strokes with alpha will be a bit mis-drawn. But that was the case before anyway. I believe some documentation already recommends using filters rather than stroke alpha in such cases.

(Note that some edges of the triangulation are incorrectly drawn red in the "round" examples above. This is an unrelated bug, which you can see occurs in both the "before" and "after" cases. If I can isolate it, I will report it as a separate issue.)

##### Pre-Merge Checklist
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

##### Thanks so much!

### CODE REVIEW

**Comment by JetLua** [comment]
Cool !  This PR also fixed #6903 . 

https://pixiplayground.com/#/edit/fxZUnCBQVQhwTi2ePohLv

**Comment by bigtimebuddy** [comment]
Thank you for this PR! Great explanation. Will review it. ping @SukantPal

**Review by SukantPal — APPROVED** [review]
Thanks for bringing these changes! In the future, I think we'll need to do work reducing the technical debt in this file.

**Comment by joshuahhh** [comment]
Thanks for the quick responses!

@bigtimebuddy, I recommend reviewing the change with whitespace ignored – it makes much more sense that way: https://github.com/pixijs/pixi.js/pull/6928/files?diff=unified&w=1.

@SukantPal, I agree that `buildNonNativeLine` & friends could use a major rework. (For instance, I honestly have no idea why `indexCount` needs to be tracked the way it is.)

**Review by bigtimebuddy — APPROVED** [review]

**Comment by bigtimebuddy** [comment]
Another good one @joshuahhh, you're on a roll! Thanks.

**Pull request merged**
