### PR TITLE
Renderer plugin to upload Textures & Graphics to the GPU

### PR DESCRIPTION
**Pull request by bigtimebuddy**
### Overview 

On low performing devices, uploading Textures or Graphics to the GPU can create some unwanted chug in performance. This PR provides a convenience plugin for WebGLRenderer to preload Textures and Graphics to the GPU. The load is spread across multiple update ticks to throttle the load. It improves the initial playback speed of WebGL content.

The first argument can be any PIXI.DisplayObject or a PIXI.Container. If a Container, upload will recursively find all Graphics and Texture children and upload.

```js
renderer.plugins.prepare.upload(container, function(){});
```

Alternatively you can manually add items for upload:
```js
renderer.plugins.prepare.add(graphic)
    .add(container)
    .add(baseTexture)
    .add(graphic)
    .upload(function(){
        console.log("Upload completed");
    });
```

### Example

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>Deprecation</title>
        <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    </head>
    <body>
        <canvas id="stage" width="600" height="600"></canvas>
        <script src="pixi.js/bin/pixi.js"></script>
        <script>
            var renderer = new PIXI.autoDetectRenderer(550, 400, {
                view: document.getElementById("stage"),
                backgroundColor: 0xffffff,
                antialias: true
            });
            var stage = new PIXI.Container();
            new PIXI.loaders.Loader()
                .add('mask', 'mask.png')
                .once('complete', function(loader, response){
                    var sprite = new PIXI.Sprite(response.mask.texture);
                    var square = new PIXI.Graphics()
                        .beginFill(0xFF0000)
                        .drawRect(0, 0, 100, 100);
                    square.x = 100;
                    square.y = 100;
                    square.skew.x = 0.4;
                    square.skew.y = 0.2;
                    stage.addChild(square, sprite);
                    renderer.plugins.prepare.upload(stage, function(){
                        console.log("Uploaded graphic and texture");
                        update();
                    });
                })
                .load();
                function update() {
                    renderer.render(stage);
                    requestAnimationFrame(update);
                }
        </script>
    </body>
</html>
```

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Btw, pixi-compressed-textures has the same method, but its not updated to v4 yet. I'd like some method that allows to hook into uploading process.

**Comment by ivanpopelyshev** [comment]
Also people asked me in private chats about continous uploading in realtime, and how to separate 1 big texture upload into several small

**Comment by bigtimebuddy** [comment]
Added the ability to register additional handlers for queueing and uploading.

```js
renderer.plugins.prepare.register(addHandler, uploadHandler);
```
Register takes two optional parameters **addHandler** and **uploadHandler**. Here are the function signatures for these handlers:

* **addHandler(item:any, queue:Array):Boolean** 
* **uploadHandler(renderer:WebGLRenderer, item:any):Boolean**

For instance, here are the built-in addHandler and uploadHandler for PIXI.Graphics:

```js
// Queue handler for Graphics
function findGraphics(item, queue) {
    if (item instanceof PIXI.Graphics) {
        queue.push(item);
        return true;
    }
    return false;
}

// Upload handler for PIXI.Graphics
function uploadGraphics(renderer, item) {
    if (item instanceof PIXI.Graphics) {
        renderer.plugins.graphics.updateGraphics(item);
        return true;
    }
    return false;
}

// Register Graphics for upload
renderer.plugins.prepare.register(findGraphics, uploadGraphics);
```

Also, added the ability to manually add items to upload instead of just searching through a container or display object:

```js
renderer.plugins.prepare.add(baseTexture);
renderer.plugins.prepare.upload(function(){
    console.log("Upload complete");
});
```

**Comment by GoodBoyDigital** [comment]
This is ace @bigtimebuddy 👍

**Comment by GoodBoyDigital** [comment]
👍

**Pull request merged**
