### PR TITLE
Replace url extension regex

### PR DESCRIPTION
**Pull request by englercj**
Fixes issue #3059.

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Doesn't browserify add polyfills for Node APIs? Seems like you could do this with `url` and `path` modules:

```js
const url = require('url');
const path = require('path');

const fullUrl = 'http://i.imgur.com/Mvv4bx8.jpg?querystring=true';
const result = path.extname(url.parse(fullUrl).pathname); // '.jpg'
```

**Comment by englercj** [comment]
yes, but the `url` polyfill is pretty big. I ended up removing it from resource-loader due to the size. Since we don't need full URL parsing I figured this would be a lighter solution.

**Comment by bigtimebuddy** [comment]
Makes sense, I'm cool with this then. Good improvement and nice unit-tests.

**Comment by GoodBoyDigital** [comment]
Nice man! 👍 for the tests too!

**Pull request merged**
