### PR TITLE
Upgrade Webdoc

### PR DESCRIPTION
**Pull request by bigtimebuddy**
Upgrade Webdoc and template to the latest versions.

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
@SukantPal I'm seeing a bunch of errors here.

```
{@assembly-mod resolve-assigned-members} failed to resolve these symbols: 
         useDeprecated.accessibility [to PIXI]
         useDeprecated.interaction [to PIXI]
         useDeprecated.prepare [to PIXI]
         useDeprecated.extract [to PIXI]
         useDeprecated.extras [to PIXI]
         useDeprecated.fromFrame [to TextureAny]
         useDeprecated.fromImage [to TextureAny]
         useDeprecated.mesh [to PIXI]
         useDeprecated.particles [to PIXI]
         useDeprecated.ticker [to PIXI]
         useDeprecated.loaders [to PIXI]
         useDeprecated.addPixiMiddleware [to PIXI.Loader]
         useDeprecated._renderWebGL [to PIXI.Container]
         useDeprecated.renderWebGL [to PIXI.DisplayObject]
         useDeprecated.renderAdvancedWebGL [to PIXI.Container]
         useDeprecated.loadSource [to BaseTextureAny]
         useDeprecated.fromCanvas [to TextureAny]
         useDeprecated.fromSVG [to TextureAny]
         useDeprecated.copy [to PIXI.Matrix]
         useDeprecated.setState [to PIXI.StateSystem]
         useDeprecated.fromVideo [to SpriteAny]
         useDeprecated.fromVideo [to TextureAny]
         useDeprecated.mixins [to PIXI.utils]
[DocParser]: Failed to parse doc for (@Unnamed){@packages/basis/src/Basis.ts<NaN, NaN>}
[DocParser]: Failed to parse doc for (@Unnamed){@packages/basis/src/Basis.ts<NaN, NaN>}
[DocParser]: Failed to parse doc for (@Unnamed){@packages/basis/src/Basis.ts<NaN, NaN>}
[TagParser]:{@} @typedef has not defined the {OriginalType}; defaulting to {any}
[TagParser]:{@} @typedef has not defined the {OriginalType}; defaulting to {any}
[DocParser]: Failed to parse doc for (@Unnamed){@packages/compressed-textures/src/loaders/CompressedTextureLoader.ts<NaN, NaN>}
[DocParser]: Failed to parse doc for (@Unnamed){@packages/compressed-textures/src/loaders/CompressedTextureLoader.ts<NaN, NaN>}
[DocParser]: Failed to parse doc for (@Unnamed){@packages/compressed-textures/src/resources/CompressedTextureResource.ts<NaN, NaN>}
[TagParser]:{@AbstractMultiResource.constructor} Parameter "options" does not have a "-" token preceeding description <Options to for Resource constructor>
undefined crashed findDoc in @webdoc/model
[undefined doesn't point to a doc]: undefined
pixi-webdoc-template took 8561ms to run!
@webdoc took 12237ms to run!
```

**Comment by SukantPal** [comment]
Nice! I think we need to add a `@static` tag to the following locations b/c of some webdoc problems:

* https://github.com/pixijs/pixi.js/blob/068e0af7f2851c51618b463b7fccc555e6ffb4b0/packages/graphics/src/Graphics.ts#L337
* https://github.com/pixijs/pixi.js/blob/068e0af7f2851c51618b463b7fccc555e6ffb4b0/packages/graphics-extras/src/drawChamferRect.ts#L8
* https://github.com/pixijs/pixi.js/blob/068e0af7f2851c51618b463b7fccc555e6ffb4b0/packages/graphics-extras/src/drawFilletRect.ts#L8
* https://github.com/pixijs/pixi.js/blob/068e0af7f2851c51618b463b7fccc555e6ffb4b0/packages/graphics-extras/src/drawRegularPolygon.ts#L8
* https://github.com/pixijs/pixi.js/blob/068e0af7f2851c51618b463b7fccc555e6ffb4b0/packages/graphics-extras/src/drawTorus.ts#L8

**Comment by SukantPal** [comment]
Good things:

* You see two lineStyle methods: http://pixijs.download/dev-webdoc-upgrade/docs/PIXI.Graphics.html#lineStyle
* The UPDATE_PRIORITY bug is fixed: http://pixijs.download/dev-webdoc-upgrade/docs/PIXI.html#UPDATE_PRIORITY

Bad things:

* PIXI.BitmapFont.from links are still partially missing. This is weird since the pixi-api website has them correct:
  * https://sukantpal.github.io/pixi-api/PIXI.BitmapFont.html#from
  * http://pixijs.download/dev-webdoc-upgrade/docs/PIXI.BitmapFont.html#from

**Comment by SukantPal** [comment]
@bigtimebuddy As for the errors, those existed before this PR. I can explain them here:

* useDeprecated links - Those, I believe, are expected. For example, you assign `PIXI.accessiblity`, even though `PIXI` is not a documented _symbol_. webdoc's symbol assembly has no way to resolve `accessibility` to `PIXI`, until _after_ the documents have been parsed. (Specifically, the `@namespace PIXI` document). Hence, the document assembler is successfully able to resolve `accessibility` to `PIXI` later on. This is why webdoc doesn't abort even after those errors.

https://github.com/pixijs/pixi.js/blob/068e0af7f2851c51618b463b7fccc555e6ffb4b0/bundles/pixi.js/src/useDeprecated.ts#L67

* Failed to parse doc: Those are because webdoc still doesn't support documenting TypeScript types:

```ts
/**
 * Webdoc will fail to understand what this is :P
 */
type Basis = { prop: string };
```

* Typedef has not defined original type - somewhere we've have a `@typedef Name` instead of `@typedef {object} Name`. I apologize for the lack of context (i.e. file name or line number).

* AbstractMultiResource constructor stuff, notice the lack of a `-` between `[options]` and `Options to...`:

https://github.com/pixijs/pixi.js/blob/068e0af7f2851c51618b463b7fccc555e6ffb4b0/packages/core/src/textures/resources/AbstractMultiResource.ts#L26

**Comment by bigtimebuddy** [comment]
@SukantPal would you mind making those fixes on this PR? I think you have a good idea where they need to be changed.

**Review by SukantPal — APPROVED** [review]
I'll update pixi-webdoc-template next weekend. I've been trying to fix all the type-checking errors in webdoc from Flow - except there are literally thousands (yes, 2200 on @webdoc/parser itself). That number is kind of inflated because some lines have up to 50 errors.

Once that's done, I'll get time again to fix pixi-webdoc-template.

**Comment by SukantPal** [comment]
So I republished webdoc 1.1.2 and then pixi-webdoc-template 1.1.3, and those should fix the `BitmapFont.from` links.

**Comment by SukantPal** [comment]
Well shoot, internal links to static method are broken. The fragment in the URL for static method contains the random ID generated for their docs, instead of their name. I guess we'll have to wait :(

**Comment by SukantPal** [comment]
But this will close #7001, because PIXI.extract has the correct URL: http://pixijs.download/dev-webdoc-upgrade/docs/PIXI.Extract.html

**Comment by SukantPal** [comment]
[webdoc 1.1.2 upgrade bugs](https://trello.com/c/B3lVJqsE/49-webdoc-112-upgrade-bugs)

**Comment by SukantPal** [comment]
I fixed the 3 issues in the Trello links in my last comment. @bigtimebuddy you can check http://pixijs.download/dev-webdoc-upgrade/docs/index.html and see for yourself!

**Comment by bigtimebuddy** [comment]
Much better!

**Comment by SukantPal** [comment]
@ivanpopelyshev Can you approve?

**Review by ivanpopelyshev — APPROVED** [review]

**Comment by bigtimebuddy** [comment]
Thanks for your help @SukantPal

**Pull request merged**
