### PR TITLE
Warn on null view

### LINKED ISSUE #3792: autoDetectRenderer should trigger an error if supplied view was not found
```javascript
var myView = document.getElementById('fooMap');
console.log(myView); //is null
var stage = new Container(),
renderer = autoDetectRenderer(window.innerWidth, window.innerHeight, {view: myView});
```

Using pixi.js 4.4.0.

I had a small typo failure (Id of my canvas was "barMap").
And wondered that nothing happends even dont get any errors.
It's a small thing but maybe it would be nice if this case triggers an error...

### PR DESCRIPTION
**Pull request by staff0rd**
Resolves #3792

### CODE REVIEW

**Comment by englercj** [comment]
Isn't not passing an explicit canvas a common use-case?

**Comment by ivanpopelyshev** [comment]
@englercj 
That case is "undefined".

**Comment by staff0rd** [comment]
@englercj right, this is an unexpected null check, not undefined which is expected.

**Comment by bigtimebuddy** [comment]
So null check is useful for checking if nothing is returned from getElementById or querySelector? I'm not convinced we should solve this problem, which is a user-error querying the DOM incorrectly.

**Comment by bigtimebuddy** [comment]
I'm going to close this for reasons mentioned above:
* `view` is always defaulted to `null` (not `undefined`), which invalidates the utility of this PR
* checking for a user's valid DOM query is outside scope of PIXI

**Pull request closed without merging**
