### PR TITLE
backport filter pool key

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
#3866 and other issues.

@Patrick-Hammond confirmed that we still have the problem, and I want to solve it radical way.

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Works like before:

https://jsfiddle.net/3kvazjw1/17/ - key = 'screen'
https://jsfiddle.net/3kvazjw1/20/ - key = '33554944' 

I dont have examples with a bug, but I'm sure that solution is correct - we store the result instead of recalculation.

**Comment by bigtimebuddy** [comment]
“I’m sure the solution is correct”, I don’t like any uncertainty here. Can you please try to dig up an erroring example so we can verify?

**Comment by ivanpopelyshev** [comment]
Its the same case as in https://github.com/pixijs/pixi.js/issues/4745 and in https://github.com/pixijs/pixi.js/pull/4579#issuecomment-378627432

Are you sure you want a third demo for it?

**Comment by ivanpopelyshev** [comment]
You are right. it was fun to reproduce it, we have one more case. Here it is: https://jsfiddle.net/3kvazjw1/21/

Chrome at 90% zoom gives us `0.8999999761581421`

```
var res = 0.8999999761581421;
console.log(1 / res * res);
```

shows `0.9999999999999999`

That's why minWidth and minHeight are less than expected, and the key is wrong.

**Comment by ivanpopelyshev** [comment]
@cursedcoder all according to [IEEE 754](https://en.wikipedia.org/wiki/IEEE_754)

**Pull request merged**
