### PR TITLE
Texture rotations

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
+ GroupD8 math, can be used for different purposes in tile-based games
+ texture rotations
+ fix bug in Sprite that causes changes in worldTransform every render

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
You can test it here : http://ivanpopelyshev.github.io/examples/index.html?s=demos&f=texture-rotate.js&title=Texture%20Rotate

**Comment by ivanpopelyshev** [comment]
[D8 on Wiki](https://en.wikipedia.org/wiki/Dihedral_group)

**Comment by ivanpopelyshev** [comment]
Im waiting for GBear to [test spine atlas](http://www.html5gamedevs.com/topic/19133-how-can-i-control-texturepack-with-rotation/?p=108917)

**Comment by GoodBoyDigital** [comment]
This is awesome @ivanpopelyshev! Once you have confirmation from GBear we can role it in. :+1:

**Comment by ivanpopelyshev** [comment]
Do you think its better to remove diamond-shaped UV-s from texture constructor? Its a side effect, and if someone really wants to use it, he can set "rotate" property manually.

```
if (rotate%2 != 0) { throw "attempt to use diamond-shaped UVs. If you are sure, set rotation manually"; }
```

**Comment by GoodBoyDigital** [comment]
sounds good to me!

**Comment by ivanpopelyshev** [comment]
Ok, I tested this with both texturePacker and spine packer, and I'm sure that both are working like intended.

I took 4 special sprites, and both packers rotated different sprites. Rows at top (spine) and bottom (tp) are identical:

Combined

**Comment by GoodBoyDigital** [comment]
Awesome man!

**Pull request merged**
