### PR TITLE
The RenderTexturePool should create renderTextures at resolution of 1

### PR DESCRIPTION
**Pull request by themoonrat**
Since internally it has already scaled the requested render texture size within getOptimalTexture
https://github.com/pixijs/pixi.js/issues/5954

- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Good one. 

I suggest to add `resolution: 1` here: https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/renderTexture/RenderTexturePool.js#L46

That's real bug, I forgot that we have default resolution.

**Comment by ivanpopelyshev** [comment]
I like it that you figured everything out. Now I know who to ask to test my changes in FilterSystem's,

**Comment by themoonrat** [comment]
I wouldn't go that far ;) But glad to work out the issue!

The 2 options are to have it as an option passed through as in this pr, or hardcode it at the point you suggest. The one I went for had less changes, but putting it as you suggest means it becomes more of a default setting that could still be overridden by the settings. But is a better default than what it does now.

Don't mind changing it over; you've already approved @bigtimebuddy so happy for me to change over the style?

**Comment by ivanpopelyshev** [comment]
Its hardcode because we need default implementation of that thing do not depend on resolution. Params are named `realWidth` and `realHeight` , that functions shouldn't create textures with res=2 by default!

**Comment by ivanpopelyshev** [comment]
Can you also remove resolution from that doc? I believe that not everything that can be passed should be documented here. `resolution` will work wrong way. 

Its better if I add doc for Type.

**Pull request merged**
