### PR TITLE
No longer skip the update transform pass on generating a texture.

### PR DESCRIPTION
**Pull request by themoonrat**
Fixes this function not working on the canvas renderer.
Before: https://jsfiddle.net/themoonrat/Lnkr5bkg/
After: https://jsfiddle.net/themoonrat/12u1nhnq/1/

### CODE REVIEW

**Comment by themoonrat** [comment]
Fixes: https://github.com/pixijs/pixi.js/issues/4317

**Comment by themoonrat** [comment]
I think I'm going down the same rabbit hole you're doing down Ivan; with this PR, if I look to extract pixels from the same container I get a different result every time. Doing an element.getBounds()  on the element before trying to go through the texture generation process fixes THAT issue. But maybe that's why skipTransforms was set to true in the first place.... to not effect the parent container.

Chicken. Meet egg.

**Comment by ivanpopelyshev** [comment]
One of my ideas was to export sprite that has special pivot or anchor to make the positioning much easier :)

**Comment by bigtimebuddy** [comment]
@themoonrat when I set `forceCanvas` to be `false`, the fiddle strobes. Is this just me?
 
https://jsfiddle.net/bigtimebuddy/tpmhe9tw/


generatetexture

**Comment by ivanpopelyshev** [comment]
It works for me. Whats going on?

**Comment by bigtimebuddy** [comment]
Update: MacOS on Chrome (Firefox and Safari are fine)

**Comment by ivanpopelyshev** [comment]
ok, which version of chrome it is? https://github.com/pixijs/pixi.js/issues/4342

**Comment by bigtimebuddy** [comment]
Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by ivanpopelyshev** [comment]
Exactly like in that ticket.

**Comment by bigtimebuddy** [comment]
Chatted with @GoodBoyDigital about this. He's going to look at this out after we get **next** in a better shape.

**Comment by bigtimebuddy** [comment]
Added this to "Future Work" so we'll remember to address. Closing for now.

**Comment by themoonrat** [comment]
@bigtimebuddy & @ivanpopelyshev - For what it's worth, I think I've solved this via changing  the generateTexture function to be from
`this.render(displayObject, renderTexture, false, tempMatrix, true);`
to
`this.render(displayObject, renderTexture, false, tempMatrix, !!displayObject.parent);`

This keeps current behaviour when containers have a parent, but solves the situation I had in canvas mode when I was trying to create a texture from a container that didn't have a parent.

Might be useful info!

**Comment by ivanpopelyshev** [comment]
Yes, its useful. 

I'll rewrite everything in it for v5, I already had a PR for that.

**Pull request closed without merging**
