### PR TITLE
Interaction fix

### PR DESCRIPTION
**Pull request by starakaj**
Some testing on android confirms that using 1 for `MOUSE_POINTER_ID` in InteractionManager is bad, since android can use 1 for touch identifiers. Using a constant 'MOUSE' fixes the issue.

### CODE REVIEW

**Comment by starakaj** [comment]
thanks to @fde31 for identifying the problem!

**Comment by andrewstart** [comment]
Could you add this to https://github.com/pixijs/pixi.js/pull/3375 instead, as we haven't merged that yet?

**Comment by starakaj** [comment]
Sure thing. I merged this branch and pushed to dev, did it work?

**Comment by andrewstart** [comment]
Yes it did! Thanks!

**Pull request closed without merging**
