### PR TITLE
Remove "same-side" guard.

### PR DESCRIPTION
**Pull request by SukantPal**
#6722 

My math failed me in achieving this :- https://github.com/pixijs/pixi.js/pull/6545#issuecomment-613144628. I think removing that code is okay for now - too complicated.

##### Description of change
Remove the code that prevents miter points from being on the opposite side.

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Could you find the old examples of graphics we were testing before to make sure we didn’t regress anything?

**Comment by bigtimebuddy** [comment]
I changed this to go to master, will probably push with the IE11 fix (whenever that arrives) as a v5.3.1 release.

**Comment by SukantPal** [comment]
@bigtimebuddy That's a regression. The original purpose of this code was to fix that. But, for some reason, it ended up being too sensitive and affected strokes when it shouldn't have.

**Comment by bigtimebuddy** [comment]
Is it fixable?

**Comment by SukantPal** [comment]
This would take a lot of effort. This dot-product based fix didn't work, although the math was provable. It means I missed something and it doesn't help we don't write the math on how stuff is calculated in the code. 🤷

**Pull request merged**
