### PR TITLE
Support for root-relative path in Spritesheet's image loading (#3715)

### PR DESCRIPTION
**Pull request by rasentry**
recreate PR to dev branch

### CODE REVIEW

**Comment by staff0rd** [comment]
Failed build unrelated to this PR, pending #3726 merge.

**Comment by rasentry** [comment]
Hi @staff0rd, yes please, cause I am no familar with tests.

json url | img  | img url |
--- | --- | ---
http://some.com/spritesheet.json | img.png | http://some.com/img.png
http://some.com/some/dir/spritesheet.json | img.png | http://some.com/some/dir/img.png
http://some.com/some/dir/spritesheet.json | ./img.png | http://some.com/some/dir/img.png
http://some.com/some/dir/spritesheet.json | ../img.png | http://some.com/some/img.png
/spritesheet.json | img.png | /img.png
/some/dir/spritesheet.json | img.png | /some/dir/img.png
/some/dir/spritesheet.json | ./img.png | /some/dir/img.png
/some/dir/spritesheet.json | ../img.png | /some/img.png

I think it will be enough.

**Comment by staff0rd** [comment]
Which spritesheet tool is exporting images like that?

**Comment by rasentry** [comment]
https://www.codeandweb.com/texturepacker
Trial exists.

19 февр. 2017 г. 3:14 пользователь "Stafford Williams" <
notifications@github.com> написал:

**Comment by staff0rd** [comment]
I added the tests - they pass once this PR is merged.  Thanks @rasentry!

**Comment by staff0rd** [comment]
Ping @bigtimebuddy

**Pull request merged**
