### PR TITLE
Fix anticlockwise sweep calculation

### PR DESCRIPTION
**Pull request by twhitbeck**
This changed from v3 to v4, we reverted back and it fixed arcs in our application.

### CODE REVIEW

**Comment by englercj** [comment]
Did you check the blame on this? This was an intentional change, what issue are you having?

https://github.com/pixijs/pixi.js/commit/1bcc6b4c2f51566bc438d7966d33f21f3a5aee21
https://github.com/pixijs/pixi.js/issues/2824

**Comment by twhitbeck** [comment]
The issue we were having was the arcs being drawn in mirror position to what we were expecting.

**Comment by twhitbeck** [comment]
Interestingly enough, we were also experiencing the issue described in #2824, but it has been resolved (even with this revert back to `* - 1`)

**Comment by twhitbeck** [comment]
After upgrading to v4, we saw this:

current

with this change, it cleared up and went back to:

reverted

**Comment by englercj** [comment]
So unless I am mistaken, this revert means that clockwise and anti-clockwise are actually the same because `(startAngle - endAngle) * -1 === (endAngle - startAngle)`. So something is seriously messed up.

**Comment by englercj** [comment]
Oops didn't mean to close.

**Comment by GoodBoyDigital** [comment]
good catch @twhitbeck! I guess we could simplify this line to basically be:

```const sweep = endAngle - startAngle;```

**Comment by twhitbeck** [comment]
@GoodBoyDigital ok I simplified the calculation.

**Comment by GoodBoyDigital** [comment]
Nice work team! 👍

**Pull request merged**
