### PR TITLE
Fixed texture from SVG

### PR DESCRIPTION
**Pull request by damianoc90**
##### Description of change
Fixed **PIXI.Texture.from()** and **PIXI.Sprite.from()** methods. In order to create a texture from url or  base64 we need to wait the src load.

##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included
- [ ] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
In terms of validating your change, could you create an example (jsfiddle/codepen/pixiplayground) where the old behavior is broken?

**Comment by damianoc90** [comment]
> In terms of validating your change, could you create an example (jsfiddle/codepen/pixiplayground) where the old behavior is broken?

Sure: https://www.pixiplayground.com/#/edit/94r8i41JvfB8oku204j85

**Comment by bigtimebuddy** [comment]
Thank you @damianoc90 

Could you fix this test? https://travis-ci.org/pixijs/pixi.js/builds/526649043#L1768-L1771

Looks like it should probably be async now.

**Comment by damianoc90** [comment]
The test was fine but the content of the file **svg-base64.txt** was an invalid svg, and the expect() on line 24 of the file SVGResource.js failed. This prevented done() method from being invoked.

**Comment by bigtimebuddy** [comment]
I moved this PR to master since we're going to do a patch release soon for 5.0.1 and will likely include this.

**Comment by damianoc90** [comment]
Thank you! :)

**Pull request merged**
