### PR TITLE
A system ticker to sit alongside the shared ticker.

### PR DESCRIPTION
**Pull request by themoonrat**
The shared ticker is tricky atm because you may want to pause the visuals on screen, but you don't want to effect the interactions or core system behaviour.
So having this system ticker separate means that you can now safely pause the shared ticker without worrying about it effecting that system behaviour

- [x] Tests and/or benchmarks are included
- [x] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Do you think it's worth re-thinking the names of `UPDATE_PRIORITY` now that you've separated out the systems stuff?

**Comment by ivanpopelyshev** [comment]
```
deprecation(v5, 'PIXI.ticker.shared has moved to PIXI.Ticker.shared');
```

fix it please.

**Comment by themoonrat** [comment]
@bigtimebuddy I think it's worth keeping as it is. The `system` ticker is still exposed, and devs can use it for their own system stuff that they wouldn't want to pause.

**Comment by ivanpopelyshev** [comment]
Its deprecation message for v4, in case somebody uses that ticker. We should change that statement too :)

**Comment by bigtimebuddy** [comment]
No it's a deprecation message for v5, we removed `PIXI.ticker` the namespace and moved the shared ticker to a static property on `PIXI.Ticker`

**Comment by ivanpopelyshev** [comment]
Oh, I thought we renamed it to `system` but its different. ok, never mind.

**Pull request merged**
