### PR TITLE
Convert canvas-display to TypeScript

### PR DESCRIPTION
**Pull request by SerG-Y**
##### Description of change
Converted canvas-display to TypeScript

##### Pre-Merge Checklist

- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
@SerG-Y could you look at why this is failing?

**Comment by SerG-Y** [comment]
> @SerG-Y could you look at why this is failing?

Will take a look

**Comment by SerG-Y** [comment]
@bigtimebuddy fixed

**Comment by bigtimebuddy** [comment]
Thanks for the quick turnaround @SerG-Y!

**Pull request merged**
