### PR TITLE
Fix for rounded rect #5540

### PR DESCRIPTION
**Pull request by GoodBoyDigital**
https://www.dropbox.com/s/zl8yf5te4vo50p3/Screenshot%202019-04-08%2020.01.42.png?dl=0

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Stroke alignment is still inverted for circles and rounded rects. Is this just the draw orientation?

**Comment by GoodBoyDigital** [comment]
https://www.dropbox.com/s/wss577uikh4t8lp/Screenshot%202019-04-08%2022.21.43.png?dl=0

fixed circle and rounded rect too 👍

**Comment by bigtimebuddy** [comment]
@GoodBoyDigital did you push?

**Comment by GoodBoyDigital** [comment]
do, try now.. :)

**Comment by bigtimebuddy** [comment]
There we go!

**Pull request merged**
