### PR TITLE
Fixed inner miter point adjustment when on opposite side of corner

### PR DESCRIPTION
**Pull request by SukantPal**
#6543

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Better, but seems like the square in the lower-left is busted now:

https://pixijs.io/examples/?v=fix-6543#/graphics/advanced.js
Screen Shot 2020-04-11 at 2 03 03 PM

https://pixijs.io/examples/?v=v5.2.1#/graphics/advanced.js
Screen Shot 2020-04-11 at 2 03 23 PM

**Comment by SukantPal** [comment]
@bigtimebuddy Was the square busted before this PR too? Or is it because of this change?

**Comment by bigtimebuddy** [comment]
Looks like because of this change.

**Comment by bigtimebuddy** [comment]
@SukantPal any ideas?

**Comment by SukantPal** [comment]
@bigtimebuddy I know where the problem is coming from. The math is incorrect. I’ll get this sorted tomorrow. It is because of the code where I prevent the inner miter point from being on the opposite side of the corner.

**Comment by SukantPal** [comment]
@bigtimebuddy I also want to present a formal (mathematical) proof that my fix will work and why.

**Comment by ivanpopelyshev** [comment]
Proofs are good things, but please do make refs , where those formulas exist in other renderers. 

Nothing bad in peeking at other people stuff to check for possible mistakes and places where you are actually smarter ;)

**Comment by SukantPal** [comment]
@ivanpopelyshev I'll try.

**Comment by SukantPal** [comment]
@bigtimebuddy Why are the tests failing in CI? Something related to `isMobile` & passing on my machine.

**Comment by SukantPal** [comment]
Okay, this bug was related to the code that "prevented the inner miter point from being on the opposite side of the corner". By doing so, you eliminate a rare class of bugs that arise at high line widths. This animation will show you what happens when the width gets to large eventually: https://jsfiddle.net/ShukantPal/fhkd2r85/. Specifically, focus on the "inner" point of the joint. It rapidly rises up, as you would expect, however, it overshoots the first & last points, looking like this:

Screen Shot 2020-04-13 at 6 59 55 PM

Let me take an example in a Cartesian plane (no y-inversion): connect the points (0, 0), (10, 100), (20, 0) with a variable line width.

* At width = 10, you will find that the inner edges will intersect at (10, 0).

* Increasing the width from 10 will result the inner edges meeting at a y-value below 0. This means on the opposite side of the joint (the joint is (10, 100) on +ve y side).

I have setup a guide showing the math behind this here: https://www.desmos.com/calculator/gtyqjkoad6

**Comment by SukantPal** [comment]
To prevent the inner miter joint from going onto the other side, we can take check for "same-sidedness" of the it and the joint (p1) w.r.t the line joining p0 & p2. This guide explains how that works:

https://www.desmos.com/calculator/zwdrci6rwh

**Pull request merged**
