### PR TITLE
Supports resolutions less than 1

### PR DESCRIPTION
**Pull request by themoonrat**
Resolutions of 0.5 / 0.75 can lead to floating point widths and heights. This PR ensures that when textures are created, `ceil` is used to ensure that everything fits in. When rendering, it uses `floor` to ensure it's not trying to render an area that doesn't exist (which IE really hates)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Is it possible to add tests for this? Want to make sure we harden this behavior. Otherwise awesome fix.

**Comment by GoodBoyDigital** [comment]
nice! awaiting secret agent x-files tests :D

**Comment by ivanpopelyshev** [comment]
For floor add `+1e-4` for ceil add `-1e-4` and it should be fine.

**Comment by ivanpopelyshev** [comment]
Maybe put those floor ceil in our own functions in math. @bigtimebuddy I need your decision whether to put `1e-4` everywhere or move it to function.

**Comment by bigtimebuddy** [comment]
Just inline those and we can do cleanup later since there are more places that could utilize the safe floor and ceil methods. Rather not pile on.

**Comment by GoodBoyDigital** [comment]
this looks cool. Will solve the case for most users and is better than we have now. @ivanpopelyshev sounds like you have some good thoughts on how to handle the floating point precision, you cool to do a separate PR? 

Ta!

**Comment by bigtimebuddy** [comment]
Thanks @themoonrat

**Comment by Megabyteceer** [comment]
When scale of sprite set to 100, Math.floor causes random resize of sprite for 0 to 100 pexels related on current render resolution.

**Pull request merged**
