### PR TITLE
Fix for "Cannot read property 'indexOf' of null #2882"

### PR DESCRIPTION
**Pull request by PatrickGormley**
removeChild function checks if there is anything to remove first. #2882

### CODE REVIEW

**Comment by GoodBoyDigital** [comment]
Hi @PatrickGormley children should always be there?

**Comment by englercj** [comment]
The only time you should get this error is if you are trying to remove a child from a previously destroyed container, which isn't something that should happen unless you have an error in your code somewhere.

In fact, in the latest `dev` we never even set `.children` to null at all. Not even on destroy.

**Comment by PatrickGormley** [comment]
Yep, looking though the code and the destroy() functions again I came to the same realization. Guessing the bug (#2882) should be closed out then?

**Comment by englercj** [comment]
Closed!

**Pull request closed without merging**
