### PR TITLE
Fixes depthTexture to work properly

### PR DESCRIPTION
**Pull request by Dairnon**
This is the start of  enabling depthTexture support.

This fixes the depthTexture from not being written to at all, and adds a depthResource that is used to fix the internalType needed for webgl2.0

This is a first pass at it, to get it working fully in webgl2.0. Then Ill move to 1.0 + extensions.

The depth resource is also something I'd like to instead be a option we can pass into either Resource itself as a property (internalFormat) or as a property for baseTexture. For now tho it'll have to do.

##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included
- [x] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [ ] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by englercj** [comment]
You can rename the branch with `git branch -m depthResource dev-depth-resource` but pretty sure you will then need to open a new PR with the new name.

**Comment by englercj** [comment]
Tests would be awesome as well.

**Comment by Dairnon** [comment]
@englercj Ah okay, should I just delete this pr and redo it to fix the name? 

As for the tests, I'm familar with providing example demos but am unsure about the standard of how we do tests here. 

I extended BufferResource which appeared to have a test already, so I wasn't sure if I needed to create another for that DepthResource specifically.

**Comment by bigtimebuddy** [comment]
I wouldn't sweat the branch renaming. Not a big deal but in, general, using kabab lower case is preferred.

**Comment by Dairnon** [comment]
Ill work out a webgl1.0 extension version soon too

I just wanted to make sure we got this in 

I am curious, anyone have any ideas on how we should manage the different shader formats between 1 and 2.0? 

How should we go back backwards compatibility between 1.0 + extensions and 2.0 for shaders

**Comment by ivanpopelyshev** [comment]
no need to rename it

**Pull request merged**
