### PR TITLE
small fixes in the documentation

### PR DESCRIPTION
**Pull request by CodeRect**
Just fixed a few issues in the documentation (also see #2953). Thank you for this great library.

### CODE REVIEW

**Comment by englercj** [comment]
https://github.com/pixijs/pixi.js/commit/c499055af4c9573030c6ed2bf77c2a63b5bf2a45

**Comment by CodeRect** [comment]
Thank you for fixing these. You unfortunately missed a few, for example:

```
let baseRenderTexture = new PIXI.BaserenderTexture(100, 100);
```

**Comment by englercj** [comment]
Oops! Should be good after  eb992e323d6f17894e8163ea77dacb3499b7e6dc.

**Comment by CodeRect** [comment]
Thanks!

**Pull request closed without merging**
