### PR TITLE
Mask graphics holes in CanvasRenderer

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
Look at polygon direction, draw a hole to counter it.

### Mask
Bad: https://www.pixiplayground.com/#/edit/W2Dm4fZVm9ygrRYqiVDXJ
Fixed: https://www.pixiplayground.com/#/edit/X8tnNzuRIXgPJBBiJTi7x

### Graphics
Bad: https://www.pixiplayground.com/#/edit/GfZudGKNnnrFe~xK8iJ7D
Fixed: https://www.pixiplayground.com/#/edit/sRbmePH_D70ofcyRlXMbA

As you can see, strokes around holes are not consistent in canvas/webgl, I don't know what to do about that yet.

Build: http://pixijs.download/dev-canvas-mask-holes/pixi.js

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
#4177
#4183

**Comment by bigtimebuddy** [comment]
Hero!!!

**Comment by ivanpopelyshev** [comment]
I think we should port this to GraphicsRenderer too. Working on it.

**Comment by ivanpopelyshev** [comment]
Done, please review again.

**Comment by ivanpopelyshev** [comment]
Lets refactor it in v5, I dont want to add complexity in this PR

**Comment by bigtimebuddy** [comment]
@ivanpopelyshev awesome work. Do you think we can port this to v5?

**Pull request merged**
