### PR TITLE
fix Video type wrongly set

### PR DESCRIPTION
**Pull request by gooderist**
Addresses issue #4882 by throwing away the query string (everything after and including the '?')

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Thanks for this, would you mind adding a simple unit test to cover the query string URL?

**Comment by gooderist** [comment]
Of course! However, I don't see an existing test file for VideoBaseTextures. How should I proceed? Add a new file or add the test to Texture.js or somewhere else?

**Comment by themoonrat** [comment]
I would create a new file. It's good to keep all tests for a single class in their own file

**Comment by gooderist** [comment]
Hello, new file and unit test for VideoBaseTexture added. Let me know if it looks off.

**Comment by themoonrat** [comment]
lgtm :)
I'd just add a test a 'normal' scenario alongside a test for your bugfix. What if just a normal .ogv url was loaded for example? This will check that (1) the type shows ogv, and doesn't just work for mp4, and (2) checks that your bugfix doesn't negatively effect regular urls.

**Comment by gooderist** [comment]
@themoonrat thanks for the feedback! I think I got it this time.

**Pull request merged**
