### PR TITLE
Added support for structs in shader uniforms

### PR DESCRIPTION
**Pull request by jnsmalm**
##### Description of change

With this change we can set structs in shader uniforms the same way we can set it using WebGL directly.

```
shader.uniforms["material.color"] = [1, 1, 1];
shader.uniforms["lights[1].position"] = [0, 1, 0];
```

##### Pre-Merge Checklist

- [ x] Tests and/or benchmarks are included
- [ ] Documentation is changed or added
- [x ] Lint process passed (`npm run lint`)
- [x ] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by GoodBoyDigital** [comment]
this is really cool!

**Comment by jnsmalm** [comment]
:) What do you other guys think, could we add this to next pixi version?

**Comment by bigtimebuddy** [comment]
I have no problem with this feature. There are some conflicts because we just finished the TypeScript convert of core, and @GoodBoyDigital has a PR right now that will also conflict. If you can have a little patience, we can work on getting this in.

**Comment by ivanpopelyshev** [comment]
Yep, lets merge it after @GoodBoyDigital PR.

**Comment by jnsmalm** [comment]
Cool, should I try to resolve these conflicts or should I just leave it as is?

**Comment by bigtimebuddy** [comment]
@jnsmalm wait until #6369 is merged and then if you could resolve conflicts after, that'd be awesome.

**Comment by jnsmalm** [comment]
I resolved the conflicts, so it should be ready now :)

**Comment by bigtimebuddy** [comment]
Thank you @jnsmalm :tada:

**Pull request merged**
