### PR TITLE
the "$>" chars are confusing

### PR DESCRIPTION
**Pull request by rap2hpoutre**

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
@rap2hpoutre There are several other occurrences of this in the README: see: https://github.com/pixijs/pixi.js#how-to-build

Could you fix those as well?

**Comment by rap2hpoutre** [comment]
Of course!

**Comment by rap2hpoutre** [comment]
@bigtimebuddy Done (these changes would "repair" the syntax highlighting too).

**Comment by bigtimebuddy** [comment]
Terrific. Good work @rap2hpoutre, thanks.

**Comment by englercj** [comment]
Sorry about that, it was supposed to be the CLI prompt but I can definitely see that being confusing :P

**Pull request merged**
