### PR TITLE
Update for IOS Voiceover,  Android Talkback and Kindle VoiceView

### PR DESCRIPTION
**Pull request by scottmcdonnell**
Update for accessibility to address issue #2683
There is a [demo here](http://scottmcdonnell.github.io/pixi-accessibility/) 

This always adds the divs on mobiles that do not support focus events in accessibility mode.
Additionally it has an updateTabOrders to correctly order the divs for tabbing.

This AccessibilityManager has been tested with PIXI v4 and PIXI v3 across:
- IOS VoiceOver for IOS
- Android TalkBack
- Kindle VoiceView

### CODE REVIEW

**Comment by GoodBoyDigital** [comment]
Thanks for this PR @scottmcdonnell ! 
Nice to see you got it working on all 3 devices 👍 
One thing to quickly check - the way the PR is set up, does that mean that the accessibility layer will always be there on android devices?

**Comment by scottmcdonnell** [comment]
Yes, we tried a load of different ways and for android only "always on" worked for us as there is no way we could find of detecting the screen reader enabled. 

The alternative I would consider in the future would be to roll all HUD buttons in plain html over the pixi layer so it's fully accessible without any potential performance hit of post render action every frame.

**Comment by JiDW** [comment]
This will however continue to break on WebGL views that does not support DOM, like CocoonJS.

https://github.com/pixijs/pixi.js/issues/2660

Is it possible to add a way to disable to accessibility manager at least please, if you can't detect when it's needed or not ?

**Comment by scottmcdonnell** [comment]
I also think it would be a good idea to be able to switch the accessibility off, that would work for Cacoonjs or your own html HUD.  I didn't add this to this PR to keep it focused but +1 for adding to pixi.js

**Comment by englercj** [comment]
Can you rebase this onto the latest `dev` branch please @scottmcdonnell? Thanks!

**Comment by scottmcdonnell** [comment]
Sorry was busy on another project, rebased now I to latest dev.

**Comment by GoodBoyDigital** [comment]
Closing this for now. Rolling a new Accessibility manager for v5 👍

**Pull request closed without merging**
