### PR TITLE
Remove needless `Number()` call.

### PR DESCRIPTION
**Pull request by finscn**
Call Number() once when create ` factor`  that better than call `Number()` multi times in for-loop.

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Why is there a "Number" anyway?

**Comment by staff0rd** [comment]
nulls?

**Comment by ivanpopelyshev** [comment]
But "null-null===0", so its obsolete here

**Comment by ivanpopelyshev** [comment]
Oh, wait, its "undefined - undefined" !!! But then, what about first thing? x1 - x0?

**Comment by englercj** [comment]
Looks good, but please make the PR to the `dev` branch; not `master`.

**Pull request closed without merging**
