### PR TITLE
Converts settings to TypeScript

### PR DESCRIPTION
**Pull request by Zyie**
##### Description of change

Opening another draft PR to let people know what is being worked on.

So far I have tried to use namespaces for settings however this resulted in many setting objects instead of one large one, not sure why.

For now I have gone with one interface that has optional parameters for the options defined outside the initial settings file.

Let me know if you guys have a better solution to try out. I dont think the current method is bad just not great.

##### Pre-Merge Checklist

- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by Zyie** [comment]
> I'm not in love with the name `PixiSettings`, maybe simply `Settings`

I've updated the name

**Comment by ivanpopelyshev** [comment]
@bigtimebuddy @Zyie What about `IPixiSettings` and `IRenderOptions` ? Also , `RenderOptions` in core will have more settings than that, and they will be optional. What about `IBaseRenderOptions` ?

**Comment by Zyie** [comment]
> What about `IPixiSettings` and `IRenderOptions` ?'

Would it be a good idea to have a naming convention for interfaces. So all begin with I? That way we dont have a mashup of different names. For example we have IPoint, IDestoryOptions, but DecomposedDataUri, Settings, RenderOptions

> For example, it doesnt have `resolution`.

Ah yes i didnt realise that got added dynamically in `AbstractRenderer`.

**Comment by ivanpopelyshev** [comment]
I think `DecomposedDataUri` is the only one without `I`

**Comment by bigtimebuddy** [comment]
I like using `I` as a prefix for interfaces.

**Comment by Zyie** [comment]
Ok I've updated the names to use the prefix. I'll let @ivanpopelyshev fix whatever needs to be fixed in his core pr

**Pull request merged**
