### PR TITLE
fix filterManager destroy

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
Just looked inside, saw a bug. Lets test it!

#4418 #4420

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
ok, fixed. That was really stupid mistake I've made in #4285

**Comment by cursedcoder** [comment]
+1, also encounter this on 4.6.0

**Comment by cursedcoder** [comment]
@bigtimebuddy can we convert this codepen into test?

**Comment by bigtimebuddy** [comment]
Yeah, we should make a unit test for this. Welcome a PR for that!

**Comment by cursedcoder** [comment]
@bigtimebuddy #4431

**Pull request merged**
