### PR TITLE
simplify transform classes. #4062

### PR DESCRIPTION
**Pull request by mreinstein**

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
@englercj haven't you already worked on this convergence for v5? I think I recall a conversation awhile back about it.

**Comment by ivanpopelyshev** [comment]
I'll review it a bit later. I suggest we REMOVE non-static transform completely.

**Comment by mreinstein** [comment]
thanks @ivanpopelyshev!

I intentionally chose the more conservative refactor here. I was worried that breaking the API would make this PR less appealing. The current strategy manages to cut the total lines of code in the transform classes in half, without breaking any existing behavior.

**Comment by englercj** [comment]
I have changed a bit of this in v5, there is only 1 transform class and it always caches by exposing properties for each value rather than observable points: https://github.com/pixijs/pixi.js/blob/455c059e8d155c1d9a05fc2ece2c02b3bdf8bf84/plugins/transform/src/Transform.js

I'm not done with it yet since I've only spent a little time with it.

**Comment by englercj** [comment]
Going to close this for now, since we are unifying this a bit differently in v5.

**Pull request closed without merging**
