### PR TITLE
Dev experimental geometry

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
epic merge

### CODE REVIEW

**Comment by englercj** [comment]
Can you just rebase instead of this? And we can update the other branch separately?

**Comment by ivanpopelyshev** [comment]
@englercj @GoodBoyDigital what do you mean rebase?

**Comment by ivanpopelyshev** [comment]
It meant to be this way, its one big mess. I'll cherry-pick features that will go to "dev". That branch isnt supposed to be merged into dev.

**Comment by englercj** [comment]
I'm not sure I follow, if you have changes that ned to be merged to dev. Just rebase your branch on dev and PR that? Or cherry pick your changes into a new branch off of dev and PR that.

**Comment by ivanpopelyshev** [comment]
@englercj they are all experimental. For example, there was #2465 for a month and it wasnt discussed enough, it was not merged, now i have to rebase it on new dev. Other features are even more complex, and I'm gonna add pixi-flip to it today. If you are ready to review, then fine, I'll rebase it.

**Comment by ivanpopelyshev** [comment]
@englercj pixijs:dev-experimental-geometry from ivanpopelyshev:dev-experimental-geometry

I dont follow it either, I just want a branch for myself and I dont have access to the repo.

**Comment by englercj** [comment]
You don't need access to the repo to make personal branches. What is the benefit of merging this PR?

**Comment by ivanpopelyshev** [comment]
I need people to actually see those new features in pixi-examples. So that branch is half-official, its extension of pixi-flip. Of course I can do it in my repo. I'm not good at these kind of things, can you talk to @GoodBoyDigital and develop a protocol how we do that?

**Comment by englercj** [comment]
Not sure I understand what putting the branch in this repo has to do with pixi examples?

Why not have a branch of examples that you can use to show off the new feature.

The protocol should be like any other new feature, develop it in your repo and PR it when you feel it should be moved into the main repository line. Having personal branches in the main repo doesn't make much sense.

**Pull request closed without merging**
