### PR TITLE
Converts git+https dependencies to releases, fixes pixi-gl-core usage

### PR DESCRIPTION
**Pull request by bigtimebuddy**
### Overview

* Updates package.json dependencies to pull from NPM releases instead of git+https.
* Updated **pixi-gl-core** implementation to match the latest publish release.

### CODE REVIEW

**Comment by themoonrat** [comment]
For our libs we copied the jaguarjs-jsdoc format that you guys used. When we use ^0.0.1 rather than the git+https, we found it wasn't actually using the latest version. That means you get poor css styling in places, such as when linking to other declared types.

Here's a screenshot of one of our jsdocced classes using ^0.0.1 and notice the link for 'eb' at the bottom -  https://s33.postimg.org/r3lkbaojz/jsdoc.jpg

**Comment by englercj** [comment]
Yeah the jsdoc theme hasn't been updated on npm for a while, I used the repo there on purpose.

Otherwise, :+1:

**Comment by themoonrat** [comment]
Try

"jaguarjs-jsdoc-patched-2": "^0.0.3"
https://www.npmjs.com/package/jaguarjs-jsdoc-patched-2

It's been updated over the past 4 months, looks essentially the same as the git+https version without the 0.0.1 issues, but has a couple of sensible tweaks imo, including listing overriden methods for a class above inherited ones.

**Comment by bigtimebuddy** [comment]
Ugh, okay. Since it's a dev dependency, I decided to revert the jaguarjs-jsdoc change. Has anyone asked the owner of that project to publish a new release to NPM? Seems trivial and we could actually lock down a version.

**Comment by bigtimebuddy** [comment]
Update: I emailed the NPM publisher of the jaguarjs-jsdoc project and ask if he would publish a new release. We'll see how that goes. In the meantime, this PR should be good to go.

**Comment by GoodBoyDigital** [comment]
nice one @bigtimebuddy 👍

**Pull request merged**
