### PR TITLE
Fix text linePositionY

### LINKED ISSUE #7344: Text's lineHeight implementation does not match HTML
Text lines are current aligned to the top. When for instance the `lineHeight` is bigger than the `fontSize` the gap [gets added to the bottom](https://www.pixiplayground.com/#/edit/AVy4yl6EFkC5H9N4TYMAh).

This is not how HTML or graphics editors work.

Rubén from the [Slack channel](https://pixijs.slack.com/archives/C0XS4MVU0/p1616771712076200?thread_ts=1616746168.071900&cid=C0XS4MVU0) thinks this is due to this code in [Text.ts](https://github.com/pixijs/pixi.js/blob/7b79a9d14edaeac4476437dac19472ecdee683c8/packages/text/src/Text.ts):

`linePositionY = ((style.strokeThickness / 2) + (i * lineHeight)) + fontProperties.ascent;`

Maybe not everyone is building a graphics editor like me in PIXI, but I don't see why PIXI shouldn't be as close as possible to how HTML works.

### PR DESCRIPTION
**Pull request by andrej-ilic**
##### Description of change

Fixes #7344

This way the text lines are not aligned to the top. The result looks similar to the HTML example and it does not seem to break when `lineHeight` is set to 0.

##### Pre-Merge Checklist

- [ ] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Could you please remove the package-lock changes?

**Comment by andrej-ilic** [comment]
Done.

**Comment by bigtimebuddy** [comment]
Thanks @andrej-ilic, this will take a bit to verify.

**Review by bigtimebuddy — APPROVED** [review]
This works for me, I didn't see anything unexpected fiddling with the lineHeight.

**Broken: (dev)**
https://jsfiddle.net/bigtimebuddy/t10wnyvf/

**Fixed: (this PR)**
https://jsfiddle.net/bigtimebuddy/7ygvL69p/

**Build:**
https://pixijs.download/dev-pr-7386/pixi.min.js

**Comment by bigtimebuddy** [comment]
@themoonrat could you let us know what you think about this Text change?

**Review by SukantPal — APPROVED** [review]

**Comment by AShenawy** [comment]
I understand that this is an issue because it's not like how HTML handles line height. But as per typography rules and definitions (see [here](https://material.io/design/typography/understanding-typography.html#readability)):

> Line height, also known as leading, controls the amount of space between baselines in a block of text. A text’s line height is proportional to its type size.

This means that the current way Pixi handles it is the proper way as far as typography is concerned.

**Comment by bigtimebuddy** [comment]
I agree @AShenawy that vertically centering text using line-height isn't what it's intended for, however, currently with Pixi Text objects there's no way for devs to know where the first baseline is located. It's basically a guess. That's not the case for HTML text and knowing this information can be pretty important for doing layout. This doesn't change the overall approach for line-height _except_ for the first line. 

Here's an example that illustrates the issue. Look add the line and how it stays relative to the text baseline.

**This PR**
https://jsfiddle.net/bigtimebuddy/qp7ejrb6/

**Current Behavior**
https://jsfiddle.net/bigtimebuddy/4wvoje13/

**Review by themoonrat — CHANGES_REQUESTED** [review]
Messaged @bigtimebuddy on Slack with my concerns over this; that it _will_ effect lots of already made content out there. It's a visually breaking change.

Also an issue of text getting cut off with lower value line heights which didn't occur before https://jsfiddle.net/e8r21yqg/ to https://jsfiddle.net/fkjvqp3m/

**Comment by andrej-ilic** [comment]
Yes, I agree. It may be bad to affect so many projects.
The last commit should fix the text getting cut off issue, in case you want to merge this PR.

**Comment by andrej-ilic** [comment]
I made it opt-in.

I the 'Documentation is changed or added' check to the PR.

**Comment by bigtimebuddy** [comment]
@nuthinking, is this good for you?

**Review by bigtimebuddy — APPROVED** [review]
Updated example with switch. Seems to work great:
https://jsfiddle.net/bigtimebuddy/7ygvL69p/

Documentation preview here:
https://pixijs.download/dev-pr-7386/docs/PIXI.Text.html#nextLineHeightBehavior

**Comment by nuthinking** [comment]
@bigtimebuddy yes, looks great. Thanks! 🙌

**Review by themoonrat — APPROVED** [review]

**Pull request merged**
