### PR TITLE
Alternative for text positioning

### PR DESCRIPTION
**Pull request by SebastianNette**
No more dom required to calculate the font size.

### CODE REVIEW

**Comment by tobireif** [comment]
Hi all!

Regarding
https://github.com/GoodBoyDigital/pixi.js/issues/1021
and
https://github.com/GoodBoyDigital/pixi.js/pull/1062
and this page here:

Does text in Pixi JS now get rendered in exactly the same position across browsers and OSs? (Including Mac-Firefox, Windows-Firefox, Mac-Chrome, Windows-Chrome, Mac-Safari, iPhone-Safari, Internet Explorer, and Android.)

Does it also work with atypical fonts? (where eg the "M" has unnormal proportions)

Is the overall performance of the fix OK?

That would be great :)

Tobi

**Comment by tobireif** [comment]
P.S.

Perhaps someone know who to resolve this line?
https://github.com/GoodBoyDigital/pixi.js/blob/88661f02228f03e1698bbe2e16f4fc47a1948e71/src/pixi/text/Text.js#L440
```
//TODO might need a tweak. kind of a temp fix!
properties.descent += 6;
```

**Comment by EricLesch** [comment]
Hi,

The short answer is that I don't know about performance/consistency of the current solution because I ended up forking it and doing it a different way in my project.

However, I've just downloaded the latest PIXI.js code from the master branch and pushed up the old font testbed that I was using. I didn't take the time to make the test lines line up with where the text should be in the latest version but you can get an idea.....

It's at http://ericlesch.com.

I am not aware of anyone profiling the performance in the related discussion so that is unknown as well.

I agree that "+=6" looks suspect.

A good webfont to check for atypical sizing would be Oswald since it has an abnormally high ascent and an abnormally short descent.

I hope that is somewhat helpful.

Thanks,
Eric

Founder
Makemake.io

P.S. Your website is rad. I like people doing creative outside-of-the-box things on the web.

**Comment by tobireif** [comment]
Hi Eric

> I ended up forking it and doing it a different way in my project.

If you solved it in a general way for you project / in your fork, perhaps you could create a pull request?

(Regarding performance: Pixi is using a cache for the font metrics - if the lib user can fill it right way then there's no performance hit later.)

**Comment by EricLesch** [comment]
As per the previous discussion here and in another thread, my solution was deemed too computationally expensive. I profiled it and thought it was ok but I think it depends on your use case.

In any case I decided not to argue about it anymore.

Thanks,
Eric

Founder
Makemake.io

**Comment by tobireif** [comment]
Thanks a lot for your reply!

Perhaps Pixi could offer both options - no arguing necessary :)

On http://ericlesch.com/ you currently have a page which tests how precise Pixi positions text, if I understood you correctly. Perhaps you could check whether the latest Pixi (dev branch) positions text correctly? (across browsers/OSs)

Then perhaps Pixi could offer two options: One solution which is 100% exact and might incur a small performance hit, and an approximate positioning option (eg the current code) which might be faster. (The latter/current option could be the default.)

If you found a solution which ensures that Pixi positions text 100% correctly across OSs, then that's very valuable (especially when *big* words are rendered and need to line up with each other or with graphics). I hope this solution can somehow find it's way (back) into Pixi.

Users worried about the small performance hit should have/get the option to ask Pixi to collect the font metrics for a list of fonts right away (after the fonts got loaded) - so that there's no perf hit caused by font measuring later during eg high-speed animations. (I'd use this btw because I do have high-speed animations in my current web app.)

To all: Would that leave any major issues unresolved?

I firmly believe that browsers should take care of exact text positioning (and fully compensate the differences between OSs), but they don't. So the burden is on poor Pixi's shoulders ...

**Comment by GoodBoyDigital** [comment]
Hi @EricLesch 
Not too sure how we got to that conclusion :/ Happy to get your code back in as this issue has been lingering for awhile!

**Comment by tobireif** [comment]
But https://github.com/EricLesch/pixi.js/commit/7c269137ceb8471dde25378d116c8dc3f7cacd31 seems to not measure descent?

Perhaps somehow the good stuff from the above could be merged with https://github.com/motiz88/pixi.js/commit/397916d4548c02c6243d61951271f6e235818505 ? (the commit linked on https://github.com/GoodBoyDigital/pixi.js/commit/fa5ba164055d3b3ee17c8490831e7031f5b9357e , which uses https://github.com/motiz88/canvas-text-metrics-polyfill which has a nice test page https://rawgit.com/motiz88/canvas-text-metrics-polyfill/master/tests/visual-test.html .)

(Neither seems to check an uppercase character plus http://en.wikipedia.org/wiki/Acute_accent , I think that got introduced later in Pixi history.)

**Comment by EricLesch** [comment]
Hi. Sorry for the super slow response. My implementation seems to fail in certain situations and render the text in completely the wrong place so its cut off. Unfortunately, it seems to be random behavior as it only happens occasionally on some devices (race condition?). Unfortunately it always works on my machine. When I get it working consistently on all devices I'll come back to this and see what we can figure out.

**Comment by logan503k** [comment]
25 февр. 2015 г. 10:56 пользователь "Eric Lesch" <notifications@github.com>
написал:
>
> Hi. Sorry for the super slow response. My implementation seems to fail in
certain situations and render the text in completely the wrong place so its
cut off. Unfortunately, it seems to be random behavior as it only happens
occasionally on some devices (race condition?). Unfortunately it always
works on my machine. When I get it working consistently on all devices I'll
come back to this and see what we can figure out.

**Comment by photonstorm** [comment]
A more concrete method for measuring text *height* would be to shove it in a DOM element and then do a `getBoundingClientRect` on it. This will give you an accurate height without having to scan any pixels or worry about capitals, etc. However the *width* will be wrong, because DOM kerning is sufficiently more advanced than Canvas. Wrong by what percentage I don't know, but maybe tolerable.

**Comment by englercj** [comment]
@photonstorm Unfortunately we are purposefully not using DOM elements to support environments due some cocoonjs/ejecta issues that don't implement DOM elements besides canvas :(

(At least I'm pretty sure that was why we switched).

**Comment by tobireif** [comment]
> When I get it working consistently on all devices I'll come back to
> this and see what we can figure out.

Thanks for working on this!

It will be awesome when this will be resolved in Pixi.

Related, and perhaps helpful:
  https://github.com/motiz88/canvas-text-metrics-polyfill
  https://github.com/motiz88/pixi.js/commit/397916d4548c02c6243d61951271f6e235818505
  https://github.com/motiz88/canvas-text-metrics-polyfill/issues/1
Also related: https://github.com/GoodBoyDigital/pixi.js/issues/1430 , https://github.com/GoodBoyDigital/pixi.js/issues/1021 , https://github.com/GoodBoyDigital/pixi.js/pull/1062 , and https://github.com/GoodBoyDigital/pixi.js/issues/1292 .

I'll be happy to help with testing. I can test on Mac OS and Windows.

I'm working on two additional test pages, they can be used already:
http://codepen.io/TobiReif/full/MYVaJY/
http://codepen.io/TobiReif/full/YPawVM/
Feel free to fork them, eg for experimentation.

**Comment by EricLesch** [comment]
The reason we switched was because of the textBaseline property when rendering text on canvas. Originally this was set to 'top'. Different browsers render 'top' in different locations. Therefore the text was being placed in different spots on different browsers. Using 'alphabetic' (the default setting for textBaseline), however, puts the font in the same place on every browser. But in order to accurately position the baseline in the same place, you have to know the ascent of the rendered  font, not the height. And you can't consistently guess the ascent based off of the height (like multiplying by 0.75 to guess) because some fonts have unusually high ascents (like Oswald).

The method that was used before basically injected text into the dom and measured the height but that returned different values for different browsers. What this meant was that if you had multiple lines of text going down the page in one text element (like 10 lines for example) then the tenth line would be in a completely different place depending on the browser (line height * 10).

This also seems a bit nitpicky for the use case of making a game where close enough is close enough and usually you won't have 10 lines of text running down the page. In that case you can just adjust things so close enough is close enough. 

However, I've written an editor for creating animatable websites in PIXI.JS.

Examples are here to give you an idea of what I'm talking about: 

example-designer.makemake.io
example-photography.makemake.io
example-planets.makemake.io

The editor is at makemake.io if you need to look at that to understand what I'm talking about.

Anyway, in the editor the user is picking a google web font on the fly and then putting as many lines of text in as they need. So the manual adjustment strategy doesn't really work. It needs to be accurate across different browsers and devices. Anyway, pixel scanning pretty much works but every once in a while I have bizarre issues on mobile devices where its wildly off and text gets clipped and I can't tell if this is due to my implementation or what.

Hopefully I will get ahold of a mobile device where the problem happens consistently and I can hook up a remote debugger to it.

Also, some commentary on the current implementation - according to the spec, actualboundingboxascent returns the ascent of the current line of text. So first we're trying pixel scanning an |Mq and say we get value of 10 for the ascent and the we get the actualboundingboxascent in a browser that supports it of the *each line of text* which happens to be "_____" so that will return 1 or 2. Actualboundingboxascent overrides the pixel scanned font ascent if the actualboundboxascent is found. That seems like a problem. We should be getting the ascent of the font, not the first line of text. Please note that I haven't tested this, but the code just looks wacky because it's measuring different text samples to compute the same property.

Ok, this post has gotten really long and I haven't suggested a solution. In any case, as I said before I'll try to figure it out as best I can when I get a chance.

BTW, whatever solution we come up with will probably never be exactly exactly the same all the time for webfonts since different browsers are consuming different file formats of the same font.

Thanks,
Eric

**Comment by tobireif** [comment]
Related:
Does a font size value in Pixi specify the overall (total) height of the text to be rendered?
CSS font-size specifies the M height https://encrypted.google.com/search?q=em+square&tbm=isch ;
that means that some glyphs can overstep that height boundary.
But when I need to place some text (using Pixi) inside an area (invisible box) and need to be sure that no part of any glyph can ever overstep the top or bottom of that area, it would be useful to be able to specify that height for the text (the total maximum possible height). (The default could still be M height.)

**Comment by gordyr** [comment]
Guys... my apologies if I am out of whack with exactly whats being discussed here since i'm late to the conversation....

But, chrome supports accurate native text measurement using the canvas element, and its implementation is currently an open bug for firefox (Looks like spartan is going to get it in windows 10 also)

This method accurately gives the ascent and every other kind of measurement you could wish for without requiring any DOM interaction.  

https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics


Perhaps it would be worth implementing this for ***v.3*** and falling back to the curren method where it is not supported?

These are the extra properties that get added to the ```ctx.measureText``` method

actualBoundingBoxLeft,
actualBoundingBoxRight,
fontBoundingBoxAscent,
fontBoundingBoxDescent,
actualBoundingBoxAscent,
actualBoundingBoxDescent,
emHeightAscent,
emHeightDescent,
hangingBaseline,
alphabeticBaseline,
ideographicBaseline

**Comment by GoodBoyDigital** [comment]
boom! thats rad!! We will definitely look into this! As usual, chrome is one step ahead :+1:

**Comment by gordyr** [comment]
@GoodBoyDigital Just checked and chrome requires the flag ```ExperimentalCanvasFeatures``` to be set to true for now.  It works beautifully though :)

With a bit of luck it shouldn't be long before it's default.

**Comment by GoodBoyDigital** [comment]
@gordyr! nice :)

**Comment by gordyr** [comment]
@GoodBoyDigital Just done a bit of hunting and it turns out there is already a polyfill for this.

I don't have time to test it right now but it would be interesting to give this a go and see how accurate it is compared with the current solution:

https://github.com/motiz88/canvas-text-metrics-polyfill

A quick look over the code shows that in browsers that don't support the new text metrics they render the text to an SVG and sniff the dimensions from that, which is an interesting idea in itself.

So it should be as accurate cross browser as SVG. Hope this helps!

**Comment by GoodBoyDigital** [comment]
Great find @gordyr! Will definitely give this a test.

**Comment by tobireif** [comment]
The polyfill you mention https://github.com/motiz88/canvas-text-metrics-polyfill has also been mentioned earlier (in two places :) ), please see the comments above yours. There also are some additional discussions linked.

The polyfill could be a basis for a solution, I think. Or perhaps https://github.com/Pomax/Font.js or http://pomax.github.io/fontmetrics.js/ .

It would be great to have exact text positioning and exact text measurements (total potential font height for avoiding potential overlap of dynamic text, bounding box of a specific text object, etc), with consistent rendering across browsers and OSs. Some users probably would also find anchorY=baseline useful (for baseline-aligning text objects eg using different fonts).

**Comment by photonstorm** [comment]
Just a heads-up: Before throwing the polyfill in be sure to check it works on CocoonJS and similar. My guess is it'll fail spectacularly if it's rendering to SVG. Meaning you'd potentially need 2 fallbacks (canvas5, to polyfill, to current implementation).

**Comment by tobireif** [comment]
Perhaps using the polyfill as-is wouldn't be a good idea, IMHO for this reason alone:

"Tests and performance: TBD. Supported browsers: TBD."

But a solution could be informed by its code.

SVG shouldn't be necessary.

**Comment by gordyr** [comment]
@tobireif Indeed, I've just seen that you mentioned the polyfill earlier.  Like I said , I'm like to the discussion and missed that :p 

@photonstorm Indeed, In environments without a DOM the polyfill would be no good.

Perhaps just using the canvas5 API when available and falling back to the current solution if not is our best bet then? Shame though as in my brief testing it works very accurately.

**Comment by EricLesch** [comment]
Hi.

The polyfill uses pixel scanning. So does fontmetrics.js and font.js. The current pixi implementation already uses pixel scanning. It just doesn't have all the other unnecessary code that those other libraries have. We gain nothing by using those other solutions.

Thanks,
Eric

**Comment by gordyr** [comment]
@EricLesch Not the one just mentioned above.  It inserts SVG elements and measures those.  Hence why it may not be suitable.

But regardless the point wasn't about the method used.  More the fact that there is now a native canvas method for this stuff around the corner as its finally gaining traction with the browsers.  

So using that when available and falling back to pixel scanning when its not seems like a good solution does it not?

**Comment by tobireif** [comment]
@EricLesch You have a good overview of the state of affairs and of the related issues. What do you see as left to be done? Are we getting the correct ascent and descent per font? (I also need the potential total height per font). Are glyphs still getting cut off?

In an earlier comment above you wrote:

"Anyway, pixel scanning pretty much works but every once in a while I have bizarre issues on mobile devices where its wildly off and text gets clipped and I can't tell if this is due to my implementation or what.

Hopefully I will get ahold of a mobile device where the problem happens consistently and I can hook up a remote debugger to it."

Any news? :)

**Comment by EricLesch** [comment]
Yeah that issue is a problem with my application. Basically sometimes webfonts were getting rendered before they were actually fully loaded in the browser. And that makes all the metrics wrong since the metrics are cached in PIXI.

Other than that everything *seems* OK.

To answer this question that you had before:

Related:
Does a font size value in Pixi specify the overall (total) height of the text to be rendered?
CSS font-size specifies the M height https://encrypted.google.com/search?q=em+square&tbm=isch ;
that means that some glyphs can overstep that height boundary.
But when I need to place some text (using Pixi) inside an area (invisible box) and need to be sure that no part of any glyph can ever overstep the top or bottom of that area, it would be useful to be able to specify that height for the text (the total maximum possible height). (The default could still be M height.)

Yeah for sure. You could take that into account to make sure that the text nevers gets rendered outside of the bounding box. Just don't use it for the line height (i.e. distance between baselines) because otherwise you will end up with multi-line text being rendered in different places in different browsers.

Regarding using the new native canvas measuring and the current method as a fallback - that sounds like a reasonable approach to me as long as it's well tested. 

Keep in mind that canvas text rendering positioning is very inconsistent across different browsers unless you set the textBaseline to 'alphabetic'. Every other setting yields 'disagreements' regarding positioning. So I would not blindly trust the new browser APIs to always give the right answer regarding font metrics.   

Also I have to be honest and tell you folks that the implementation that I'm using in production is a version before Sebastian made his changes a while back. I'm hesitant to change it because I don't want to deal with any regressions. I'm going to have to eventually though because I've gotten reports of fuzzy text rendering on retina displays.

Cheers!
Eric

**Pull request merged**
