### PR TITLE
Repeating deprecation warnings #4443

### PR DESCRIPTION
**Pull request by YahorPadlucki**
Added message-stack map to prevent showing multiple warning messages from same place. 
Didn't change anything for case with "IE < 10 and Safari < 6" - should I add separate array to store shown messages for this case?

Fix for issue #4443

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
@YahorPadlucki thanks for this! I had just added this feature to v5, but went for a slightly simpler approach. You can check it out here: https://github.com/pixijs/pixi.js/blob/next/bundles/pixi.js/src/deprecated.js#L2-L48

I would argue slightly against this approach only because if there are the same warnings called each frame from different places, it would still spam both messages and kill performance. I tend to lean towards being a little aggressive about silencing repeat warnings to not hurt performance overall.

What do you think?

**Comment by YahorPadlucki** [comment]
@bigtimebuddy, I thought that it is useful to show exact place were the warning is called from - to know where to fix it.
With your approach - if you want to fix all deprecations, it can be a bit confusing - when you fix it in one place, refresh, and get it in a new  place - which wasn't logged before.  So you need to know that you better to search same places in code. 
Thats the only concern I have.

**Comment by bigtimebuddy** [comment]
Yeah, I think the trade-off for fewer warnings for better performance is better. So I'm okay being conservative with warning and the dev having to find-and-replace, refresh than having to spit out every possible warning. I'm considering the worst case scenario, which I saw when we deprecated some filters APIs that get called every frame.

**Comment by bigtimebuddy** [comment]
@YahorPadlucki, would you mind changing this to block repeat deprecations based on the message and not the stack trace? Then, I'd like to merge for 4.8.0

**Comment by YahorPadlucki** [comment]
Changed. Sorry - didn't get that I need to update my branch - thought you will merge your solution.

**Comment by bigtimebuddy** [comment]
Thank you @YahorPadlucki!

**Pull request merged**
