### PR TITLE
Fix incorrect bounds for drawPolygon with lineAlignment lower than 0.5

### PR DESCRIPTION
**Pull request by andrej-ilic**
Fixes: #7389

When using drawPolygon with lineAlignment value less than 0.5, there is a gap between the bounds and the rectangle. The bounds are correct when using drawRect, though.

Example of bug: https://www.pixiplayground.com/#/edit/9JJqaW3NtUcH-2BRn4zgk

##### Description of change
Fix bounds when using drawPolygon with lineAlignment that is less than 0.5.

##### Pre-Merge Checklist

- [x] Tests and/or benchmarks are included
- [ ] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
A unit-test would be great for this, should be an easy check. The test should fail and dev and pass with this PR.

**Comment by JetLua** [comment]
It would be even better if we could consider orientation of vertices.

https://www.pixiplayground.com/#/edit/0-1pqUSC44SY11WpV_-0h

```js
const vertices = [
    new PIXI.Point(0, 0),
    new PIXI.Point(100, 0),
    new PIXI.Point(100, 100),
    new PIXI.Point(0, 100)
].reverse(); // There is no problem
```

**Review by bigtimebuddy — APPROVED** [review]

**Review by SukantPal — APPROVED** [review]
Little details!

**Comment by bigtimebuddy** [comment]
Thank you @andrej-ilic

**Pull request merged**
