### PR TITLE
Added missed dependency for canvas-graphics, canvas-mesh, canvas-sprite and canvas-text

### PR DESCRIPTION
**Pull request by SerG-Y**
##### Description of change

Just added missed `canvas-display` dependency to `canvas-graphics`, `canvas-mesh`, `canvas-sprite` packages and added `canvas-sprite` to `canvas-text` dependecy.

As you can see Graphics extends Container
https://github.com/pixijs/pixi.js/blob/8998367f026d2a729bc3ae8583c4b6954de42260/packages/graphics/src/Graphics.ts#L78
and CanvasRenderer execute next line
https://github.com/pixijs/pixi.js/blob/cdf9494b1a4f8ad758033683dcf101033cf8c95b/packages/canvas/canvas-renderer/src/CanvasRenderer.ts#L299
which call next method ```Container.prototype.renderCanvas``` it exist in `canvas-display` (**without this module it will throw an error that `renderCanvas` method doesn't exist in Graphics class**) package and then
 ```Container.prototype.renderCanvas``` call method `_renderCanvas`
https://github.com/pixijs/pixi.js/blob/8998367f026d2a729bc3ae8583c4b6954de42260/packages/canvas/canvas-display/src/Container.ts#L36
from `canvas-graphics`
https://github.com/pixijs/pixi.js/blob/8998367f026d2a729bc3ae8583c4b6954de42260/packages/canvas/canvas-graphics/src/Graphics.ts#L66

##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included
- [ ] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Quick question @SerG-Y, does this also apply to canvas-sprite, canvas-particles, canvas-mesh, etc? These probably have a similar situation.

**Comment by SerG-Y** [comment]
@bigtimebuddy oh, yes it applies to other modules too (canvas-sprite, canvas-particles, canvas-mesh, etc.)
I can fix dependencies for other modules too as a part of this PR or better to create a new one?

**Comment by bigtimebuddy** [comment]
Just append then to this PR. Thanks

**Comment by SerG-Y** [comment]
@bigtimebuddy As I see only **canvas-graphics**, **canvas-mesh**, **canvas-sprite** and **canvas-text** has missed dependency. Can you review it again, please

**Pull request merged**
