### PR TITLE
Added simultaneous multi touch events support

### PR DESCRIPTION
**Pull request by artsjedi**
Added a touch identifier variable to allow multiple touches events at once.
Each Touch (start to end) works independently based on its identifier.

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Nice. Did somebody test it?

**Comment by artsjedi** [comment]
Yes, i tested

**Comment by SeminYun** [comment]
identifier is started by 0..

0 and false is same...

there looks some problem with touchEnd

**Comment by artsjedi** [comment]
For touch it does not verifies if identifier is true or false. It's only verify if touchend identifier is equal to the the touchstart identifier.

**Comment by charlesbodman** [comment]
@SeminYun  I agree, there is definitely a bug with touch end.

**Comment by englercj** [comment]
Please do not make PRs to the `master` branch, PRs are only accepted to the `dev` branch. 
Please read through our [Contributing Guide](https://github.com/pixijs/pixi.js/blob/master/CONTRIBUTING.md) which details how to make good PRs and Issues.

**Comment by photonstorm** [comment]
You should so setup a GitHub PR template for that :)

On Thursday, 14 April 2016, Chad Engler <notifications@github.com> wrote:

> Please do not make PRs to the master branch, PRs are only accepted to the
> dev branch.
> Please read through our Contributing Guide
> <https://github.com/pixijs/pixi.js/blob/master/CONTRIBUTING.md> which
> details how to make good PRs and Issues.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pixijs/pixi.js/pull/2415#issuecomment-210118285>
>


-- 
Photon Storm Ltd.
http://www.photonstorm.com

Skype: richard.davey
Twitter: @photonstorm

Registered in England and Wales.
Company ID: 8036404
VAT Number: 136 4333 27

**Comment by englercj** [comment]
> You should so setup a GitHub PR template for that :)

Yeah i know, I have a saved response but haven't got around to the template yet. Ideally what I want is `master` to be latest development, a `release` branch is the latest release, and to download the latest release you just go to the releases page (builds never get committed). But not sure how feasible it is now that so many are used to the current flow.

**Pull request closed without merging**
