### PR TITLE
fix some types in 5.4.0-rc.2

### PR DESCRIPTION
**Pull request by Zyie**
##### Description of change

Fixes a couple of incorrect types after upgrading to to the pre-release

- `.from` function now have optional options
- export `TLoaderResource` as this is the type of `LoaderResource`
- make `context` optional in `Ticker.add`, `Ticker.remove`
- update `RenderTexture.baseTexture` to be type `BaseRenderTexture`
- make `options` optional in `destroy` functions for anything extending `DisplayObejct`

### CODE REVIEW

**Review by themoonrat — APPROVED** [review]

**Comment by bigtimebuddy** [comment]
What about using generics for RenderTexture... e.g. `extends Texture<BaseRenderTexture>` then you don't have to do some much casting and you can avoid overriding baseTexture. Otherwise this is great fixes.

**Review by bigtimebuddy — APPROVED** [review]
Optional comment above. Looks good.

**Comment by Zyie** [comment]
@themoonrat @bigtimebuddy sorry guys i found a lot more, opened this a little early.  If you guys dont mind re-reviewing

@bigtimebuddy Sure ill look into making it a generic

Also does anyone know if `TextStyle.constructor` should be optional? 
`deepCopyProperties(this, style, style);` this part confused me

**Review by ivanpopelyshev — APPROVED** [review]

**Comment by Zyie** [comment]
@bigtimebuddy ok made `Texture` generic

**Comment by ivanpopelyshev** [comment]
> ok made Texture generic

wait wait wait WHAT?

yeah, its old idea to make it generic because BaseRenderTexture, but honestly, its rudiment. We had VideoBaseTexture before, but we removed it in favor of resources.

Its better to add interface for BaseRenderTexture fields in RenderTexture itself.

My advice is to make it in separate PR

**Comment by ivanpopelyshev** [comment]
Alternative: add `castToRT()` into both Texture and BaseTexture

**Comment by Zyie** [comment]
@ivanpopelyshev ok I have reverted this change so it doesn't block fixing the rest of the types

**Review by bigtimebuddy — APPROVED** [review]

**Comment by bigtimebuddy** [comment]
Thank you @Zyie

**Pull request merged**
