### PR TITLE
Fix preparation of destroyed items

### PR DESCRIPTION
**Pull request by andrewstart**
* Added `isDestroyed` to DisplayObject, BaseTexture, which is automatically set in `destroy()`.
* The prepare plugins will automatically skip destroyed items, by checking the `isDestroyed` property.

### CODE REVIEW

**Comment by englercj** [comment]
I've seriously resisted the `isDestroyed` markers for a while. destroy() should just remove itself from the pixi ecosystem of things, and users should drop references. Anything else is an error and should be corrected, not worked around by checking if something is destroyed, imo.

**Comment by GoodBoyDigital** [comment]
I agree with chad on tho one!

**Comment by ivanpopelyshev** [comment]
That marker is better than events or signals. Of course it is only for internal usage or dirty production hacks. We don't have to promote it as solution for user problems. We have many hacks that we made for performance causes already.

**Comment by ivanpopelyshev** [comment]
Can we mark it in docs like "for internal usage" ?

**Comment by andrewstart** [comment]
I agree with the sentiment about what `destroy()` should do, but this is a situation where the thing being destroyed has no access to the renderer that might be preparing it, which limits us to setting a variable or emitting an event. We certainly could make the property internal to the library, if that would assuage your concerns.

**Comment by bigtimebuddy** [comment]
My preference would be to have this be an internal flag only (e.g., `_destroyed`) documented as private, since it is only used by internal classes.

**Comment by bigtimebuddy** [comment]
Also, @andrewstart this PR should go to **dev** not **master**.

**Comment by bigtimebuddy** [comment]
@andrewstart could you describe your use-case more specifically why this flag is necessary? Why are destroyed items being sent to the prepare plugin that cannot be mitigated by better resource management dev-side?

**Comment by andrewstart** [comment]
The use case is when one is preparing one or more items to be used, it could take a bit of time due to rate limiting to avoid hitting the framerate too hard. Sometimes, due to user input, the items being prepared need to be discarded (out of view, exiting state to a different game state, etc) before they can be prepared.

**Comment by englercj** [comment]
@andrewstart My follow question would be: why can't the destroy method send out a notification that the prepare system uses to know to remove that item from its list of items.

**Comment by andrewstart** [comment]
Our options are emitting an event or marking it with a private variable. My preference is the variable, because it should be slightly lighter weight, but if the consensus is that this should use events, I'll change it.

**Comment by bigtimebuddy** [comment]
@englercj or @GoodBoyDigital do you want to weigh-in on Andrew's options? I don't have a strong preference on way or another, but overall, I support this PR.

**Comment by englercj** [comment]
Like I mentioned, I'm abstaining :)

**Comment by bigtimebuddy** [comment]
I say private variable @andrewstart!

**Comment by andrewstart** [comment]
It has now been changed to `_destroyed` and is marked as private.

**Comment by bigtimebuddy** [comment]
**Please don't merge this right away.** Need to confirm *dev* vs *master* with @andrewstart.

**Pull request merged**
