### PR TITLE
Avoid equal compare between float number

### PR DESCRIPTION
**Pull request by uinz**
##### Description of change

Avoid equal compare between float number.

In extreme conditions, precision conversion can cause some strange problems.

```cpp
// vTextureId = 2.0
float textureId = floor(vTextureId + 0.5);
bool isEqual = textureId == 2.0; // isEqual = false
```
##### solution
```js
if (i < maxTextures - 1) {
  src += `if (vTextureId < ${i}.5)`;
}
```

##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included
- [ ] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Its true, I had some bad cases about it.

We have this line in v4: https://github.com/pixijs/pixi.js/blob/v4.x/src/core/sprites/webgl/generateMultiTextureShader.js#L13

Somehow, we forgot to merge it in v5.
Can you please modify PR that way it just adds that line and nothing else?

`float textureId = floor(vTextureId+0.5);`

**Comment by uinz** [comment]
@ivanpopelyshev done!

**Comment by ivanpopelyshev** [comment]
you can remove "<" now, because its always integer number.

**Comment by uinz** [comment]
I found that on some Android devices,

`floor(X.5)` not equal `X.0`.

So I suggest  use `<` instead of `floor` and `==`.

**Comment by ivanpopelyshev** [comment]
I am aware of this kind of effects, but i dont have a proof for it, every time i encountered it i just fixed it in plugins. I can merge that change in my libs: pixi-heaven, pixi-project, however I cannot accept it in pixijs vanilla core because i have teammates that will ask me to find that device and show them.

Also, it should work if X is big enough. For 0.0-32.0 it should work.

Please submit the demo and name of device, better if we know which videochip does that.

**Comment by ivanpopelyshev** [comment]
@GoodBoyDigital I summon you!

**Comment by uinz** [comment]
Fine, Thank you for your response.
I found this problem on `Samsung S9(8.0)` `Mi8(8.0&8.1)` `vivo nex A(8.0)`running on custom engine,
but on system browser works fine.

**Comment by ivanpopelyshev** [comment]
Did you test specific numbers or only small ones ?

**Pull request merged**
