### PR TITLE
Update Container.js about #3107

### PR DESCRIPTION
**Pull request by finscn**
I hope this PR could  make my point clear to you. @GoodBoyDigital  @englercj 

https://github.com/pixijs/pixi.js/issues/3107

### CODE REVIEW

**Comment by englercj** [comment]
I see what you are looking for, what I'm not clear on is the use-case. What is the situation where you need to change only the loop iterating children?

**Comment by finscn** [comment]
@englercj , example: I want to sort children before render , or do something like https://github.com/pixijs/pixi.js/issues/3107#issuecomment-253720685 , or something else.

The key point is NOT what I want to do now , is  when I want to do I could do.

Flexibility and Extensibility are very important for a Framework / Engine

**Comment by englercj** [comment]
> Flexibility and Extensibility are very important for a Framework / Engine

I absolutely agree, but we have to balance that against performance. Adding a function call to the hottest function in the engine is something we only want to do for a very specific reason. If you want to sort children you can do that in a couple other hook locations, or just run it as part of your updateTransform.

**Comment by finscn** [comment]
This   function call  is not the hotspot of performance , if you very care about "function call" ,
I think there are many unnecessary "function call"  in PIXI.js , 
e.g.  utils.sign , utils.removeItems  ,  the getter / setter of  width / height / tint / texture  ....

**Comment by englercj** [comment]
> utils.sign , utils.removeItems , the getter / setter of width / height / tint / texture

Getters/setters are inlined when trivial, as is util.sign. And we already talked about util.removeItems, it isn't adding a fn call but is removing GC trash.

**Comment by finscn** [comment]
I still think THIS "function call" is not the hotspot of performance.

**Comment by GoodBoyDigital** [comment]
Hi @finscn! Thanks for the PR. 

I guess there are many different ways to skin a cat :)

The situation being solved here is considered an edge case and I believe it can be sorted out by overriding the functions to ensure pixi does what you need it to do.

Cheers!

**Pull request closed without merging**
