### PR TITLE
Dev vao state cache

### PR DESCRIPTION
**Pull request by GoodBoyDigital**
Even more caching! even less webGL calls :D

This PR builds on #3201 and reduces GL calls even further by added a bindVAO function to the renderer.

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
It looks good but please search for every entry of "_activeTextureLocation" in the sources, and add "boundTextures" stuff there. We have that more than in one location

**Comment by englercj** [comment]
When we merge #3201 I will look into this one, looks like it depends on a lot of the same changes so it is hard to sift through what is unique here until we merge the other one.

**Comment by englercj** [comment]
Ok, rebased and squashed. Please review this to ensure I didn't screw something up in the merge. Look closely!

**Comment by GoodBoyDigital** [comment]
Nice man! Thanks for this, will double check tomoz :)

**Comment by GoodBoyDigital** [comment]
just working on this now.. almost there!

**Comment by GoodBoyDigital** [comment]
ok good to go! thanks for the help with git stuff @englercj 👍

**Comment by englercj** [comment]
Eslint is failing :)

**Comment by GoodBoyDigital** [comment]
all fixed! can I get one more approval pretty pls! cc @bigtimebuddy, @ivanpopelyshev

**Comment by bigtimebuddy** [comment]
@ivanpopelyshev tentative release for Wednesday

**Pull request merged**
