### PR TITLE
@function -> @method

### PR DESCRIPTION
**Pull request by SukantPal**
Functions and methods are fundamentally different things, at least for webdoc. A function can be called without a `this` context and is not a member of a class/object. They are documented as separate pages. A method does have a `this` context and only is called using "`context.`"`method()`

The methods added by the cache mixin should be tagged `@method` and not `@function`.

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
While you're at it, could you fix these two classes in the docs:

* BasisFile
* IGLUniformData

**Review by ivanpopelyshev — APPROVED** [review]

**Review by bigtimebuddy — APPROVED** [review]

**Review by YaroYaro8 — APPROVED** [review]

**Comment by YaroYaro8** [comment]
Hello

**Comment by YaroYaro8** [comment]
``h

**Comment by bigtimebuddy** [comment]
Thanks @SukantPal. If you can do a docs follow-up with those classes above, that would be great :+1:

**Pull request merged**
