### PR TITLE
Fix  rendering tinted Spines

### LINKED ISSUE #6921: Issue with rendering tinted Spines
I stumble upon two minor problems with rendering spine mesh with tint.

### Expected Behavior
Spine meshes to be rendered correctly 

### Current Behavior
**First one :**
When you try to render a spine mesh with tint on IE 11 (in legacy mode) browser fails with multiple IndexSizeError errors during rendering.

Culprit of the issue is recent change made with https://github.com/pixijs/pixi.js/pull/6783 in _renderDrawTriangle
Because textureSource is now tinted canvas the dimensions are wrong.

**Second one :**
In the same scenario - even the texture is properly generated by getTintedCanvas it is not drawn on the original canvas.

### Possible solution: 
For the IE11 issue if both textureWidth and textureHeight might be set to textureSource.width and textureSource.height. Then the IndexSizeError will not be risen.  

For the second one i have no proposed solution but i suspect the issue is with matrix transform ( it is based on original source which may cause tinted canvas to be drawn outside the clip area.)

### Step to reproduced

Attached codepen contains 2 canvases - one in legacy mode(A)  and one standard(B). 
On canvas A there are 2 spines - one with tint and one without 
The tinted spine is rendering only textures that have no transformation, other one is working fine.

On canvas B is webGL version of the same. 
If pixi library is set to version 5.3.0 only difference will be in canvas A - on the tinted canvas all textures are rendered - those with transformation are without tint 

### Environment

- **`pixi.js` version**: legacy 5.3.3
- **Browser & Version**: All
- **OS & Version**:  All
- **Running Example**: https://codepen.io/ggzz/pen/rNLBBGN

### PR DESCRIPTION
**Pull request by JetLua**
Fix #6921 

demo: https://codepen.io/jerald/pen/vYKBPQQ

It's hard to imagine this being the third revision.

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Are we sure that it wont tint texture two times if there are two meshes in spine?

**Comment by bigtimebuddy** [comment]
I worry about memory leaks creating a new `Texture` object if the Mesh's tint is constantly changing/animating. Would probably be better to re-use (or destroy the Texture)?

**Comment by ivanpopelyshev** [comment]
> I worry about memory leaks creating a new `Texture` object if the Mesh's tint is constantly changing/animating. Would probably be better to re-use (or destroy the Texture)?

Oh that's usual problem in tilingpsrite/sprite tinting for canvas2d.

**Comment by JetLua** [comment]
I cached `texture` should be better. If `tint` values change frequently, `_tintedCanvas` will still be generated frequently.

**Comment by bigtimebuddy** [comment]
Can you make sure the cache texture is destroyed when the Mesh is destroyed?

**Comment by ivanpopelyshev** [comment]
I dont like the fact that we cache tint of whole atlas, its bad for spine. I can approve PR though because i dont particularly care about that part :)

**Comment by JetLua** [comment]
I can't think of a perfect solution here, just to make up for the previous two PR mistakes. 😿

**Review by ivanpopelyshev — APPROVED** [review]

**Comment by ivanpopelyshev** [comment]
Let god sort them out. I'll fix if it becomes a memory problem for user. Btw, maybe spine meshes should have separate cache for that thing, then its definitely `pixi-spine` problem

**Review by bigtimebuddy — APPROVED** [review]
Thank you for this and for handling our feedback.

**Review by themoonrat — APPROVED** [review]

**Comment by bigtimebuddy** [comment]
Thank you @JetLua :+1:

**Pull request merged**
