### PR TITLE
Removed the ceil'ing of width and height in base texture

### PR DESCRIPTION
**Pull request by themoonrat**
As otherwise you lose precision going from one to the other.

Just trying to create some demo's that show up the issue in pixi playground

### CODE REVIEW

**Comment by themoonrat** [comment]
Grrr, thought this would be an easy one to reproduce - will come back and have a fresh think about why this fixed an issue in my version of the libs and why it's not doing anything here.

**Comment by ivanpopelyshev** [comment]
> As otherwise you lose precision going from one to the other.

> Just trying to create some demo's that show up the issue in pixi playground

> Grrr, thought this would be an easy one to reproduce - will come back and have a fresh think about why this fixed an issue in my version of the libs and why it's not doing anything here.

Welcome to the X-Files. I told you about extra `eps` before!

**Comment by themoonrat** [comment]
v5: https://www.pixiplayground.com/#/edit/wpSKMBzOgh1zvO6q~_iBw
v5 with this PR: https://www.pixiplayground.com/#/edit/RVnw2iNv3lVmSmNf5kBcA
v4: https://www.pixiplayground.com/#/edit/ZtI5gS5beIhU~UqRTx98b

**Comment by themoonrat** [comment]
Tbf, in this test, even v4 gets the height wrong.... works fine with Texture.WHITE

**Comment by ivanpopelyshev** [comment]
Good examples. My `eps` doesnt help there: https://www.pixiplayground.com/#/edit/VofrhNr_0CURPAIW2LB49

**Pull request merged**
