### PR TITLE
XOR blendMode

### LINKED ISSUE #6131: does blendMode support XOR?
like this
https://photonstorm.github.io/phaser3-docs/Phaser.BlendModes.html#.XOR__anchor

https://developer.mozilla.org/zh-CN/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation

thank you

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
Fixes #6131

Demo for all composition modes: https://www.pixiplayground.com/#/edit/bWeh8BX~4XaD5jslgtb_3

XOR is first row. Left is canvas2d, right is webgl.

### CODE REVIEW

**Comment by cursedcoder** [comment]
Example does not work: `Uncaught ReferenceError: sprite1 is not defined`

**Comment by bigtimebuddy** [comment]
Thanks @ivanpopelyshev

**Comment by huangjianke** [comment]
@bigtimebuddy hello, is there any plan to release 5.1.6 include this pr

**Comment by bigtimebuddy** [comment]
We are workin on 5.2.0 right now that will include this. Hope to have it out soon. Thanks for your patience.

**Comment by huangjianke** [comment]
Got it,
Thanks

**Pull request merged**
