### PR TITLE
Update JSDocs to latest version to fix EISDIR error

### PR DESCRIPTION
**Pull request by drpepper**
On my system (macOS High Sierra 10.13.2) the docs failed to build. Updating JSDoc to the latest version fixed the problem.

Previous error output:

```
$ npm run docs

> pixi.js@4.6.2 predocs /Users/himmelattack/Downloads/pixi.js-dev
> rimraf docs/**


> pixi.js@4.6.2 docs /Users/himmelattack/Downloads/pixi.js-dev
> jsdoc -c scripts/jsdoc.conf.json -R README.md

fs.js:1965
  binding.copyFile(src, dest, flags);
          ^

Error: EISDIR: illegal operation on a directory, copyfile '/Users/himmelattack/Downloads/pixi.js-dev/node_modules/@pixi/jsdoc-template/static/fonts/glyphicons-halflings-regular.eot' -> 'docs/fonts'
    at Object.fs.copyFileSync (fs.js:1965:11)
    at /Users/himmelattack/Downloads/pixi.js-dev/node_modules/@pixi/jsdoc-template/publish.js:391:12
    at Array.forEach (<anonymous>)
    at Object.exports.publish (/Users/himmelattack/Downloads/pixi.js-dev/node_modules/@pixi/jsdoc-template/publish.js:388:17)
    at Object.module.exports.cli.generateDocs (/Users/himmelattack/Downloads/pixi.js-dev/node_modules/jsdoc/cli.js:430:39)
    at Object.module.exports.cli.processParseResults (/Users/himmelattack/Downloads/pixi.js-dev/node_modules/jsdoc/cli.js:383:20)
    at module.exports.cli.main (/Users/himmelattack/Downloads/pixi.js-dev/node_modules/jsdoc/cli.js:227:14)
    at Object.module.exports.cli.runCommand (/Users/himmelattack/Downloads/pixi.js-dev/node_modules/jsdoc/cli.js:180:5)
    at /Users/himmelattack/Downloads/pixi.js-dev/node_modules/jsdoc/jsdoc.js:103:9
    at Object.<anonymous> (/Users/himmelattack/Downloads/pixi.js-dev/node_modules/jsdoc/jsdoc.js:104:3)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pixi.js@4.6.2 docs: `jsdoc -c scripts/jsdoc.conf.json -R README.md`
npm ERR! Exit status 1
```

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
We have not upgraded JSDoc from `3.4.3` because of ES6 bugs in 3.5.x. It broke a few things in our docs and no one has had time to fix it. What version of Node.js are you running @drpepper?

**Comment by drpepper** [comment]
Hi @bigtimebuddy I'm running node v9.3.0

**Comment by bigtimebuddy** [comment]
Could you try v6.x.x and see if that still produces the problem?

**Comment by drpepper** [comment]
Indeed, the docs work fine with node version v6.12.3

**Comment by bigtimebuddy** [comment]
Thanks for this. I'm going to hold off merging until we have time to verify that 3.5.5 works with our docs and template. The workaround for now is to use Node.js < v8.5.0 (which introduced this issue).

**Comment by bigtimebuddy** [comment]
I investigated this further and the docs built with jsdoc@3.5.5 are broken. For a little more context, see these:

* Related PR: https://github.com/pixijs/pixi.js/pull/4232
* JSDoc bug: https://github.com/jsdoc3/jsdoc/issues/1425

Basically, until the bug is addressed or someone goes thru all the source to workaround the issue, will not merge this PR. 

@drpepper: Thanks for tracking down this issue with Node.sj and jsdoc. If you don't have the time to retool this PR to workaround the jsdoc bug mentioned above, maybe close the PR and someone else could resubmit a more robust fix. How do you want to proceed?

**Comment by drpepper** [comment]
Thanks @bigtimebuddy for looking into it! I'll just close it for the time being then.

**Pull request closed without merging**
