### PR TITLE
Proposed fix for issue #3049

### PR DESCRIPTION
**Pull request by lordnoriyuki**

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Yeah, that was real pain to discover

**Comment by englercj** [comment]
Not sure about this, it may break the current expectations of some filters. I think most of them expect to be using a buffer that when cleared will be transparent. Clearing it to a solid color would make a lot of them act strangely.

**Comment by englercj** [comment]
Anyone else have thoughts about this?

**Comment by alvinsight** [comment]
I agree with @englercj a lot of existing filters would be weird, we probably want to make it an "opt-in" rather than an "opt-out" option.

**Comment by GoodBoyDigital** [comment]
As mentioned above I do not think this is quite the solution.

We could let a RenderTexture / baseRenderTexture have its own clear color? RenderTargets do after all!

**Comment by englercj** [comment]
Closing this PR, but the discussion can continue.

**Pull request closed without merging**
