### PR TITLE
Add the export namespace to the declaration file

### PR DESCRIPTION
**Pull request by JetLua**
Want to have a namespace called `PIXI` just like `v5`. It's easy to do some custom configuration in `vscode`.

Now: 
https://unpkg.com/browse/pixi.js@6.0.2/index.d.ts

```ts
export {}
```

This PR will replace it with:

```ts
export as namespace PIXI;
```

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Why not add the namespace to the individual packages too, not just the bundles? In that case, you could probably add this to `writeToIndex` function instead.

**Comment by bigtimebuddy** [comment]
I tested this and it works well if you want to define types using the PIXI global. For instance:

```typescript
import type { Texture } from 'pixi.js';
let texture: Texture;
```
could become:
```typescript
let texture: PIXI.Texture;
```

**Comment by bigtimebuddy** [comment]
@JetLua what do you think about adding this for all packages instead of just bundles?

**Comment by JetLua** [comment]
All right. I'll try it tonight.

**Comment by JetLua** [comment]
@bigtimebuddy Done.

**Review by bigtimebuddy — APPROVED** [review]
Much cleaner :+1:

**Review by Zyie — APPROVED** [review]
looks good!

**Comment by bigtimebuddy** [comment]
I think we should revert this change.

**Pull request merged**
