### PR TITLE
Refactor: extract variables & fix doc

### PR DESCRIPTION
**Pull request by finscn**

### CODE REVIEW

**Comment by finscn** [comment]
This PR is safe ，it only improves something，  does n't break any thing .

**Comment by finscn** [comment]
@GoodBoyDigital  ， Could you review  this one ，please？ Thank you

**Comment by bigtimebuddy** [comment]
Please do not merge this to dev before the 4.4 release this week.

**Comment by finscn** [comment]
This PR could make the code be more simple & with better performance.

**Comment by bigtimebuddy** [comment]
Thanks @finscn!

**Pull request merged**
