### PR TITLE
Added overlapping children tests

### PR DESCRIPTION
**Pull request by staff0rd**
I've added the following tests to help document the expectations of the InteractionManager specific to when the scene includes children that overlap.  The tests set up a scene similar to [this pen](https://codepen.io/staff0rd/pen/MJWJdy?editors=0010) and then fire clicks at various points on it.

I have left one test failing because it _feels_ off, considering the expectation is valid and passes when the parent is non-interactive.  I need some feedback regarding a decision on whether;

1. ~The expectation is wrong, and the test should be changed or;~
2. The expectation is correct, and the API needs to change ✔️ 

Upon which the following issues at least are then possibly fixed or are a step closer to resolution; #3419, #2921, #2364, #1901.

### When parent is non-interactive
* when both children are interactive
 :white_check_mark: should callback front child when clicking front child
 :white_check_mark: should callback front child when clicking overlap
 :white_check_mark: should callback behind child when clicking behind child
* when front child is non-interactive
 :white_check_mark: should not callback when clicking front child
 :white_check_mark: should callback behind child when clicking overlap
 :white_check_mark: should callback behind child when clicking behind child
* when behind child is non-interactive
 :white_check_mark: should callback front child when clicking front child
 :white_check_mark: should callback front child when clicking overlap
 :white_check_mark: should not callback when clicking behind child
### When parent is interactive
* when both children are interactive
 :white_check_mark: should callback parent and front child when clicking front child
 :white_check_mark: should callback parent and front child when clicking overlap
 :white_check_mark: should callback parent and behind child when clicking behind child
* when front child is non-interactive
 :white_check_mark: should callback parent when clicking front child
:x: should callback parent and behind child when clicking overlap
 :white_check_mark: should callback parent and behind child when clicking behind child
* when behind child is non-interactive
 :white_check_mark: should callback parent and front child when clicking front child
 :white_check_mark: should callback parent and front child when clicking overlap
 :white_check_mark: should callback parent when clicking behind child

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
2. Its correct and we have to change it.

**Comment by ivanpopelyshev** [comment]
I think after those tests we can integrate pixi-display at last :)

**Comment by ivanpopelyshev** [comment]
Currently element interaction is described by two vars: interactive and interactiveChildren.

Its not obvious that "interactive=false" element can be clicked and click bubbles to "interactive=true" parent.

**Comment by GoodBoyDigital** [comment]
Interesting stuff! Is there a convention we can follow here to help us point in the right direction? I originally tried to follow the flash way. It might be better for us to follow something like the DOM interactive model? How do they deal with this issue?

**Comment by GoodBoyDigital** [comment]
poke @staff0rd , is there a way we can roll this in without the failing test? I think this is a great set of tests. But not sure how easy the fix will be for the failing test right now. Maybe we could open up another issue for that? Cheers!

**Comment by staff0rd** [comment]
@GoodBoyDigital I've commented out the failing test and opened #3596 for the fix.

**Comment by GoodBoyDigital** [comment]
Three greats in one comment... I have been staring at git hub issues for too long :P

**Pull request merged**
