### PR TITLE
Changes for pixi-compressed-textures

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
newer version of resource-loader
pass the metadata to images
export WebGLManager

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
@englercj please reupload resource-loader 1.6.3 to npm.

**Comment by ivanpopelyshev** [comment]
[It Works! ](http://ivanpopelyshev.github.io/examples/index.html?s=textures&f=dds.js&title=DirectDrawSurface%20(DDS)&plugins=pixi-compressed-textures)

Please publish resource-loader and merge this thing.

**Comment by englercj** [comment]
Publihed 1.6.3, and travis is rebuilding. I'll look to merge tomorrow.

**Comment by ivanpopelyshev** [comment]
How about bumping pixi version?

**Comment by englercj** [comment]
There are other changes in `dev` that we are not ready to release yet, and a few more things we want to get in first.

You can see all the things waiting for release here:

https://github.com/pixijs/pixi.js/compare/master...dev

**Pull request merged**
