### PR TITLE
Fixed a difference between canvas and webgl sprite renderer on scaled textures.

### PR DESCRIPTION
**Pull request by ceco-fmedia**
You can see it here:
https://jsfiddle.net/1cj8w0mv/24/

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
@ceco-fmedia could you make a unit-test for this?

**Comment by ivanpopelyshev** [comment]
@bigtimebuddy Its not easy to add graphical unit test in pixi. We have only one such test.

I've made new library for testing based on `PIXI.extract` but it was too difficult and im going to make that PR for v5.

Lets create new label "needs visual test" and when the time comes, I'll go through all issues under that label.

**Comment by bigtimebuddy** [comment]
I guess I was thinking this could be a pretty straightforward measuring the width/height of the scaled texture. Not a visual test.

**Comment by ivanpopelyshev** [comment]
@bigtimebuddy what about that label idea?

**Comment by bigtimebuddy** [comment]
Thanks @ceco-fmedia

**Comment by ivanpopelyshev** [comment]
@themoonrat awesome! Lets remove "* resolution" from it.

**Comment by ivanpopelyshev** [comment]
or just roll it back, we can make those changes in v5.

**Comment by ceco-fmedia** [comment]
@themoonrat can you check again with https://github.com/ceco-fmedia/pixi.js/tree/canvas_sprite_renderer

**Comment by themoonrat** [comment]
@ceco-fmedia  still have the same display issue on that code too, unfortunately

**Comment by ceco-fmedia** [comment]
@themoonrat can you send me a sample atlas to test with?

**Comment by ceco-fmedia** [comment]
@themoonrat were you able to create some samples?

**Comment by ceco-fmedia** [comment]
@themoonrat can you check again with https://github.com/ceco-fmedia/pixi.js/tree/canvas_sprite_renderer

**Pull request merged**
