### PR TITLE
Resetting sprites array on flush (#4090)

### PR DESCRIPTION
**Pull request by YahorPadlucki**
Fix for #4090

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
I dont think that `.length=0` removes that optimization, array does stilll has the same capacity and `push` has to work fast.

**Comment by GoodBoyDigital** [comment]
Cool! If theres no difference in perf, i'm happy! But lets test first 👍

**Comment by ivanpopelyshev** [comment]
https://jsperf.com/js-empty-array/1

30-50% slower depends on browser and platform.

I agree that `length=0` is fast enough for rendering loop, but for SpriteRenderer we need as much speed as we can.

Line 262, `sprites[i] = null` will handle this better.

**Comment by YahorPadlucki** [comment]
@GoodBoyDigital  @ivanpopelyshev thanks for review and explanations. It is valuable experience for me.

**Pull request closed without merging**
