### PR TITLE
Fix for TilingSprite.tilePosition with textureResolution > 1 on CanvasRenderer

### LINKED ISSUE #3892: TilingSprite CanvasRenderer @2x images tilePosition bug
Hello everyone

I have noticed that when animating the `tilePosition.x` of an instance of `PIXI.extras.TilingSprite` with the canvasRenderer and the sprite is built from a source retina @2x image e.g. myImage@2x.png there is a jump when the new tile is added to the left, I think its a simple miscalculation error.

I have made an example, simply watch a wait until the tilePosition.x is a factor of  256px

http://jsfiddle.net/brenwell/kn6zvpnL/12/

I looked through the issues and there seemed to be many similar issues but not this exact one

Thanks for any help in advance

### PR DESCRIPTION
**Pull request by brenwell**
Fixes #3892 a small calculation issue with tilingsprites.

You can see the bug in action here

http://jsfiddle.net/brenwell/kn6zvpnL/13/

### CODE REVIEW

**Comment by brenwell** [comment]
Oh shit it contains all my previous commit messages

**Comment by brenwell** [comment]
My previous commits have been accepted and merged into Dev already I believe.
How can I prevent these messages from appearing here and only having my last commit mentioned in the pull request?

**Comment by bigtimebuddy** [comment]
@brenwell don't worry about it, we'll squash these commits when it is merged in.

**Comment by brenwell** [comment]
Ok Cheers @bigtimebuddy. But for future reference how can I prevent that. Should I be using *rebase* instead?

**Comment by englercj** [comment]
You should branch from dev to make changes, one branch per PR. Also consider rebasing onto `dev` if a bunch of changes make it in, to ensure your PR is on the latest version.

Either way, it is fine; we will squash these out later.

**Comment by brenwell** [comment]
Ok, will do in future. Cheers

**Pull request merged**
