### PR TITLE
prevent gaps in duplicate lineTo calls

### PR DESCRIPTION
**Pull request by gooderist**
Ignore duplicate calls to lineTo (same x, y inputs) to prevent gaps in WebGL render. Addresses #4046 and #3592. edit: also #4890

Notes: it is not yet understood why duplicate lineTo calls caused gaps to begin with. Also, I'm not sure of a good way to unit test this without comparing render output. If anyone has anything to say about either point, I'm all ears. Thanks!

### CODE REVIEW

**Comment by themoonrat** [comment]
Unit test wise you could count how many points in the path there are?

**Comment by gooderist** [comment]
Okay, sounds good to me! Thanks!

**Comment by englercj** [comment]
I think more importantly for the test is that you have the right points. Can you assert that the path is `[0, 0, 10, 0]`?

Otherwise :shipit:

**Comment by gooderist** [comment]
Good idea, will do!

Btw, would you happen to know how to run the WebGLRenderer unit tests? They turn up as "pending" when I do npm test. Clearly, I need to run them on a browser or something but I'm not sure how.

**Comment by gooderist** [comment]
Thanks @bigtimebuddy. So, I'm trying to run WebGLRenderer related tests. When I `npm run` they show up as `pending` like this...





This is to be expected since there is no WebGL renderer in node, but I did notice that electron is in the project and so I assumed there was some automated script to do render tests. Am I assuming correctly or should I check my settings or... ?

**Comment by gooderist** [comment]
In case anyone else is unable to run WebGLRenderer tests (people with older graphics cards)

Your GPU is likely [blacklisted by Chromium](https://github.com/electron/electron/issues/8217) like mine (Intel HD Graphics 3000). The link contains instructions on how to ignore the gpu blacklist which will let your tests run like the wild stallions they yearn to be.

Or you can buy a new(er) Macbook. Up to you!

**Comment by distinctdan** [comment]
Just ran into this myself when calling a `moveTo(100, 100); lineTo(100, 100)`. I'm using font path data exported by opentype.js, and the glyphs have some duplicate calls like that. Thanks for fixing it!

**Pull request merged**
