### PR TITLE
[next] Re-organize contributor documentation

### PR DESCRIPTION
**Pull request by allanbreyes**
Syncs changes with #4768 per @bigtimebuddy's request. + a few minor fixes.

### CODE REVIEW

**Comment by cursedcoder** [comment]
Would be nice to add link to wiki 
https://github.com/pixijs/pixi.js/wiki

**Comment by bigtimebuddy** [comment]
@allanbreyes, I like @cursedcoder suggestion, could you add a link to the wiki in there too?

**Comment by allanbreyes** [comment]
Sure thing!

**Comment by bigtimebuddy** [comment]
Thanks @allanbreyes

**Pull request merged**
