### PR TITLE
Add --strictNullChecks check for specific path

### PR DESCRIPTION
**Pull request by SuperSodaSea**
#### Description of change

Add `npm run types:strict` for enabling `--strictNullChecks` for specific path. The `scripts/filterTypeScriptErrors.js` is based on the code in #8852.

Once we migrated a package to `--strictNullChecks`, we should add its path to `scripts/filterTypeScriptErrors.js` like this:

https://github.com/pixijs/pixijs/blob/4aba79d7cb6e0e686e0f6f2e735b4b6b3991cd1a/scripts/filterTypeScriptErrors.js#L1-L3

Failed example: https://github.com/pixijs/pixijs/actions/runs/3662967151/jobs/6192432725#step:11:26

#### Pre-Merge Checklist

- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Review by bigtimebuddy — COMMENTED** [review]
Very helpful! Couple of things, could you convert the script to TS and use ts-node? Also, could you remove this check from dist and postversion? I don't want to block these things yet, seeing how the strictNullChecks will take awhile to sort. lastly could you add some documentation to the script itself to explain why it exists, for what purpose.

**Comment by SuperSodaSea** [comment]
@bigtimebuddy Converted to TS and document added!

**Review by bigtimebuddy — APPROVED** [review]
Thanks for this 👍

**Comment by bigtimebuddy** [comment]
One last thing, could you update #8852 with details about how to use this script?

**Comment by SuperSodaSea** [comment]
Updated :)

**Pull request merged**
