### PR TITLE
Bugfix/masking whilst rendering to a render texture

### PR DESCRIPTION
**Pull request by GoodBoyDigital**
Fixes issue where masking is not currently working on render textures. Enjoy!

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
I'm afraid thats also a mask problem. You sure?

**Comment by ivanpopelyshev** [comment]
Also, make sure that filterArea is set to null after the fact. Make sure that if user specifies his own filterArea, its used instead of the substitute.

**Comment by GoodBoyDigital** [comment]
Hey @ivan this is fixing masking whilst rendering to a render texture, not masking with a render texture. Different problems init :)

**Comment by bigtimebuddy** [comment]
@GoodBoyDigital could you fix up the linting on this?

**Pull request merged**
