### PR TITLE
fix a bug

### PR DESCRIPTION
**Pull request by wswei99**
please check this...

### CODE REVIEW

**Comment by themoonrat** [comment]
Could you supply a bit more detail about the issue and the fix please?

**Comment by bigtimebuddy** [comment]
@wswei99: In general, the responsibility to test and verify changes is on the person submitting the pull-request because we are all volunteers working on this project. This change requires a unit-test, at least, to be added to make sure it addresses some underlying issue. Also, it's very important to give some more context for what this change accomplishes in the description of this pull-request.

**Comment by wswei99** [comment]
/**
 * Connect to the list.
 * @param {TickerListener} previous - Input node, previous listener
 */
connect(previous)
{
    this.previous = previous;
    /** 
    * If the last node is not a tail node, the current operation is an insert.
    * The order of elimination is '... <-> previous <-> this <-> previous.next <-> ...'
    * so 'previous.next.previous = this;' and 'this.next = previous.next;' Is the logic code for the insertion operation, should be written in the 'if' statement.
    */
    if (previous.next)
    {
        previous.next.previous = this;
    }
    this.next = previous.next;
    previous.next = this;
}

**Comment by bigtimebuddy** [comment]
Can you please provide and example or a jsfiddle that reproduces this problem?

**Comment by bigtimebuddy** [comment]
You’re just explaining the code change, but what is the effect? What is the bug or crash?

**Comment by bigtimebuddy** [comment]
@wswei99 Would you mind showing an example or JSFiddle of this breaking? Would help to verify this change. Thank you!

**Comment by bigtimebuddy** [comment]
@wswei99 I'm going to close this PR because of insufficient evidence showing this fix resolves a real bug. If you can demonstrate a bug or make a unit-test that shows the problem, we will reconsider this.

**Pull request closed without merging**
