### PR TITLE
Fix SVG disposed while loading

### PR DESCRIPTION
**Pull request by maximgavrilov**
##### Description of change
If SVGResource was disposed during load, do not draw it on canvas.

##### Pre-Merge Checklist
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by cursedcoder** [comment]
Also, I can't see the green build.

**Comment by maximgavrilov** [comment]
But there no "done" events in this case, because they are suppressed with dispose.

Unit can be something like
```
const resource = new SVGResource(                                   
    path.join(this.resources, 'heart.svg'),                         
);                                                                  

resource.dispose();                                                                    

// ??? wait some time
// without patch it throws error ('canvas is null' in _loadSvg::tempImage.onload)
// with patch nothing is throwed
// maybe make resource.load() promise rejected on dispose? I am not certain with this.
```

**Comment by bigtimebuddy** [comment]
Travis is having issues atm

**Comment by bigtimebuddy** [comment]
Thank you @maximgavrilov!

**Pull request merged**
