### PR TITLE
cacheAsBitmap is leaking objects

### PR DESCRIPTION
**Pull request by sivael**
When destroying objects that had cacheAsBitmap, the internal objects were being retained - options parameter decides whether the children should be destroyed.
If you pass true to a containers destroy that's being cached as bitmap, the containers contents would not be destroyed, unless we pass the parameter to the original destroy method here.

To observe:
1. Create an object containing other objects inside.
2. Cache it to bitmap
3. Destroy the object
4. Goto 1

It will leak the containers sub objects and in the end crash the browser(observable on mobile mostly where memory is much more limited)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Thanks @sivael! I would like to release this ASAP, so I'm manually pushing this change to **master** (c1903f94d5fe4cd965fb68fcbf128f7c2640376c). Will close this.

**Comment by sivael** [comment]
@bigtimebuddy What was preventing this PR from merging? 
Initially it was LINT that prevented it but I've fixed it since.

**Comment by bigtimebuddy** [comment]
I'm not positive, but it looks the Travis never completed (or started) the comment commits. That's needed in order to be merged.

**Comment by sivael** [comment]
Ok, thanks:) Thought i did something wrong there.

**Comment by bigtimebuddy** [comment]
No worries, thanks for the addition. I made sure to add your name the commit message, so you got credit for this.

**Comment by sivael** [comment]
No problem, glad to help:)

**Pull request closed without merging**
