### PR TITLE
Replaces Testem with Floss

### PR DESCRIPTION
**Pull request by bigtimebuddy**
## Overview

Replaces [Testem](https://www.npmjs.com/package/testem) (PhantomJS-based) with [Floss](https://www.npmjs.com/package/floss) (Electron-based) for the unit testing. This runs the unit-tests within an instance of Chrome so that the tests can be debugged using DevTools (`npm run test:debug`) as well as headlessly. Also, with this approach PIXI can now use WebGL and Canvas APIs for creating actual render unit-tests.

### Added
* Adds new script `npm run test:debug` to open unit tests with DevTools
* Implemented unit-testing with Floss

### Fixed
* Fixes the linting errors and warnings generated from the existing unit-tests.

### Removed
* Removes the Testem tools for unit-testing
* Removes chai and Mocha dependencies, these are included in Floss
* Removes a bunch of unused/old test files

_**Full Disclosure: I co-develop Floss for unit-testing WebGL renders.**_

### CODE REVIEW

**Comment by GoodBoyDigital** [comment]
Nice job dude!

**Comment by englercj** [comment]
> Replaces Testem (PhantomJS-based) 

Just an fyi, Testem is not PhantomJS based, it is just a launcher. You can run tests in any browser you want (Chrome, FF, phantom, Saucelabs, Selenium, BrowserStack, anything).

Pixi even had the config setup to run Chrome/FF locally, and FF on travis.

**Comment by bigtimebuddy** [comment]
@englercj Yup, my mistake! I did some playing around with Testem and I think Electron is still an arguably better unit-test environment for PIXI. 

Consistency is really important if you're trying to use unit-test to help refactor a bunch of code (which is one of the benefits of having good coverage), inconsistent client browsers introduce some annoying amounts of variability and Testem does not control for this. Testem opens a world where some tests pass locally but fail on Travis and visa-versa. I want to ensure that unit-tests get run exactly the same client-side (and are a mandatory part of the build process) and run exactly the same on Travis. 

Cross-browser testing is an important issue we should parse from unit-testing. Related, but we should make integration tests that test as many features across as many supported browsers as possible. We should find a better tool to achieve this, Testem seems like not such a good option.

**Comment by RanzQ** [comment]
@bigtimebuddy I'd like to ask about the license included in `floss` since it's not open source. How permissive it us, could I use it for any project I'd want?

**Comment by bigtimebuddy** [comment]
@RanzQ Currently, am in the process of open-sourcing, feel free to use wherever. Once open, license is probably going to be very permissive (e.g. MIT).

**Comment by bigtimebuddy** [comment]
@RanzQ Here you go: https://github.com/jiborobot/floss/

**Pull request merged**
