### PR TITLE
Do check as same as `calculateVertices`

### PR DESCRIPTION
**Pull request by finscn**
I already ask a question about this  https://github.com/pixijs/pixi.js/issues/3408  , but no one reply .
I think opening PR is better than asking question.

### CODE REVIEW

**Comment by finscn** [comment]
@staff0rd  ， I can't understand what's your mean.
What should I do to this PR ?

**Comment by staff0rd** [comment]
Instead of this;
~~~javascript
if (this._transformID === this.transform._worldID && this._textureID === this._texture._updateID) { return; }
...
if (this._transformID === this.transform._worldID && this._textureID === this._texture._updateID) { return; }
~~~

Self-documenting and reduced;

~~~javascript
isAlreadyUpdated() {
    return this._transformID === this.transform._worldID && this._textureID === this._texture._updateID;
}

if (isAlreadyUpdated()) { return; }
...
if (isAlreadyUpdated()) { return; }
~~~

**Comment by finscn** [comment]
@staff0rd but it will create a new function call. In this place I think performance is very important.

**Comment by staff0rd** [comment]
Ah I see - I wasn't aware javascript had a cost associated with function declaration.  TIL.

**Comment by englercj** [comment]
If you're lucky it gets inlined, but not guaranteed. That is one of the shitty parts of working with such a dynamic lang.

**Comment by englercj** [comment]
I want @ivanpopelyshev to see this before we merge, since he did a lot of trim work.

**Comment by ivanpopelyshev** [comment]
I don't think we can use same temporary variables in two different functions. If you update one of them, second wont be updated.

**Comment by finscn** [comment]
@ivanpopelyshev  ， you're right . I changed them.

**Comment by GoodBoyDigital** [comment]
good catch @ivanpopelyshev !

**Pull request merged**
