### PR TITLE
[Please close] and navigate to https://github.com/pixijs/pixi.js/pull/4246

### PR DESCRIPTION
**Pull request by axldns**
… frames already scaled #4213

minimal source sample exposing the problem:
https://github.com/axldns/axldns.github.io/tree/master/pixi4v5bitmapfont
live:
https://axldns.github.io/pixi4v5bitmapfont/

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Thanks @axldns. Would you mind fixing linting error here: https://travis-ci.org/pixijs/pixi.js/builds/262621654#L308

**Comment by axldns** [comment]
sure, finally passed

**Comment by englercj** [comment]
Looks like this is mostly just a revert of #3993, is the issue that PR fixed active again after this change?

**Comment by axldns** [comment]
@englercj indeed, looks like revert. 
Not sure what do you mean with the other part. 

- If you ask if our PR resolves our issue, then yes, it does (in number of games) 

- If you ask if our PR breaks anything up with issue #3993 - we're not able to tell since no source files, no live examples attached in that issue

**Comment by axldns** [comment]
Thanks for the review @bigtimebuddy . 
The easy workaround proposed isn't that easy in fact. We have lot of games on production servers. They all benefit from bitmap fonts nested into bigger atlases @ various resolutions and PIXI supporting this until **v4.1.1**.
Understanding both scenarios analysed in your review, please find updated PR. I have also changed target branch from dev to master, since this could be considered as backward capability fix.
Best

**Comment by axldns** [comment]
Moved to https://github.com/pixijs/pixi.js/pull/4246 since target branch has changed

**Pull request closed without merging**
