### PR TITLE
use correct shader

### PR DESCRIPTION
**Pull request by finscn**

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Do you have a case when that does not work? Texture can be changed, trimming will be changed too. The idea is that both shaders have the same input and thus same location numbers

**Comment by finscn** [comment]
"Do you have a case when that does not work?"  :  No. If no this PR, it could work too. But in logic , it's not perfect.
So , this pr is not for fixing bugs, just  cosmetic.

**Comment by finscn** [comment]
By the way , the mesh in dev branch has been changed (about tint) , This branch also need to update.

**Comment by ivanpopelyshev** [comment]
Lets not put this shader into glData then.

**Comment by finscn** [comment]
> Lets not put this shader into glData then.

I can't understand this sentence. Could you tell me more ?

**Comment by finscn** [comment]
@ivanpopelyshev , I've remove the `shader` in glData

**Pull request closed without merging**
