### PR TITLE
Upgrade @pixi-build-tools/api-extractor-lerna-monorepo to 1.0.3

### PR DESCRIPTION
**Pull request by SukantPal**
This new version will exit with a non-zero code immediately when
@microsoft/api-extractor fails on a specific package. This ensures our
CI doesn't pass when a scoped package's declaration file fails to be
generated.

### CODE REVIEW

**Comment by SukantPal** [comment]
@bigtimebuddy Is the package-lock.json diff too much?

**Comment by bigtimebuddy** [comment]
Woah, why is that package lock diff so crazy?

**Comment by SukantPal** [comment]
Not sure, I did “npm ci” before installing the new package. Possibly that?

On Mar 23, 2021, at 11:13 PM, Matt Karl ***@***.******@***.***>> wrote:



Woah, why is that package lock diff so crazy?

**Comment by bigtimebuddy** [comment]
Closing in favor of #7333

**Pull request closed without merging**
