### PR TITLE
RenderTexture#destroy destroys the depth texture as well.

### PR DESCRIPTION
**Pull request by SukantPal**
#6556

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Maybe it would be better to move it to `dispose()`. Technically its the same thing for Framebuffer,  because its never recovering.. hm...

**Comment by SukantPal** [comment]
@ivanpopelyshev Dispose just removes the framebuffer from the GPU. Destroy will destroy the data itself.

We shouldn't move this to dispose. `Framebuffer#dispose` disposes the depth texture already by disposing the framebuffer-object, which holds the depth texture on the GPU.

**Comment by ivanpopelyshev** [comment]
> We shouldn't move this to dispose. `Framebuffer#dispose` disposes the depth texture already by disposing the framebuffer-object, which holds the depth texture on the GPU.

Nope, that's the point - depthTexture is not disposed on the GPU automatically. Framebuffer disposes itself and renderbuffer if mounted, but not depthTexture.

```
            gl.deleteFramebuffer(fbo.framebuffer);
            if (fbo.stencil)
            {
                gl.deleteRenderbuffer(fbo.stencil);
            }
```

Oh, I feel that we are missing MSAA case here: `fboFramebuffer` should be also disposed automatically :(

**Comment by SukantPal** [comment]
@ivanpopelyshev Correct, because the depth texture _was not added internally by the framebuffer system_. This is way you cannot run `gl.deleteTexture` on the depth-texture - this is equivalent of destroying (not disposing) the depth texture: https://github.com/pixijs/pixi.js/blob/9cdb526a9bfbc4643d36a106be3f2b16981e516d/packages/core/src/textures/TextureSystem.ts#L353

**Comment by SukantPal** [comment]
The user _might not want to destroy the depth texture and may reuse it after destroying the framebuffer_. That is not the case for the stencil renderbuffer, because it is never manually added to the framebuffer.

**Comment by ivanpopelyshev** [comment]
Agree. But then it might be user problem to destroy the depth texture when he destroys renderTexture and we dont need this PR. 

I don't think it matters, we can change it later, lets merge this one.

**Comment by SukantPal** [comment]
@ivanpopelyshev Agreed, it is all semantics. Putting it in render-texture makes more sense for now, as it is a higher-level API and users might face problems like with 6556.

The user can still "snatch" the depth texture before it gets destroyed by listening to "dispose".

**Comment by SukantPal** [comment]
@bigtimebuddy Done!

**Comment by bigtimebuddy** [comment]
Did you forget to commit RenderTexture? `Error: Cannot find module './RenderTexture'`

**Comment by SukantPal** [comment]
@bigtimebuddy Yup, I forgot a `git add .`

**Pull request merged**
