### PR TITLE
sprite json data "sourceSize" change to a optional data

### PR DESCRIPTION
**Pull request by 1056ng**

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Hm. Why is it optional?

**Comment by 1056ng** [comment]
@ivanpopelyshev 
coz, I has recognized that Texture class's `orig` is optional, right?

https://github.com/pixijs/pixi.js/blob/dev/src/core/textures/Texture.js#L99

**Comment by ivanpopelyshev** [comment]
I do not know if it is optional in spritesheet format.

**Comment by 1056ng** [comment]
> I do not know if it is optional in spritesheet format.

incidentally, `v3` is working.
https://github.com/pixijs/pixi.js/blob/master/src/loaders/spritesheetParser.js#L85

**Comment by ivanpopelyshev** [comment]
I do not understand what's the bug and what are you trying to fix. Can you be more clear please?

**Comment by 1056ng** [comment]
Sorry for that, I tried to reduce in json size. But, it's not good technique.

**Comment by ivanpopelyshev** [comment]
Ah, that's fine. Just make your own parser for your format, and ask me if you will have problems with creating textures

**Pull request closed without merging**
