### PR TITLE
Add exception handling to `utils.canUseNewCanvasBlendModes`

### PR DESCRIPTION
**Pull request by nikolowry**
Multiple sites using pixi have been throwing the following error:
`Uncaught TypeError: Cannot read property 'data' of undefined`.

----

Chromium v53 x64 Linux  Kernel 4.6

### CODE REVIEW

**Comment by nikolowry** [comment]
Also want to add some context to this - I use a few extensions to prevent canvas fingerprinting and they seem to be the cause of my error. 

Would prefer to keep my privacy, while also being able to view sites that use pixi.

**Comment by englercj** [comment]
Instead of try catch:

```js
var imageData = context.getImageData(2,0,1,1);

if (!imageData)
{
    return false;
}

var data = imageData.data;

return //...
```

**Comment by englercj** [comment]
Oh shoot just realized this PR was to `master`, we only accept PRs to `dev`:

https://github.com/pixijs/pixi.js/blob/master/CONTRIBUTING.md

**Comment by nikolowry** [comment]
I'll close and reopen another - thanks

**Pull request closed without merging**
