### PR TITLE
fix(render): make cacheAsBitmap not affect other textures with a filter for 1 frame

### PR DESCRIPTION
**Pull request by Loonride**
##### Description of change

The issue I was experiencing was that I had a single texture that had a custom filter. Any time I created a new Graphics object and set `cacheAsBitmap` to true, the texture with the custom filter would partially flicker for that frame while the Graphic was being cached. This change fixed the problem for me.

I saw an issue which may be the same as my problem here: https://github.com/pixijs/pixi.js/issues/2831

If you really need me to, I could make a new reproducible test demo. But preferably not, I think this change is quite straightforward.

##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included
- [ ] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [ ] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Based on our experience with that kind of bugs:
1. I trust that you found the real issue
2. I require example anyway to ensure that issue wont appear after a regression

Flickering is easy to reproduce: turn off ticker and manually call render() one or two times.

**Comment by Loonride** [comment]
> Based on our experience with that kind of bugs:
> 
> 1. I trust that you found the real issue
> 2. I require example anyway to ensure that issue wont appear after a regression
> 
> Flickering is easy to reproduce: turn off ticker and manually call render() one or two times.
> 
> If you cant reproduce it or dont have enough time - I'll deal with it in weekend.

Here is an example: https://jsfiddle.net/Loonride/vcu4n1bm/18/

You will notice that a part of the rabbit image cuts off during the frames where a new graphics object is created.

I found that these lines were part of the problem, as removing them from the example fixes the issue:

```
if (sprite) {
        if (sprite.parent) {
            var parent = sprite.parent;
            parent.removeChild(sprite);
            parent.addChild(sprite);
        }
    }
```

I use this method to bring sprites to the top of the stage in my project. Is there a better recommended way to reorder pixi sprites?

**Comment by ivanpopelyshev** [comment]
OK, still need to find time to review it properly and add a unit test.

**Comment by ivanpopelyshev** [comment]
I'm on a break but we need someone to add a test. @eXponenta or someone else

**Comment by ivanpopelyshev** [comment]
Demo is here: https://www.pixiplayground.com/#/edit/LZli1NESJ3Vlf_8l9Fdbe

If you comment out first line, you'll see the original error.

btw, We dont need to clone renderTexture, only `sourceFrame`, please make that change in PR and I'll approve it.

**Comment by ivanpopelyshev** [comment]
@Loonride in case you dont have time right now, I can make separate PR with cloning just rectangle. I think whether should I try to add tests too...

**Comment by bigtimebuddy** [comment]
Closing in favor of #6466

**Pull request closed without merging**
