### PR TITLE
Convert mixin-cache-as-bitmap to TS

### PR DESCRIPTION
**Pull request by SerG-Y**
#### Description of change
Converted mixin-cache-as-bitmap to TS

##### Pre-Merge Checklist

- [x] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by SerG-Y** [comment]
Hi guys,
is it okay to cast some variables to `any` to be able to access some private fields (ex. `_render`, `_tempDisplayObjectParent `, `_boundsID`)?

@bigtimebuddy @ivanpopelyshev @themoonrat

**Comment by bigtimebuddy** [comment]
Let's try to avoid the any casts. What's better is something like this so that we can maintain the internal properties in once place and we get the correct type.

```typescript
interface RendererInternals extends Renderer {
  _tempDisplayObjectParent: Container;
}
this.parent = (renderer as RendererInternals)._tempDisplayObjectParent;
```

**Comment by SerG-Y** [comment]
@bigtimebuddy it's not possible in this case because typescript doesn't allow to have the same property in one class private and public in another class/interface
image

**Comment by bigtimebuddy** [comment]
Then maybe don’t extend.

**Comment by ivanpopelyshev** [comment]
`_tempDisplayObjectParent` - just `as any` it, I'm gonna remove that object in another PR soon.

**Pull request merged**
