### PR TITLE
Added tint to DisplayObject that supports Container tinting - #2328

### PR DESCRIPTION
**Pull request by andrewstart**
Changed existing tint functionality to pull from the new worldTint so
that it respects the parent tint.

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
@GoodBoyDigital could you take a look at Andrew's PR and let us know what you think?

**Comment by ivanpopelyshev** [comment]
Ok guys, a interruption here: that kind of stuff needs to be separated into rendering context: all "world" variables have to be calculated into a component, otherwise it will get messy. I'm already having a lot of problems with "world" stuff in my fork

**Comment by GoodBoyDigital** [comment]
I had a really great thought about how we could implement this kind of functionality as a plugin.
A way that does not involve changing anything but adding the extra variables to a displayObject. Imagine pixi used a series of passes through the scene graph.

So the default pass is what we have - updates the transform + the alpha
We could add a new tint pass that would go through the scene graph and calculate the world tint of all the objects.
Further down the line we could add new passes for extra functionality
After all passes are complete we can then do the render pass.

What do you guys think?

**Comment by ivanpopelyshev** [comment]
even alpha logic is not that easy, filters and masks can break it. It needs to be separated from DisplayObject, in a component. And yes, different pass.

**Comment by ivanpopelyshev** [comment]
Proper way would be addign special RenderingContext component that takes care of "tint", "alpha", "renderable". Possible to add this component as second parameter to "renderWebGL" and "renderCanvas". That will allow many smart hacks and performance optimizations.

**Comment by bigtimebuddy** [comment]
@GoodBoyDigital Like your suggestion here.

**Comment by englercj** [comment]
Closing this since we will be redesigning how this works a bit in v5, and it probably wont make it in v4.

**Pull request closed without merging**
