### PR TITLE
there is no BLEND_MODES.NONE

### PR DESCRIPTION
**Pull request by staff0rd**
As seen [here](https://github.com/pixijs/pixi.js/blob/dev/packages/constants/src/index.js#L63-L83), there is no `BLEND_MODES.NONE`

### CODE REVIEW

**Comment by Dairnon** [comment]
Whats the use case for NONE? Isn't NORMAL basically no blendMode?

**Comment by bigtimebuddy** [comment]
Looks like @GoodBoyDigital had originally added that here e416a1ed318904b57731c0e9de5e98f59d3f6d67 and @ivanpopelyshev removed NONE here db0caa656e35b906b6bc8ca93aca07b1adc92b40

I think this is the result of a bad merge from dev -> next and we should re-add `NONE`, assuming it has some original intention. Maybe @GoodBoyDigital could elaborate what was the purpose?

**Comment by englercj** [comment]
> Whats the use case for NONE? Isn't NORMAL basically no blendMode?

None was no blending, normal is actual an Alpha blend.

**Comment by Dairnon** [comment]
@englercj So what would the standard use case of NONE be? Just rendering the entire image with no alpha?

**Comment by ivanpopelyshev** [comment]
Copy pixels instead of blending with blackground.

**Comment by bigtimebuddy** [comment]
Sounds like there's still some utility here. @staff0rd based on this conversation, could you re-add `NONE` to the list of blend modes?

**Comment by bigtimebuddy** [comment]
Thanks @staff0rd

**Pull request merged**
