### PR TITLE
Fixes noise filter (#3119)

### PR DESCRIPTION
**Pull request by YahorPadlucki**
Fixes [#3119](https://github.com/pixijs/pixi.js/issues/3119)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
I'm not sure this fixes the problem. Maybe @englercj or @GoodBoyDigital could weigh-in. While NoiseFilter in this PR does in-fact respect alpha, The rendering doesn't look quite right.

### Example

```js
const app = new PIXI.Application({
    backgroundColor: 0x006600,
    width: 200,
    height: 200
});
document.body.appendChild(app.view);
const graphic = new PIXI.Graphics()
    .beginFill(0xff0000)
  .drawCircle(100, 100, 50);
graphic.filters = [ new PIXI.filters.NoiseFilter() ];
app.stage.addChild(graphic);
```

### Current
screen shot 2017-04-16 at 9 10 39 am

### With This PR
screen shot 2017-04-16 at 9 11 17 am

**Comment by englercj** [comment]
The "with this PR" show is what I would expect with a noise filter. What makes you feel it is wrong?

**Comment by bigtimebuddy** [comment]
I would expect something similar to the current filter but maintaining alpha. This filter should be taking the pixels and applying a little darkness and a little lightness to each pixel not removing alpha from random pixels.

**Comment by englercj** [comment]
Opened an alternative fix if you'd like to check that one @bigtimebuddy.

**Comment by bigtimebuddy** [comment]
@YahorPadlucki Thanks a lot for your help here, but we are going to consider #3941 as better approach to this issue.

**Pull request closed without merging**
