### PR TITLE
Protect the initial state  of `this._activeRenderTarget` in _indexContext

### PR DESCRIPTION
**Pull request by finscn**
```
    this._activeRenderTarget = null;
    this._activeTextureLocation = 999;
    this._activeTexture = null;
````
must before `this._indexContext()` , otherwise  the _activeRenderTarget & _activeTexture init in  _indexContext will back to `null`.

### CODE REVIEW

**Comment by finscn** [comment]
@bigtimebuddy  @ivanpopelyshev  @englercj  @GoodBoyDigital  

This PR is very important.
 
Review as soon as possible , please .

 Thanks.

**Comment by bigtimebuddy** [comment]
@finscn Could you please explain what this change is and why it's important?

**Comment by finscn** [comment]
@bigtimebuddy  please forgive me for my bad english.  It's not important , it's just fix a serious bug.
The bug is serious , but is not usual.

In current PIXI ,   `_initContext()`  will set 
```
renderer. _activeRenderTarget = renderer.rootRenderTarget;
```

But, after `_initContext()` , the code
```
this._activeRenderTarget = null;
```
make the `_activeRenderTarget`  is back to `null`.

So , after  you `new WebGLRenderer()` , the `renderer._activeRenderTarget === null`, 
the  things that doing in `_initContext()`  are in vain.


And there will take a error when we first call  
```
renderer.clear()
```

example: 
```
var  renderer = new WebGLRenderer({
    clearBeforeRender : false
});


// I clear the canvas by myself.

tick()
{

    // do sth.

    renderer.clear();

    // do sth.

   renderer.render(stage);
}

```
When the game first call  `tick()` , there is an error.

**Comment by finscn** [comment]
This is a bug absolutely.

the current  logic in the constructor of  WebGLRenderer is : 
```
this. _activeRenderTarget = createDefaultActiveRenderTarget();

this. _activeRenderTarget = null;
```

The bug is  quite obvious.

**Comment by finscn** [comment]
Why does nobody care about this bug ?

**Comment by bigtimebuddy** [comment]
@finscn It's not that no one cares, it's because we all have day jobs. We are not paid to develop pixi.js so please have patience when someone cannot respond quickly enough.

**Comment by ivanpopelyshev** [comment]
@finscn I cared first :)

**Pull request merged**
