### PR TITLE
Account for scaling b/w sourceFrame → destinationFrame in ScissorSystem

### LINKED ISSUE #6866: ScissorSystem does not account for scale in sourceFrame → destinationFrame projection
https://github.com/pixijs/pixi.js/blob/857452aef9945307a5855765051feb2a0d45e30e/packages/core/src/mask/ScissorSystem.ts#L97

The scissor system account for different (x,y) coordinates between the source & destination frame; however, it doesn't do so for width/height. This means if the width/height of those rectangles are not equal, scissor masking will not work correctly.

### Possible Solution

```js
        const width = rect.width * resolution * destinationFrame.width / sourceFrame.width;
        const height = rect.height * resolution * destinationFrame.height / sourceFrame.height;
```

### PR DESCRIPTION
**Pull request by SukantPal**
Fixes #6866

-----
:pen: https://codepen.io/sukantpal/pen/mdPLvJG?editors=0010

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Example?

**Comment by SukantPal** [comment]
@bigtimebuddy https://codepen.io/sukantpal/pen/mdPLvJG?editors=0010!

**Comment by SukantPal** [comment]
A parallel issue I found was #6871. The pen makes sure to bypass it.

**Review by ivanpopelyshev — APPROVED** [review]

**Review by bigtimebuddy — APPROVED** [review]

**Review by GoodBoyDigital — APPROVED** [review]
nice!

**Pull request merged**
