### PR TITLE
Non developer readme contribution

### PR DESCRIPTION
**Pull request by GabrieleRomeo**
I have written a clear, easy-to-comprehend introduction for Pixi.js. 

**I believe this introduction, free of complex technical terms, will swiftly and thoroughly inform anyone about the use-cases, merit, and advantages, including the celebrated features, of Pixi.js.** 

Seasoned developers, new programmers, and even nontechnical visitors will benefit from the clear language, exposing Pixi.js to a broader range of users.

### CODE REVIEW

**Comment by englercj** [comment]
This is really cool @GabrieleRomeo, thanks for writting this up.

**Comment by GabrieleRomeo** [comment]
Thanks @englercj !
I hope that my little contribution will be used to improve your fantastic project :-) 
**For me, it would be very, very important!**

**Comment by englercj** [comment]
Its easier if you make PRs to the `dev` branch :)

**Comment by GabrieleRomeo** [comment]
Hi @englercj 
Do I need to make my changes on my `dev` branch and then create a new pull request?
I'm sorry but I'm a newbie with GitHub :smile: 
Thank you

**Pull request closed without merging**
