### PR TITLE
fix & refactor updateBatches logic

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
#5711 

Original Test: https://www.pixiplayground.com/#/edit/IVHxo3MM4vPZMZpn2VvPS

Verification: https://www.pixiplayground.com/#/edit/jh1VK3gUN~m2DusR2prgx

The problem is that it actually takes default `fillStyle` instead of our `lineStyle`. `fillStyle.visible=false`, so its not filling anything, but it doesn't take into account that `lineStyle` has `native` prop that we need later.

Of course just adding `currentNative` could fix that , but I really want to make the code readable.

I will also re-use the same approach in BatchRenderer later, to make customizable batch logic.

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Do you know why the native line shape is not closed?

**Comment by ivanpopelyshev** [comment]
I think it doesn't take into account `shape.closeStroke;`

**Comment by ivanpopelyshev** [comment]
OK, I fixed & refactored that too. It could go in another PR, but you insisted ;)

**Comment by ivanpopelyshev** [comment]
Graphics without style but with bounds: https://www.pixiplayground.com/#/edit/CZLJ66klqelKBLw7TnLoD

**Pull request merged**
