### PR TITLE
Fix `the fault after merge`

### PR DESCRIPTION
**Pull request by finscn**

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Wait a minute, how the heck "true" was there instead of false? I didn't do it!

**Comment by finscn** [comment]
@ivanpopelyshev  , I think it's a github's issue.

At first  , it  is `true`. (version 1 )
Then I  open this PR ,  it is still `true` (version 2)
Then Someone change `true` to `false` (version 3)

When merge my PR , the github can't merge correctly.

**Comment by finscn** [comment]
@ivanpopelyshev , I think github should report `conflict` , but it didn't.

**Comment by bigtimebuddy** [comment]
Either way, thanks for catching this @finscn

**Pull request merged**
