### PR TITLE
Trigger on tag push

### PR DESCRIPTION
**Pull request by cursedcoder**
So now it seems to be working properly.

I've tested with `git push --tags`.

Here is the result https://github.com/cursedcoder/pixi.js/actions/runs/149723902

See #6715

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
👏 thank you!

**Comment by bigtimebuddy** [comment]
image

Here’s from that link. Shouldn’t the Tag release have run? Instead of Non-Tag Branch?

**Comment by cursedcoder** [comment]
@bigtimebuddy sorry, I'm working on it, will require few changes to the steps

**Comment by cursedcoder** [comment]
@bigtimebuddy please check:

Tag pushed:
https://github.com/cursedcoder/pixi.js/runs/814136386?check_suite_focus=true

Branch pushed:
https://github.com/cursedcoder/pixi.js/runs/814136124?check_suite_focus=true

**Comment by bigtimebuddy** [comment]
Awesome. Nice work

**Pull request merged**
