### PR TITLE
Fix for #1950

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
I tested it on my https://github.com/ivanpopelyshev/railways and didnt notice differences, it still sucks. Regardless of my tests, this expression is just wrong.

### CODE REVIEW

**Comment by GoodBoyDigital** [comment]
thanks for the correction @ivanpopelyshev :+1:

**Comment by ivanpopelyshev** [comment]
@GoodBoyDigital Hey Matt! 

Can you please look at [this thread](http://www.html5gamedevs.com/topic/18480-pixi-spine-plugin-wip-gpu-patch/) at html5 forums? 
[issue at pixi-spine.js](https://github.com/pixijs/pixi-spine/issues/66)

No one wants to help me with code review on that patch, and I think its huge advantage for pixi.

**Comment by GoodBoyDigital** [comment]
I 100% agree! This is an amazing feature. How can we help?

**Comment by ivanpopelyshev** [comment]
@GoodBoyDigital I just need a consultation. Look at my last post at [issue at pixi-spine.js](https://github.com/pixijs/pixi-spine/issues/66) . If I merge that thing into pixi-spine, you'll be able to mention it at pixijs.com . So far that's the only open-source spine runtime which uses special shader.

**Comment by GoodBoyDigital** [comment]
Cool, I will check it out this week. If its stable though I would definitely merge it in. Also once it is, let me know and we can make sure the world knows! (We can do a guest blog post even!)

**Pull request merged**
