### PR TITLE
Convert Extract to TypeScript

### PR DESCRIPTION
**Pull request by Zyie**
##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included
- [ ] Documentation is changed or added
- [ ] Lint process passed (`npm run lint`)
- [ ] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Do you think it makes sense to create a IRendererPlugin interface that Extract, Prepare, etc that they can all implement? This would basically just take renderer as a single constructor argument. Not sure if there are any other methods called by Renderer. I like hardening plugin types for users to implement to.

**Comment by Zyie** [comment]
> Do you think it makes sense to create a IRendererPlugin interface that Extract, Prepare, etc that they can all implement? This would basically just take renderer as a single constructor argument. Not sure if there are any other methods called by Renderer. I like hardening plugin types for users to implement to.

I didn't think it was possible to implement an interface that defines a constructor? Could you point to an example for me.

We could create a base class that plugins extend from if an interface doesn't work?

**Comment by bigtimebuddy** [comment]
Would probably look something like this:

```typescript
interface IRendererPluginConstructor {
  new (renderer: Renderer): IRendererPlugin;
}

interface IRendererPlugin {
  destroy(): void;
}
```
So the Renderer [here](https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/Renderer.ts#L491) would be:
```
registerPlugin(static registerPlugin(pluginName: string, ctor: IRendererPluginConstructor): void
```

**Comment by bigtimebuddy** [comment]
Is this good to go, @Zyie? Was there something else you wanted to do?

**Comment by Zyie** [comment]
> Is this good to go, @Zyie? Was there something else you wanted to do?

Sorry got super busy last week. Just updated this to add the `IRendererPlugin` like you suggested.

So this is now good to go

**Pull request merged**
