### PR TITLE
Fix Cannot read property 'disposeGeometry' of undefined (#5929)

### PR DESCRIPTION
**Pull request by mudcube**
##### Description of change
Loop through runner items backwards, in case one of the items removes itself from the array.

https://www.pixiplayground.com/#/edit/yjTOm9m7zJN0XMYWMVTCv

##### Pre-Merge Checklist

- [x] Lint process passed (`npm run lint`)
- [ ] Tests passed (`npm run test`)

##### Note
Just realizing that I unfortunately cannot run `npm run test` due to a [separate issue](https://github.com/pixijs/pixi.js/issues/5931) which happens from a clean install on my machine with the latest master.

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Please make an example for disposeGeometry, thats my method and k thought i've taken into account that thing

**Comment by ivanpopelyshev** [comment]
Did you achieve that with two renderers?

**Comment by ivanpopelyshev** [comment]
Oh, right, here it is: 

https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/geometry/Geometry.js#L277
https://github.com/pixijs/pixi.js/blob/dev/packages/core/src/geometry/GeometrySystem.js#L464

Runners dont have , maybe mini-signals will be better in that case. 
@GoodBoyDigital 
@englercj

**Comment by ivanpopelyshev** [comment]
Demo: https://www.pixiplayground.com/#/edit/0fUXKi8LVTJBLB5JOC~JB

**Comment by mudcube** [comment]
> Did you achieve that with two renderers?

Yup, exactly.

> My idea is either we add option to reverse ticker order, either we use signal.

My only concern with reverse order is how it might affect things... that's to say, is anything expecting things to be fired in a certain way?

A third option might be to clone the `const items = [...ref.items]` before looping through it. But that might create necessary garbage?

**Comment by bigtimebuddy** [comment]
We need unit test coverage to reflect this change.

**Comment by GoodBoyDigital** [comment]
Hello! Figured it might actually be quite handy to be able to remove something mid run. This situation is a great example of that! 

https://github.com/pixijs/pixi.js/pull/5972

**Comment by bigtimebuddy** [comment]
Closing this in favor of #5972 or #5975

**Pull request closed without merging**
