### PR TITLE
Fix Texture leak with SpritesheetLoader

### LINKED ISSUE #6506: SpriteSheet.destroy(true) does not delete entries from TextureCache
Spritesheet.destroy(true) does not remove all items from the TextureCache.  To reproduce 

```typescript
const app = new Application({
        width: 640,
        height: 480,
        backgroundColor: 0x000000});

Loader.shared.add('assets/spritesheet-png8.json').load(setup);

function setup() {
   const sheet = Loader.shared.resources['assets/spritesheet-png8.json'].spritesheet;
   sheet.destroy(true);
   console.log(utils.TextureCache);
}
```

A potential workaround, for now, is to remove the elements from the cache directly.  

Use the resources from the following [repository](https://github.com/CodeAndWeb/pixijs-sprite-sheets/tree/master/images)

### PR DESCRIPTION
**Pull request by bigtimebuddy**
Fixes #6506

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Is it about TextureCache?

**Comment by bigtimebuddy** [comment]
No problem with TextureCache. The problem is we ignore (but don’t destroy) the Texture created by the TextureLoader—Spritesheet only uses the BaseTexture.

**Comment by ivanpopelyshev** [comment]
Maybe make a test to check if texture remains in TextureCache after spritesheet destroy? I suggest to clean all texture cache before executing it

**Comment by bigtimebuddy** [comment]
I already added a test check for this. You looking for something else?

**Comment by ivanpopelyshev** [comment]
Oh , right. OK, its fine then

**Pull request merged**
