### PR TITLE
Fixes issue #2932 trimmed spritesheet

### PR DESCRIPTION
**Pull request by Yennick**
This looks like it is the fix. Couldn't find any tests for loaders..

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
PR must be done in DEV branch, not master. Sorry, that's one of our project quirks :) Also what exactly did you fix? Trimmed stuff works just fine, even if rotated

**Comment by Yennick** [comment]
The pull request fixes trimmed spritesheets issue #2932 which look distorted when it's a movieClip and move around in a way they shouldn't. gif coming up..

**Comment by Yennick** [comment]
This is the way it should look like (pixi v3)
windmill_correct

And this is the way it looks right now (pixi v4)
windmill_wrong

**Comment by ivanpopelyshev** [comment]
I did change logic of trim in v4, and I modified that place accordingly. Can you show me your json file?

**Comment by Yennick** [comment]
Truncated the file (attached the whole json file at bottom)
```
{"frames": {

"windmill_shape0000":
{
	"frame": {"x":2,"y":2,"w":40,"h":64},
	"rotated": false,
	"trimmed": true,
	"spriteSourceSize": {"x":2,"y":10,"w":45,"h":74},
	"sourceSize": {"w":45,"h":74}
},
"windmill_shape0001":
{
	"frame": {"x":44,"y":2,"w":39,"h":67},
	"rotated": false,
	"trimmed": true,
	"spriteSourceSize": {"x":5,"y":7,"w":45,"h":74},
	"sourceSize": {"w":45,"h":74}
},
"windmill_shape0002":
{
	"frame": {"x":85,"y":2,"w":37,"h":70},
	"rotated": false,
	"trimmed": true,
	"spriteSourceSize": {"x":8,"y":4,"w":45,"h":74},
	"sourceSize": {"w":45,"h":74}
}},
"meta": {
	"app": "Adobe Flash Professional",
	"version": "15.0.1.179",
	"image": "windmill.png",
	"format": "RGBA8888",
	"size": {"w":256,"h":512},
	"scale": "1"
}
}
```

[windmill.txt](https://github.com/pixijs/pixi.js/files/550331/windmill.txt)

**Comment by ivanpopelyshev** [comment]
Yeah, I did it wrong. I still dont understand different between spriteSize and spriteSourceSize widht and height.

**Comment by GoodBoyDigital** [comment]
good stuff! 👍

**Pull request merged**
