### PR TITLE
Fix svg

### PR DESCRIPTION
**Pull request by ChinnJung**
##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included
- [ ] Documentation is changed or added
- [ ] Lint process passed (`npm run lint`)
- [ ] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by englercj** [comment]
Can you describe what the issue you are fixing is?

**Comment by ivanpopelyshev** [comment]
We dont handle errors there. Lets ask @JetLua :)

**Comment by JetLua** [comment]
In https://github.com/pixijs/pixi.js/pull/5697  I removed the error monitor. 

It's okay to add it back, but this PR is out of date and should be updated from [pixi.js:dev](https://github.com/pixijs/pixi.js/tree/dev).

**Comment by bigtimebuddy** [comment]
Agree with @JetLua. This change doesn't reflect the latest in *dev*. In fact, change to handle image load is already added. Closing.

**Pull request closed without merging**
