### PR TITLE
added check for root

### LINKED ISSUE #3505: Problem with render when cacheAsBitmap and mask is used together
If inside container is element, which have set mask on it and this element position is not 0,0, then this element will be not rendered if we set '**cacheAsBitmap**' to true on the container wherein the element is located.

Link to example: http://codepen.io/kiture/pen/bByGKg

If we remove this line: 
_container.cacheAsBitmap = true;_
Then all works correctly.

### PR DESCRIPTION
**Pull request by GoodBoyDigital**
fixes #3505

### CODE REVIEW

**Comment by GoodBoyDigital** [comment]
Thanks for the feedback dude! Not sure what problem you are solving here? The root property changes depending on if you are rendering to a frameBuffer or not?

**Comment by ivanpopelyshev** [comment]
No, the thing is cacheAsBitmap and masking are changing renderTarget.transform but scissor doesn't know about that. As a result I have to use a shift somewhere:

```js
shift.x = Math.round((projectionMatrix.tx + 1) / 2 * rt.sourceFrame.width);
shift.y = Math.round((projectionMatrix.ty + 1) / 2 * rt.sourceFrame.height);
```

**Comment by GoodBoyDigital** [comment]
ScissorMasking is disabled on anything other than root, Mainly as renderTargets use scissor rects to crop where they render too. With that in mind the shift should not be required? 

This issue should not have anything todo with coordinates but more when to use fastRect? Maybe what you mention is a separate issue from this?

**Comment by ivanpopelyshev** [comment]
May be its separate, but I'd like to make a fix for it later. Add "enableScissor" to renderTarget please.

**Comment by GoodBoyDigital** [comment]
Until we have a new fix I believe this PR is good to go. Adding extra variables for PRs that will happen later seems a little redundant?

If you want to make a new PR later down the line that would be ace. Then at that point we can add the extra variables and refactor as necessary.

**Comment by GoodBoyDigital** [comment]
Does this PR break your existing code?

**Comment by ivanpopelyshev** [comment]
Please make a commentary in the code about it and I'll approve it.

**Comment by GoodBoyDigital** [comment]
righto skippy! @ivanpopelyshev note added, you happy to roll this one in? 👍

**Pull request merged**
