### PR TITLE
Add JSDoc comments on PIXI.Transform

### PR DESCRIPTION
**Pull request by mofnire**
##### Description of change

This PR adds JSDoc comments on `PIXI.Transform` properties and improves the PixiJS type declaration file. I intentionally changed the visibilities of the methods `onChange` and `updateSkew` from `@private` to `@protected`. I thought it is a good thing to allow developers to override them when needed. But if it isn't, I will revert them.

##### Pre-Merge Checklist

- [x] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)

### CODE REVIEW

**Comment by mofnire** [comment]
> Also I'd like to point out that (cx, sx) is normalized first column of matrix, coordinates of normalized local X axis in parent space. Same about (cy, sy)

Thank you for clarifying. I thought long about their good explanations / technical terms. "X-coordinate value of normalized local X axis" sounds good.

**Comment by ivanpopelyshev** [comment]
We can put the same desc in both _cx and _cy:

> `(_cx,_sx)` is normalized local X axis, first column of local matrix without scale.

> `(_cy,_sy)` is normalized local Y axis, second column of local matrix without scale.

I leave it to you.

**Comment by bigtimebuddy** [comment]
@ivanpopelyshev, why should all the members be protected?

**Comment by ivanpopelyshev** [comment]
That way i can write functions like this: https://github.com/pixijs/pixi-projection/blob/master/src/base/LinearProjection.ts#L2

**Comment by ivanpopelyshev** [comment]
Also, those are not global unique ID's , they are  unique only inside the instance. We can say that they are incremented. and `_worldID`  is read by others , while `_parentID` points to `_worldID` of parent that we already used for calculation. I don't know how to spell that.

**Comment by mofnire** [comment]
I revised descriptions as per review comments.

**Pull request merged**
