### PR TITLE
Making the rect param of the getLocalBounds methods of the Spirte and TilingSprite classes optional, using the same approach as in the DisplayObject class.

### PR DESCRIPTION
**Pull request by flashist**
##### Pre-Merge Checklist

- [x] Tests and/or benchmarks are included
- [x] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
The optional rect makes sense, but the other change I don't understand. What are you fixing by moving the `if (!rect){}`? Can you show a bug or make a test for this?

**Comment by flashist** [comment]
Thanks for the feedback. I changed the code, left only the changes, which made the rect param optional in the API and added a test for Spirte.getLocalBounds

My original idea was to keep code-approach the same, getting the DisplayObject class as an example. But after your feedback I found out that actually the same checking would be done in the DisplayObject class, if no rect is passed.

**Review by ivanpopelyshev — APPROVED** [review]
That is definitely a bug in our API, thank you!

**Comment by flashist** [comment]
@ivanpopelyshev , @bigtimebuddy , thanks a lot! Looking forward to see the changes merged into the official dev branch.

**Comment by bigtimebuddy** [comment]
Thanks for the contribution @flashist. If you see more issues, PRs always welcome!

**Pull request merged**
