### PR TITLE
implemented event bubbling

### PR DESCRIPTION
**Pull request by akbr**
See #2342.

### CODE REVIEW

**Comment by gurmukhp** [comment]
Would it be possible to see an example of this working? I've tried this approach but the event.target value is always the parent DisplayObject and not the children, although looking in event.children[1], I can see the one that I clicked.

A working example would be great, thanks!

**Comment by akbr** [comment]
Hello @gurmukhp! Here is an example for you: http://jsbin.com/noboliqamo/1/edit?html,js,console,output

Click events show up in the console.

Let me know if this helps!

**Comment by akbr** [comment]
Ok, I think I see your issue.

My example works great _unless_ the outer Pixi container is set as interactive. If it is, it prevents its children from hearing the click.

I'll see if I can find time to take a closer look soon.

**Comment by gurmukhp** [comment]
Thank you! That's really useful! Do you know if event bubbling from within a Pixi Canvas brings any performance benefit? 

In the HTML world the more events bound, the slower it can be, do you know if this also applies to Pixi?

**Comment by englercj** [comment]
@gurmukhp It will of course be slower, it will have to emit events many more times than before.
.

**Comment by gurmukhp** [comment]
Thanks, so to confirm, we should try to limit the number of event listeners possible.

Any idea when this will make it to the public release?

**Comment by englercj** [comment]
> Thanks, so to confirm, we should try to limit the number of event listeners possible.

@gurmukhp No, if an event happens it will emit from the target through all the parents. It doesn't matter how many listeners you add. Aside from the overhead of actually calling your callbacks, there isn't any significant difference between 10 listeners and 100. It still walks the same number of nodes, and emits the same number of events.

**Comment by akbr** [comment]
Yep: Any performance penalty would come from deeply-nested targets bubbling through lots of parents, _not_ the volume of interactive targets. (If you want to use event bubbling in a deep scene graph, you can use `stopPropagation` to mitigate this.)

I use event bubbling not for performance reasons, but because it can help me write cleaner code. In some cases, I think it's best to separate event logic from individual sprites.

> Any idea when this will make it to the public release?

This doesn't seem to be a high priority issue. (I might be the only one who really cares!)

Given the potential performance implications, and the fact most Pixi devs don't seem to use bubbling, I'm wondering if bubbling should ultimately be implemented as an optional toggle (defaulting to "off").

**Comment by bigtimebuddy** [comment]
@akbr Where there is clear trade-off for performance v. usability, having an opt-in toggle for usability is probably a better approach.

**Comment by endel** [comment]
About performance, I don't think this would be an overhead for any PIXI application. Some benchmarks would be necessary to confirm exactly how much time it would consume having to bubble in a long display list.

**Comment by akbr** [comment]
I'm closing this in light of https://github.com/pixijs/pixi.js/pull/2658, which adds global events to the `InteractionManager`. As @andrewstart notes, global events allow for "some of the use cases of event bubbling without the performance hit of deep display lists." (:beers:)

If there is a desire for "proper" event bubbling -- which should probably be opt-in, as discussed above -- someone else can pick this up.

**Pull request closed without merging**
