### PR TITLE
ViewableBuffer: Uint32View and Float32View dont need getters

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
Subj. I just dont know cases that dont use one or both of them.

Pushing colors or something else in uint8 or int8 can happen but its rare.

Also Uint32 had wrong jsdoc type.

### CODE REVIEW

**Comment by SukantPal** [comment]
The getters were there so that `ViewableBuffer` could be used as a generic buffer. You might not want to use all the views. So, why initialize all of them.

You are initializing the `uint32` and `float32` in the constructor. If we use this somewhere else than in batch, it would be wasting memory and we would be allocating for no reason (unless those views were going to be used).

**Comment by SukantPal** [comment]
Let us see what @bigtimebuddy says. 

I don't have a problem though. It is just that it breaks the uniformity of the code.

**Comment by SukantPal** [comment]
You also have to fix `destroy()`, then.

**Comment by bigtimebuddy** [comment]
Sorry Ivan, I don't understand this change. Seems superficial and there's no real benefit. In fact, I prefer the readonly getters instead of members.

**Comment by SukantPal** [comment]
@bigtimebuddy, kind of agree.

**Comment by ivanpopelyshev** [comment]
> Sorry Ivan, I don't understand this change. Seems superficial and there's no obvious benefit. In fact, I prefer the readonly getters instead of members.

It will make me calm that the class works like before, without extra getters. `packGeometry` didnt have any getter calls before we started the refactoring. I do not know about all that deoptimization stuff and how to detect it, but I prefer things to stay the same just in case. 

Typed arrays backed by ArrayBuffer consume only a handful of memory. I cant explain my sense of balance, but I really dont like it that we just changed stuff and now suddenly its canonical.

**Comment by SukantPal** [comment]
There is no reason to the set the view. It will work like the same as before.

I don't think anyone would want to set the uint32View to a different value.

**Comment by ivanpopelyshev** [comment]
I'm afraid of getters.

**Comment by bigtimebuddy** [comment]
Is accessing these members "hot" code? If that's the case, let's measure the impact of getters so we understand the underlying issue. Also if you're going to add something that is seemingly anti-pattern in the code, you should make an inline comment about this being a performance optimization.

**Comment by ivanpopelyshev** [comment]
> Also if you're going to add something that is seemingly anti-pattern in the code, you should make an inline comment about this being a performance optimization.

It was like that before last PR, I just noticed it too late. I want to stay it that way before someone who knows how to look at deoptimizations looks at it.

I asked @englercj to explain me those things before but i didnt get good answer from him.

**Comment by ivanpopelyshev** [comment]
> This will cause a memory leak if left unchanged.

`destroy()` functions are also our paranoia, its actually the same level as "ivan doesn't like getters in critical code" :) I know js memory model enough to be sure that if we dont nullify all those small links in our destroys - nothing bad will happen. 

Event "in case pixijs will be ported to native C++ code" has very small probability.

I usually maintain `destroy()` methods just for other people to be calm, so please accept this change because it makes me calm.

Yeah, we can tag this PR with "paranoia" label, if we introduce one :) We already have X-Files.

**Comment by ivanpopelyshev** [comment]
Another minor thing is that i dont want to fall into those functions while debugging flush and packGeometry step by step :) yeah, its all minor, just let me have this status quo for two fields please.

**Comment by SukantPal** [comment]
I forgot I'm not writing C++. I agree. We could merge this if @bigtimebuddy agrees.

As far as "hot code" is concerned, I don't think time in JavaScript is much spent. Also, we are essentially caching the views in packInterleavedGeometry,

```
const { uint32View, float32View } = attributeBuffer;
```

**Comment by SukantPal** [comment]
Be brave of getters, they're safe :P

**Comment by ivanpopelyshev** [comment]
I took a big corporate holiday, I didnt just abandon this thing :)

**Comment by englercj** [comment]
I know I'm late but for what it is worth I'm ambivalent about this change. I don't think the complexity of the getters justify the memory savings, and I don't think the property vs getter performance difference is big enough for us to care on modern engines.

The destroy methods are important because they notify systems to drop references they would otherwise keep. We don't need to do the "null out all members" thing anymore, but we do need to have destroy so the system can drop references we otherwise wouldn't know to drop.

**Pull request merged**
