### PR TITLE
Adds Containers events for addedTo and removedFrom

### PR DESCRIPTION
**Pull request by davidfig**
##### Description of change
Pull request for #5471 

DisplayObject has the 'added' and 'removed' events. It would be helpful if Container included events for 'addedTo' and 'removedFrom' (or something along those lines) for when the container's children change. the Container.onChildrenChange() overridable is not ideal since it doesn't say what was added or removed.

##### Pre-Merge Checklist

- [didn't add tests] Tests and/or benchmarks are included
- [X] Documentation is changed or added
- [X] Lint process passed (`npm run lint`)
- [? (I had issue with npm test -- it wouldn't complete but didn't list any errors] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Thank you @davidfig! I think it's important that we add some basic tests here so we don't break these events in the future. Do you need help with that?

**Comment by davidfig** [comment]
I added the tests for these events.

**Comment by bigtimebuddy** [comment]
@davidfig, could you please remove package-lock.json?

**Comment by davidfig** [comment]
Removed.

**Comment by bigtimebuddy** [comment]
Oops, sorry I wasn't clearer. You actually should just revert it to the one that's in the dev branch. You should actually delete. We need that file, but different versions of npm make small subtle changes to that file that we don't want as part of this PR.

**Comment by davidfig** [comment]
:smile: Okay, it's back to the current one.

**Comment by davidfig** [comment]
Good suggestion. I renamed the events to childAdded and childRemoved, and added the index to the events. Tests are also updated.

**Comment by bigtimebuddy** [comment]
Nice one. Thanks @davidfig for reacting to our feedback so quickly.

**Pull request merged**
