### PR TITLE
Consistent Canvas State after render()

### PR DESCRIPTION
**Pull request by cawoodm**
Save and Restore canvas state so transform, style changes etc aren't propagated outside of render()

### CODE REVIEW

**Comment by themoonrat** [comment]
Couple of issues there linting wise (npm run lint... pixi is very strict with it's linting rules... can be a pain but it does maintain consistent standards!)

/home/travis/build/pixijs/pixi.js/src/core/renderers/canvas/CanvasRenderer.js
  203:9  warning  'setTransform' is not defined  no-undef
  231:1  warning  Trailing spaces not allowed    no-trailing-spaces

Also, wouldn't the ctx.restore() go AFTER the ```displayObject.renderCanvas(this);``` call? @ivanpopelyshev ?

**Comment by ivanpopelyshev** [comment]
@themoonrat I agree with the changes, if he makes it through lint :)

@cawoodm run "npm run build" locally to see if lint breaks, or run "npm run test" to ensure that its at least working.

**Comment by cawoodm** [comment]
All I did was add 2 lines here on github directly. I did not clone the repo nor do I know how to build it.

**Comment by bigtimebuddy** [comment]
@cawoodm Could you fix this PR based on the notes above or close it and ask @ivanpopelyshev to do it?

**Comment by cawoodm** [comment]
Is it OK now?

**Comment by ivanpopelyshev** [comment]
Never mind, made separate PR with "context.setTransform". Thank you, you'll name will appear in next pixi release :)

**Comment by ivanpopelyshev** [comment]
you removed "context" from setTransform and "npm run test" was failing because of that.

**Comment by cawoodm** [comment]
Oh my! <insert embarrassed emoticon here>

**Pull request closed without merging**
