### PR TITLE
Adds factory for creating custom BatchRenderer plugins

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
This feature is required by multiple plugins.

Demo will follow.

Need help with names and structure of the API.

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Demo: https://www.pixiplayground.com/#/edit/gyEI8Qi6~ii7hMwCTUO7k

**Comment by GoodBoyDigital** [comment]
I think you are really on to something here dude! API does need a little work, but the principles are spot on!

**Comment by bigtimebuddy** [comment]
This is basically currently your implementation from the demo. This feels overly burdensome. It requires that the dev knows about `BatchShaderGen`, `BatchRenderer`, `shaderGen` property and how they all fit together.

```js
const myShaderGen = new PIXI.BatchShaderGen(undefined,
`
varying vec2 vTextureCoord;
varying vec4 vColor;
varying float vTextureId;
uniform sampler2D uSamplers[%count%];

void main(void){
    vec4 color;
    %forloop%
    gl_FragColor = vColor * vec4(color.a - color.rgb, color.a);
}
`);

class MyBatch extends PIXI.BatchRenderer {
    constructor(renderer) {
        super(renderer);
        this.shaderGen = myShaderGen;
    }
}

PIXI.Renderer.registerPlugin('invert', MyBatch);
const sprite = new PIXI.Sprite();
sprite.pluginName = 'invert';
```

Maybe we could create a Factory method or class that generates the new BatchRenderer, like this. Then devs essentially only need to know about a single new API.

```js
const vertex = undefined;
const fragment = `
varying vec2 vTextureCoord;
varying vec4 vColor;
varying float vTextureId;
uniform sampler2D uSamplers[%count%];

void main(void){
    vec4 color;
    %forloop%
    gl_FragColor = vColor * vec4(color.a - color.rgb, color.a);
}
`;

PIXI.Renderer.registerPlugin('invert', PIXI.BatchRendererFactory.create(vertex, fragment));
const sprite = new PIXI.Sprite();
sprite.pluginName = 'invert';
```

**Comment by ivanpopelyshev** [comment]
Yes, that'll be better for basic usage. For advanced, we still need to re-declare shaderGen in BatchRenderer constructor.

**Comment by bigtimebuddy** [comment]
Also, I'd love to see the more verbose "Generator", not shorting to "Gen". PixiJS typically only abbreviates API names if it's common usage ("gl", "uvs", etc). I don't think "Gen" is a commonly understood shortening.

**Comment by bigtimebuddy** [comment]
@ivanpopelyshev how do you want to proceed with this? Do you want me to take a pass?

**Comment by ivanpopelyshev** [comment]
Yes, because im on vacation and my time online is limited by my fun :)

**Comment by bigtimebuddy** [comment]
Here's a fork of your example with the new API. https://www.pixiplayground.com/#/edit/QYx55VopCd0rNFnc_gTYl

* Was toying with `BatchRendererFactory` vs `BatchPluginFactory`? Not bullish on either.
* Can `BatchShaderGenerator` be private now?

**Comment by ivanpopelyshev** [comment]
1. I think BatchPluginFactory is better.
2. It has to be publish, because we can generate better stuff than that. For example, two textures per sprite. Texture dimensions supplied in uniforms.

**Comment by GoodBoyDigital** [comment]
ability to pass in uniforms would be ace too!

**Comment by bigtimebuddy** [comment]
@GoodBoyDigital You mean these uniforms?

```js
        const uniforms = {
            tint: new Float32Array([1, 1, 1, 1]),
            translationMatrix: new Matrix(),
            default: this.defaultGroupCache[maxTextures],
        };

        return new Shader(this.programCache[maxTextures], uniforms);
```

**Comment by ivanpopelyshev** [comment]
I have `customUniforms` in my plugins. If several sprites have same group of uniforms, they are batched.

https://github.com/pixijs/pixi-projection/blob/master/src/curve/SpriteBilinearRenderer.ts#L124

You think its worth adding in next PR for next version? :)

**Comment by GoodBoyDigital** [comment]
thats right! so you could for example set up new uniforms in the fragment source:

```
const uniforms = {extraColor:[1,0,0,1]};

const options = {fragment, uniforms};

BatchRendererFactory.create(options);

```
const uniforms = {
            tint: new Float32Array([1, 1, 1, 1]),
            translationMatrix: new Matrix(),
            default: this.defaultGroupCache[maxTextures],
            customUniforms: UniformGroup.from(uniforms);
        };
```

**Comment by ivanpopelyshev** [comment]
Lets do it in next version? :) I'm not sure about uniforms API yet.

**Comment by bigtimebuddy** [comment]
I tend to agree with @ivanpopelyshev, I think we could do a follow-up for uniforms. Doesn't change the overall approach here. Do you have some specific ideas how devs might use this feature @GoodBoyDigital?

**Pull request merged**
