### PR TITLE
Children outside of hitArea cannot be hit

### PR DESCRIPTION
**Pull request by themoonrat**
Fixes https://github.com/pixijs/pixi.js/issues/4564

Unit tests to cover this new case added (some interaction unit tests were within graphics; I've moved these into the interaction manager)

Example on 4.6.2: http://jsfiddle.net/themoonrat/fjo9aeew/1/
Example with fix: http://jsfiddle.net/themoonrat/fjo9aeew/2/

Note on 4.6.2, you see the hand appear if you follow the circles outside of the box on the bottom right corner. A console log is also output when a circle is hovered over. This no longer occurs with the fix

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
I'm looking at it.

**Comment by ivanpopelyshev** [comment]
I thought that mask can work without hitArea.

**Comment by themoonrat** [comment]
http://jsfiddle.net/9tm62nx5/

**Comment by st3v0** [comment]
@themoonrat This change has broken all my buttons which use hitArea. 

If i rolled over a button and then moved the mouse off to the left the out events would not fire. However If i move off to the right then they would work fine.

I've rolled back to the 4.6.2 release and everything is working fine again.

**Comment by st3v0** [comment]
The Example below will turn red when you roll over the box and white when not.
https://codepen.io/st3v0/pen/WdqrXX

I did notice a couple things:
- If i use Graphics instead of Sprite or Container it seems to work fine.
- The hit area is also affected by the anchor position. If you uncomment the `test.anchor.set` line you'll see that the hit area now starts halfway through the box, even though the hit area x,y to 0,0

**Comment by themoonrat** [comment]
Cheers for the example, I'll take a look today. Our unit tests only cover checking hitArea with graphics, which is an oversight on our part

**Comment by ivanpopelyshev** [comment]
hitArea is affected only by transform (position, scale, pivot, e.t.c.). If you use anchor to move the image, you have to adjust its hitArea too.

**Comment by ivanpopelyshev** [comment]
In the fiddle, you change width/height of sprite, thus you change its `scale`, and it affects hitArea. Local coords (0,0,100, 100) become global (100, 0, 1000, 1000)

**Comment by themoonrat** [comment]
Also, I'm trying this in 4.6.2 and I'm getting the same behaviour

**Comment by qtiki** [comment]
This has introduced a breaking change in 4.7. In version 4.6.2 it was possible to create complex hierarchies of hit-areas. Now the hit-check early-exits if the point is not inside the parent. This is not consistent with what the user sees. In my opinion if a button is visible, it should also be clickable. I modified the example to demonstrate this: https://codepen.io/anon/pen/vRyMON

In 4.6.2 the whole white area is hittable, whereas in 4.7 only the top-left rectangle is.

**Comment by ivanpopelyshev** [comment]
override containsPoint and not hitArea, then it'll work.

**Comment by qtiki** [comment]
@ivanpopelyshev Do you mean I should override containsPoint in my example or that the pull request code should be modified to use containsPoint instead of hitArea? I'm just wondering whether this is considered a bug in PIXI or "as designed" - which is why I commented here instead of just opening a new issue.

**Comment by ivanpopelyshev** [comment]
@qtiki you should use containsPoint . if you have a shape inside, you can just do

```js
element.containsPoint = function(p) {
return shape.contains(p.x, p.y)`
}
```

**Comment by Hyperkettu** [comment]
@ivanpopelyshev How do you put that shape inside an element so that it maintains its transform hierarchy? Moreover, if I have a container hierarchy that has also sprites as children (buttons), how does that containsPoint method work since containers don't have containsPoint function? Is there any way?

**Comment by ivanpopelyshev** [comment]
`p` here is a point in local coordinates, already reverse transformed.

**Pull request merged**
