### PR TITLE
Replace native Array.splice with manual removeItems

### PR DESCRIPTION
**Pull request by adelciotto**
Added a ```removeItems``` function to the ```utils``` module to replace the native Array.splice for removing array items.  Unit tests also added.

Related to #2205. This PR adds the ability to remove multiple items.

### CODE REVIEW

**Comment by englercj** [comment]
:+1: This is really awesome, thanks @adelciotto and @mreinstein for putting these together. Great addition to the lib.

@GoodBoyDigital Want you to take a look at this before I merge.

**Comment by mreinstein** [comment]
@adelciotto thanks for doing the leg work and seeing this through. Really nice job! :+1:

**Comment by GoodBoyDigital** [comment]
Open source spirit at its finest! This PR looks great to me. I love thease kind of optimisations thanks for taking the time to add them to pixi. 

@englercj lets roll this in!

**Comment by mudcube** [comment]
I ran across this solution while optimizing arrays, it appears although this is faster in Firefox, it's slower in Chrome/Safari/Opera and IE - http://jsperf.com/removeitems

**Pull request merged**
