### PR TITLE
Fix: Clear full texture in filter system

### LINKED ISSUE #7063: Blur Filter bug in 5.4.0-rc.3
Noticing an odd issue with 5.4.0-rc.3. The blur filter appears to be bleeding (this did not happen in 5.3.3 running the same code). 

Here are my blur settings:
blur = new PIXI.filters.BlurFilter();
blur.blur = 0.75;
blur.resolution = 2;
blur.quality = 8;

Included below are two screenshots that demonstrate the issue (top is 5.3.3, bottom is 5.4.0-rc3):

image

image

...note the bits of bleed that show up sporadically. I'm testing on MacOS 10.13.6 w the latest Firefox, Chrome, Safari, and Edge browsers. I'm rendering in WebGL (have not tested canvas fallback as yet - but critical for this to work in WebGL).

### PR DESCRIPTION
**Pull request by SukantPal**
Fixes #7063. See #7073 for explanation of why this will work.

##### Description of change

Clear whole filter texture in filter system.

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Still seeing the bleeds, although it's a little better.

**dev branch**
https://jsfiddle.net/bigtimebuddy/fok60qrv/

**this PR**
https://jsfiddle.net/bigtimebuddy/8q0z6dyt/

**Review by ivanpopelyshev — APPROVED** [review]

**Comment by ivanpopelyshev** [comment]
Gonna check whats wrong with this one.

**Review by ivanpopelyshev — CHANGES_REQUESTED** [review]
gonna check why bleeds are persisting

**Comment by SukantPal** [comment]
> gonna check why bleeds are persisting

I know the problem now. But it's super annoying your requesting changes on nothing even though this is a draft.

**Comment by SukantPal** [comment]
@bigtimebuddy @ivanpopelyshev Recheck, it should be fixed now.

**Review by bigtimebuddy — APPROVED** [review]
This works for me.

**Review by ivanpopelyshev — APPROVED** [review]

**Pull request merged**
