### PR TITLE
Bounds builder. Fixes all abnormal bounds behaviours. Tested.

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
Everything is taken into account. Almost all bounds calculation (except Graphics) are moved into separated file, which can be changed if we enchance our Transforms in some way.

Tests in examples:

See local width and height, global width and height at the same time. When rotation=0 or 180 they will be the same. #2623

```js
var renderer = PIXI.autoDetectRenderer(800, 600);
document.body.appendChild(renderer.view);

// create the root of the scene graph
var stage = new PIXI.Container();

PIXI.loader
    .add('_assets/basics/fighter.json')
    .load(onAssetsLoaded);

var movie;
var rect1 = new PIXI.Graphics();
var rect2 = new PIXI.Graphics();

function onAssetsLoaded()
{
    // create an array of textures from an image path
    var frames = [];

    for (var i = 0; i < 30; i++) {
        var val = i < 10 ? '0' + i : i;

        // magically works since the spritesheet was loaded with the pixi loader
        frames.push(PIXI.Texture.fromFrame('rollSequence00' + val + '.png'));
    }


    // create a MovieClip (brings back memories from the days of Flash, right ?)
    movie = new PIXI.extras.MovieClip(frames);

    /*
     * A MovieClip inherits all the properties of a PIXI sprite
     * so you can change its position, its anchor, mask it, etc
     */
    movie.position.set(300);

    movie.anchor.set(0.0);
    movie.animationSpeed = 0.5;

    movie.play();

    stage.addChild(movie);
  stage.addChild(rect1);
  stage.addChild(rect2);

    animate();
}

function animate() {
    movie.rotation += 0.01;

    var bunny = movie;
    var bounds = bunny.getBounds();
    rect1.clear();
    rect1.lineStyle(2, 0xff0000, 1);
    rect1.drawRect(bounds.x, bounds.y, bunny.width, bunny.height);
    rect1.endFill();

    rect2.clear();
    rect2.lineStyle(2, 0x00ff00, 1);
    rect2.drawRect(bounds.x, bounds.y, bounds.width, bounds.height);
    rect2.endFill();
  
    // render the stage container
    renderer.render(stage);

    requestAnimationFrame(animate);
}

```

Wrong graphics size (flickering) because of localBounds bug since v4. #2631

```js
var renderer = new PIXI.WebGLRenderer(800, 600);

document.body.appendChild(renderer.view);

var stage = new PIXI.Container();

var g = new PIXI.Graphics();
g.beginFill(0xff00ff, 0.5);
g.drawRect(0, 0, 100, 100);
g.endFill();
stage.addChild(g);

setInterval(function(){ g.width = 200; console.log(g.width); }, 1000);

animate();

function animate() {
    requestAnimationFrame(animate);

    renderer.render(stage);
}
```

Testing mesh bounds

```js
var renderer = PIXI.autoDetectRenderer(800, 600);
document.body.appendChild(renderer.view);

// create the root of the scene graph
var stage = new PIXI.Container();

var count = 0;

// build a rope!
var ropeLength = 918 / 20;
var ropeLength = 45;

var points = [];

for (var i = 0; i < 25; i++)
{
    points.push(new PIXI.Point(i * ropeLength, 0));
}

var strip = new PIXI.mesh.Rope(PIXI.Texture.fromImage('_assets/snake.png'), points);

strip.position.x = -40;
strip.position.y = 300;

stage.addChild(strip);

var rect1 = new PIXI.Graphics();
stage.addChild(rect1);

var g = new PIXI.Graphics();

g.x = strip.x;
g.y = strip.y;
stage.addChild(g);

// start animating
animate();

function animate() {

    count += 0.1;

    // make the snake
    for (var i = 0; i < points.length; i++) {

        points[i].y = Math.sin((i * 0.5) + count) * 30;

        points[i].x = i * ropeLength + Math.cos((i * 0.3) + count) * 20;

    }
  
    var bounds = strip.getBounds();
    rect1.clear();
    rect1.lineStyle(2, 0xff0000, 1);
    rect1.drawRect(bounds.x, bounds.y, bounds.width, bounds.height);
    rect1.endFill();

    // render the stage
    renderer.render(stage);

    renderPoints();

    requestAnimationFrame(animate);
}

function renderPoints () {

    g.clear();

    g.lineStyle(2,0xffc2c2);
    g.moveTo(points[0].x,points[0].y);

    for (var i = 1; i < points.length; i++) {
        g.lineTo(points[i].x,points[i].y);
    };

    for (var i = 1; i < points.length; i++) {
        g.beginFill(0xff0022);
        g.drawCircle(points[i].x,points[i].y,10);
        g.endFill();
    };
}

```

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Ugh, cacheAsBitmap is wrong. Fixing.

**Comment by ivanpopelyshev** [comment]
Testing one more thing #2631: 

```js
var renderer = PIXI.autoDetectRenderer(800, 600,{backgroundColor : 0x1099bb});
document.body.appendChild(renderer.view);
var stage = new PIXI.Container();

var container = new PIXI.Container();
stage.addChild(container);
var mySprite = createSprite();
stage.addChild(mySprite);

container.position.set(300, 100);

setTimeout(step1, 1000);
setTimeout(step2, 2000);
setTimeout(step3, 3000);

function step1()
{
	console.log("Step1");
	container.addChild(mySprite);
	console.log(mySprite.width); // the width is 118, this is correct
}

function step2()
{
	console.log("Step2")
	stage.addChild(mySprite);
	console.log(mySprite.width) // width is now 415.5 .. that is NOT Correct
}

function step3()
{
	console.log("Step3")
	console.log(mySprite.width) // width is 118 again after rendering. yay

}

function createSprite()
{
	var container = new PIXI.Container();

	var gfx = new PIXI.Graphics();
	gfx.beginFill(0xff0000);
	gfx.lineStyle(13, 0xffffff);
	gfx.drawRoundedRect(0, 0, 105, 60, 10);
	gfx.endFill();
	container.addChild(gfx);
	
	var debugRect = new PIXI.Graphics();
	debugRect.beginFill(0x00ffff);
	debugRect.drawRect(0, 0, 100, 50);
	debugRect.endFill();
	//workaround for generateTexture
	debugRect.parent = stage;
	var tex = renderer.generateTexture(debugRect); // image of 100x50 pixels
	debugRect.parent = null;
	
	var sprite = new PIXI.Sprite(tex);
	sprite.position.set((gfx.width - sprite.width) / 2, (gfx.height - sprite.height) / 2);
	container.addChild(sprite);
	return container;
}

PIXI.ticker.shared.add(() => {
	renderer.render(stage);
});
```

Need 3 x 118 in console. Test is passed.

**Comment by ivanpopelyshev** [comment]
cacheIsBitmap test bug, again:

```js
var renderer = PIXI.autoDetectRenderer(800, 600);
document.body.appendChild(renderer.view);

// create the root of the scene graph
var stage = new PIXI.Container();

// load resources
PIXI.loader
    .add('spritesheet','_assets/monsters.json')
    .load(onAssetsLoaded);

// holder to store aliens
var aliens = [];
var alienFrames = ['eggHead.png', 'flowerTop.png', 'helmlok.png', 'skully.png'];

var count = 0;

// create an empty container
var alienContainer = new PIXI.Container();
alienContainer.position.x = 400;
alienContainer.position.y = 300;

var mask = PIXI.Sprite.fromImage('_assets/flowerTop.png');
mask.anchor.set(0.5);
mask.scale.set(10)
mask.position.x = 400;
mask.position.y = 300;
alienContainer.mask = mask;
alienContainer.addChild(mask)

// make the stage interactive
stage.interactive = true;

stage.addChild(alienContainer);

function onAssetsLoaded()
{
    // add a bunch of aliens with textures from image paths
    for (var i = 0; i < 100; i++)
    {
        var frameName = alienFrames[i % 4];

        // create an alien using the frame name..
        var alien = PIXI.Sprite.fromFrame(frameName);
        alien.tint = Math.random() * 0xFFFFFF;

        /*
         * fun fact for the day :)
         * another way of doing the above would be
         * var texture = PIXI.Texture.fromFrame(frameName);
         * var alien = new PIXI.Sprite(texture);
         */
        alien.position.x = Math.random() * 800 - 400;
        alien.position.y = Math.random() * 600 - 300;
        alien.anchor.x = 0.5;
        alien.anchor.y = 0.5;
        aliens.push(alien);
        alienContainer.addChild(alien);
    }

    // start animating
    requestAnimationFrame(animate);
}

stage.on('click', onClick);
stage.on('tap', onClick);

function onClick()
{
    alienContainer.cacheAsBitmap = !alienContainer.cacheAsBitmap;

//        feel free to play with what's below
//        var sprite = new PIXI.Sprite(alienContainer.generateTexture());
//        stage.addChild(sprite);
//        sprite.position.x = Math.random() * 800;
//        sprite.position.y = Math.random() * 600;
}

function animate() {
    // let's rotate the aliens a little bit
    for (var i = 0; i < 100; i++)
    {
        var alien = aliens[i];
        alien.rotation += 0.1;
    }

    count += 0.01;

    alienContainer.scale.x = Math.sin(count);
    alienContainer.scale.y = Math.sin(count);

    alienContainer.rotation += 0.01;

    // render the stage
    renderer.render(stage);

    requestAnimationFrame(animate);
}
```

lines 23-29 were added

**Comment by ivanpopelyshev** [comment]
And new test is working! YAY!

By the way, now we can remove 4-th parameter of SystemRenderer.render . And may be 5-th will be removed later too.

**Comment by ivanpopelyshev** [comment]
One more test, easy one. pixi.js v4 fails it without my patch:

```js
var renderer = PIXI.autoDetectRenderer(800, 600);
document.body.appendChild(renderer.view);

// create the root of the scene graph
var stage = new PIXI.Container();

// load resources
PIXI.loader
    .add('spritesheet','_assets/monsters.json')
    .load(onAssetsLoaded);

// holder to store aliens
var aliens = [];
var alienFrames = ['eggHead.png', 'flowerTop.png', 'helmlok.png', 'skully.png'];

var count = 0;

// create an empty container
var alienContainer = new PIXI.Container();
alienContainer.position.set(0);

var graphics = new PIXI.Graphics();
graphics.beginFill(0xFFFFFF);
graphics.drawRect(0, 0, 200, 200);
graphics.endFill();
graphics.position.set(100);
alienContainer.addChild(graphics);

var mask = PIXI.Sprite.fromImage('_assets/flowerTop.png');
alienContainer.mask = mask;
mask.position.set(200);
mask.anchor.set(0.5);
alienContainer.addChild(mask)

// make the stage interactive
stage.interactive = true;

stage.addChild(alienContainer);

function onAssetsLoaded()
{
    // start animating
    requestAnimationFrame(animate);
}

stage.on('click', onClick);
stage.on('tap', onClick);

function onClick()
{
    alienContainer.cacheAsBitmap = !alienContainer.cacheAsBitmap;

}

function animate() {
    // render the stage
    renderer.render(stage);

    requestAnimationFrame(animate);
}
```

**Comment by ivanpopelyshev** [comment]
Also I recomment to remove "transform" from RenderTarget, it is obsolete now.

**Comment by bigtimebuddy** [comment]
@ivanpopelyshev Can you please create some unit tests for this PR? Unit tests are more helpful than examples or demos.

**Comment by ivanpopelyshev** [comment]
@bigtimebuddy If you show me what you've done already, I will make tests in that format :)

**Comment by bQvle** [comment]
Issues with Graphics:

```
var renderer = PIXI.autoDetectRenderer(800, 600);
document.body.appendChild(renderer.view);

// create the root of the scene graph
var stage = new PIXI.Container();

// load resources
PIXI.loader
    .add('spritesheet','_assets/monsters.json')
    .load(onAssetsLoaded);

// holder to store aliens
var aliens = [];
var alienFrames = ['eggHead.png', 'flowerTop.png', 'helmlok.png', 'skully.png'];

var count = 0;

// create an empty container
var alienContainer = new PIXI.Container();
alienContainer.position.set(0);

var graphics = new PIXI.Graphics();
graphics.beginFill(0xFFFFFF);
graphics.drawRect(0, 0, 800, 600);
graphics.endFill();
graphics.position.set(-400,-300);
alienContainer.addChild(graphics);

var mask = PIXI.Sprite.fromImage('_assets/flowerTop.png');
alienContainer.mask = mask;
mask.anchor.set(0.5);
mask.scale.set(3)
alienContainer.addChild(mask);
alienContainer.position.set(400,300);


// make the stage interactive
stage.interactive = true;

stage.addChild(alienContainer);

function onAssetsLoaded()
{
    // start animating
    requestAnimationFrame(animate);
}

stage.on('click', onClick);
stage.on('tap', onClick);

function onClick()
{
    alienContainer.cacheAsBitmap = !alienContainer.cacheAsBitmap;

}

function animate() {
    alienContainer.rotation += 0.01
  
    // render the stage
    renderer.render(stage);

    requestAnimationFrame(animate);
}
```

**Comment by englercj** [comment]
> @bigtimebuddy If you show me what you've done already, I will make tests in that format :)

You can find the current suite in the test directory:

https://github.com/pixijs/pixi.js/tree/master/test

**Comment by ivanpopelyshev** [comment]
toLocal, toGlobal and getLocalBounds() fixed that way they dont need displayObject.updateTransform(): 

```js
const sprite1 = new PIXI.Sprite(PIXI.Texture.EMPTY);
sprite1.position = new PIXI.Point(10,10);
const grandParentContainer = new PIXI.Container();
const parentContainer = new PIXI.Container();
parentContainer.x = -50;

grandParentContainer.addChild(parentContainer);
parentContainer.addChild(sprite1);

let localCoordinates = parentContainer.toLocal(new PIXI.Point(0, 0), sprite1);
console.log(localCoordinates); //10, 10
localCoordinates = sprite1.toLocal(new PIXI.Point(0, 0), parentContainer);
console.log(localCoordinates); //-10, -10
let globaCoordinates = sprite1.toGlobal(new PIXI.Point(0, 0));
console.log(globaCoordinates); //-40, 10
```

**Pull request closed without merging**
