### PR TITLE
Fix texture's frame dimension error report

### PR DESCRIPTION
**Pull request by EcutDavid**
What's the error: 
The error will tell you both X and Y are wrong if you only one of them has incorrect value:
For example, set the height to `Number.MAX_VALUE`, then:
image

Why change `frame && frame.width ...` to `frame.width ...`?
If `frame == undefined`, it already breaks during  `if (frame.x + frame.width > this.baseTexture.width || frame.y + frame.height > this.baseTexture.height)` :)

### CODE REVIEW

**Comment by englercj** [comment]
The error message isn't saying both are wrong. It is saying something is wrong and dumping the information to let you find out the issue. I like the idea of just getting all the information when the error happens.

**Comment by EcutDavid** [comment]
Thanks, I'll come up with changes that fix the wrong `>` :)
image

**Comment by englercj** [comment]
If you want to be pedantic, you could just put an "OR" between them.

**Comment by EcutDavid** [comment]
Hey @englercj @ivanpopelyshev thanks, changes in
image

**Comment by EcutDavid** [comment]
image
🤔

**Comment by ivanpopelyshev** [comment]
Guys, do we have a problem with travis?

**Comment by bigtimebuddy** [comment]
Thanks for the PR @EcutDavid!

**Comment by Hoangminhtrang0109** [comment]
HVT: Nguyễn Văn Công NS: 17/07/1990 CMT:031090000662 GMAIL: minhtrang.hp010915@gmail.com STK: 2108205048930 NH: Agribank Cát Bà

**Pull request merged**
