### PR TITLE
Fix wrong video frame when update

### PR DESCRIPTION
**Pull request by meowtec**
`frame` on video texture is incorrect... fix it 

##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included
- [ ] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Could you provide an example so we can verify?

**Comment by meowtec** [comment]
OK

**Comment by ivanpopelyshev** [comment]
I think we fixed it in v5.

@meowtec Did you test it on your videos? I think that `onBaseTextureLoaded` fired before `onBaseTextureUpdated` and it actually switches `noFrame` to `false` by assigning something to `frame` property. Is it true that in your case `onBaseTextureLoaded` is not fired, but `onBaseTextureUpdated` is fired?

**Comment by meowtec** [comment]
https://jsfiddle.net/3ytxwes9/

下载

**Comment by meowtec** [comment]
@ivanpopelyshev 

Because I am using frame property to `crop` videos and images, the behavior on video is incorrect.
Yes I am using PIXI@4, maybe will upgrade to v5, but not now.

**Comment by ivanpopelyshev** [comment]
please elaborate. Do you change baseTexture width/height manually somehow?

**Comment by meowtec** [comment]
No, my code:
```javascript
  const texture = Texture.from(media)
  texture.frame = new Rectangle(
    0,
    0,
    texture.width * 0.5,
    texture.height * 0.5,
  )
  const sprite = new Sprite(texture)
  sprite.width = app.screen.width / 2 
  sprite.height = app.screen.height / 2
  sprite.x = 0
  sprite.y = 0

  app.stage.addChild(sprite)
```

I just crop a video and put it to the stage.

**Comment by meowtec** [comment]
Please look the reproduction: https://github.com/pixijs/pixi.js/pull/5777#issuecomment-501336118

**Comment by bigtimebuddy** [comment]
Here's with this fix applied:

https://jsfiddle.net/ye2mn6u7/

**Comment by meowtec** [comment]
I have two sprites: one for video and the other one for image.
They has the same width/height, the same texture width/height, and the same frame.
So I except them having the same size on the screen, right? But the video sprite is much bigger (2x2) them the image sprite.

**Comment by meowtec** [comment]
You mean that I just override the `onBaseTextureUpdated` function? 
That is also OK.

**Comment by bigtimebuddy** [comment]
@meowtec is this still something you're looking for or did you find a workaround?

**Comment by meowtec** [comment]
@bigtimebuddy I just have overwritten `Texture.prototype.onBaseTextureUpdated = function() {...}` in my project.

**Pull request closed without merging**
