### PR TITLE
Don't set any defaults for properties of MeshMaterial and State in Mesh constructor

### LINKED ISSUE #6907: [BUG] Mesh constructor should not change any property of the passed in MeshMaterial/State
### Expected Behavior
The `Mesh` constructor should not change any property of the passed in `MeshMaterial`/`State`.

### Current Behavior
The `Mesh` constructor resets the tint value of the passed in `MeshMaterial` and also the blend mode of the passed in `State` which should not be the case.

### Possible Solution
Remove:
https://github.com/pixijs/pixi.js/blob/a4c1e3d58159138f99e2714c476360932ebf0152/packages/mesh/src/Mesh.ts#L148-L149

### PR DESCRIPTION
**Pull request by teoxoy**
fix #6907

##### Description of change

Don't set any defaults for properties of `MeshMaterial` and `State` in `Mesh` constructor

##### Pre-Merge Checklist

- [ ] Tests and/or benchmarks are included
- [ ] Documentation is changed or added
- [ ] Lint process passed (`npm run lint`)
- [ ] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by teoxoy** [comment]
Any updates on this?

**Comment by bigtimebuddy** [comment]
I agree, these lines seems redundant. Both MeshMaterial and State set these defaults already. I'm not sure what the original intention of this was here.  These lines were added here #5132 (this was my cleanup of @GoodBoyDigital's PR). He is the original author and could clarify the intention.

Need to get to the bottom of that, but overall this seems reasonable.

**Review by ivanpopelyshev — APPROVED** [review]

**Review by GoodBoyDigital — APPROVED** [review]
looks cool to me!

**Comment by bigtimebuddy** [comment]
Thanks you @teoxoy, sorry it took so long!

**Pull request merged**
