### PR TITLE
Format the application docs to be exported

### PR DESCRIPTION
**Pull request by bigtimebuddy**
### Fixed

* Update the documentation according to: #7159 
* Fixes docs bug with instance methods `start` and `stop` of TickerPlugin
* Renamed typedef `PIXI.Application.Plugin` to match types `PIXI.IApplicationPlugin`
* Fix types for `IApplicationPlugin` to be stricter

### webdoc Bug

* ~~Issue with `@typedef` + TypeScript `interface` https://github.com/webdoc-labs/webdoc/issues/76~~

### CODE REVIEW

**Comment by SukantPal** [comment]
I published @webdoc/cli@1.1.5 and fixed the issues. This PR should work fine with it now. I don't understand tho - why do we need `IApplicationPlugin` to be a type definition instead of an interface?

**Comment by bigtimebuddy** [comment]
I'm not sure I understand your question @SukantPal. We used typedef in JSDoc because there was no interface doc type. Is there in webdoc?

**Comment by SukantPal** [comment]
I think JSDoc 3 has [@interface](https://jsdoc.app/tags-interface.html). We already have them on the dev documentation: [IBitmapFontOptions](http://pixijs.download/dev/docs/PIXI.IBitmapFontOptions.html) for example.

webdoc already supports interfaces from Typescript source code. So you don't have to use the interface tag anymore.

```ts
/**
 * @memberof PIXI
 */
export interface IApplicationPlugin {
    /**
     * Called when Application is constructed, scoped to Application instance. Passes in `options` as
     * the only argument, which are Application constructor options.
     *
     * @param options
     */
    init(options: IApplicationOptions): void;

    /**
     * Called when destroying Application, scoped to Application instance
     */
    destroy(): void;
}
```

**Comment by bigtimebuddy** [comment]
That's way better

**Review by SukantPal — APPROVED** [review]

**Review by Zyie — APPROVED** [review]

**Pull request merged**
