### PR TITLE
HitTest hole fix

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
Fix for #6156 , thanks to @xuyangbill

Doesn't work: https://www.pixiplayground.com/#/edit/XSqLaGQ_Htc9T1N8WSYlj
Fixed: https://www.pixiplayground.com/#/edit/qZJGOVcZm~qTrm2orFgtX

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
Added test.

**Comment by cursedcoder** [comment]
What if we add a hole inside a hole?

**Comment by ivanpopelyshev** [comment]
Yes, its in the test.

**Comment by ivanpopelyshev** [comment]
@cursedcoder do you think there'll be people who call beginHole() inside a hole? :)

**Pull request merged**
