### PR TITLE
Add `precision, attributeLocations` parameters to Shader

### PR DESCRIPTION
**Pull request by finscn**
Update version of pixi-gl-core,  and ddd `precision, attributeLocations` parameters to Shader.

### CODE REVIEW

**Comment by GoodBoyDigital** [comment]
hello! not sure if we need this after the refactor from here: https://github.com/pixijs/pixi.js/tree/dev-geometry-update

**Comment by finscn** [comment]
@GoodBoyDigital  ， I see https://github.com/pixijs/pixi.js/blob/dev-geometry-update/src/core/shader/Shader.js  ， there is no `precision, attributeLocations`.

**Comment by ivanpopelyshev** [comment]
@finscn its in dependency, here: https://github.com/pixijs/pixi-gl-core/blob/master/src/GLShader.js

**Comment by finscn** [comment]
I know the pixi-gl-core will be removed in PIXI 5.x .
But I hope this feature could be included in PIXI 4.x .
It could make the PIXI 4.x be better .

**Comment by ivanpopelyshev** [comment]
I forked v5 and rewrote shaders to typescipt, and I saw that in 'next" branch of pixi there are attributes and locations inside the shader,

**Comment by englercj** [comment]
Yes, this is supported in the v5 refactor

**Comment by finscn** [comment]
Your mean is that this feature won't be included in PIXI 4.x ？

**Comment by GoodBoyDigital** [comment]
Hi all! Closing this one as we will be adding this to v5 👍

**Comment by finscn** [comment]
@GoodBoyDigital  , please don't forget this pr

**Pull request closed without merging**
