### PR TITLE
Feature/bmpfont txt parser

### PR DESCRIPTION
**Pull request by maurodetarso**
##### Description of change
Added support for bmglyph txt-based bitmap font data alongside regular XML data, using the same bitmap font API and changing existing code as little as possible.

##### Pre-Merge Checklist
- [x] Tests and/or benchmarks are included
- [x] Documentation is changed or added
- [x] Lint process passed (`npm run lint`)
- [x] Tests passed (`npm run test`)

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Good feature! Thanks for doing this.

Organizationally, a place for improvement is to separate the parsers and loaders for each format instead of having different methods for xml and text. Would make it nice and clean and make it easier for us to split our into different packages if need be. Also this way each format is fully encapsulated and we should add unit test for each individually.

**Comment by GoodBoyDigital** [comment]
Nice idea that! Two separate loaders would make more sense!

**Comment by bigtimebuddy** [comment]
@maurodetarso do you think you'll be able to address the feedback?

**Comment by bigtimebuddy** [comment]
Closing this in favor of #6347

**Pull request closed without merging**
